### ISSUE TITLE
Weird error with AppImage when pressing ANY key in gui

### ISSUE THREAD

**Issue by wolfy01** [srevinsaju/guiscrcpy#103]
```
/tmp/.mount_guiscrSXpQvR/AppRun: line 27: 10914 Segmentation fault      ${APPDIR}/usr/bin/python3.8 -s ${APPDIR}/opt/python3.8/bin/guiscrcpy "$@"
```
No idea why this is happening

**Comment by wolfy01** [comment]
Also get the same error when closing guiscrcpy

**Comment by srevinsaju** [comment]
@wolfy01 can you show me your `neofetch` ?

**Comment by wolfy01** [comment]
I'm using Debian 10. Also, `neofetch` doesn't work in my terminal.

**Comment by srevinsaju** [comment]
@wolfy01 maybe 
```bash
sudo apt install neofetch
```

**Comment by wolfy01** [comment]
```
       _,met$$$$$gg.          user@penguin 
    ,g$$$$$$$$$$$$$$$P.       ----------------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 10 (buster) on Chrome OS x86_64                                                                                                                                 
 ,$$P'              `$$$.     Host: crosvm                                                                                                                                                                         
',$$P       ,ggs.     `$$b:   Kernel: 4.19.87-07826-g55ab70aff690                                                                                                                                                  
`d$$'     ,$P"'   .    $$$    Uptime: 46 mins                                                                                                                                                                      
 $$P      d$'     ,    $$P    Packages: 726 (dpkg)                                                                                                                                                                 
 $$:      $$.   -    ,d$$'    Shell: bash 5.0.3                                                                                                                                                                    
 $$;      Y$b._   _,d$P'      Resolution: 1512x853                                                                                                                                                                 
 Y$$.    `.`"Y$$$$P"'         Theme: CrosAdapta [GTK2/3]                                                                                                                                                           
 `$$b      "-.__              Icons: CrosAdapta [GTK2/3]                                                                                                                                                           
  `Y$$                        Terminal: ld-linux-x86-64                                                                                                                                                            
   `Y$$.                      CPU: 06/4c (4) @ 1.600GHz                                                                                                                                                            
     `$$b.                    Memory: 222MiB / 2844MiB                                                                                                                                                             
       `Y$$b.                                                                                                                                                                                                      
          `"Y$b._                                                                                                                                                                                                  
              `"""                                                                                                                                                                                                 
```

And yes, I can confirm that I am using Chrome OS. Maybe that has to do with this issue?

**Comment by srevinsaju** [comment]
Thanks for the information. 
Actually our appimages are still in beta. we are working on it. 
I would be very grateful if you tell me if the following works
```bash
pip3 install -U guiscrcpy
wget https://dl.google.com/android/repository/platform-tools-latest-linux.zip
unzip platform-tools-latest-linux.zip -d adb
sudo cp adb/platform-tools/adb /usr/bin/.
guiscrcpy
```

**Comment by wolfy01** [comment]
> Can you tell me how Debian 10 works on Chrome OS natively. Sorry for this question
I actually don't know how it works on Chrome OS. There's only a terminal really, and AppImages do work on Chrome OS.

**Comment by srevinsaju** [comment]
@wolfy01 I am curious. Do you have a GUI?

**Comment by wolfy01** [comment]
If your referring to linux, no, just a terminal.

**Comment by srevinsaju** [comment]
Oh yes. Thats the reason, `guiscrcpy` needs a display to work. To confirm, can you tell me the output of this command
```bash
echo $DISPLAY
```

**Comment by wolfy01** [comment]
I have a display, lol.. And I think Chrome OS is linux? Also I do have the GUI showing for guiscrcpy.

**Comment by srevinsaju** [comment]
Ok, makes sense. 
Did you try out this https://github.com/srevinsaju/guiscrcpy/issues/103#issuecomment-619417620

**Comment by wolfy01** [comment]
> @wolfy01 Ok, makes sense.
> Did you try out this [#103 (comment)](https://github.com/srevinsaju/guiscrcpy/issues/103#issuecomment-619417620)

Currently i'm getting the `egg_info` error when running `pip3 install -U guiscrcpy`

```
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-11n1t0z7/PyQt5/
```

**Comment by srevinsaju** [comment]
Seems like your device doesn't support PyQt5 wheels for `manylinux2014`, I will check it out

**Comment by srevinsaju** [comment]
Are you having an ARM device?

**Comment by wolfy01** [comment]
> @wolfy01 Are you having an ARM device?

No.
`x86_64` aka `AMD64`

**Comment by srevinsaju** [comment]
ok, I will try it out on a chromium VM. 
By the way, there are apt packages for PyQt5, but please note, `guiscrcpy` requires PyQt5 >= 5.14

**Comment by wolfy01** [comment]
Also it appears that `PyQt5` does not work in Chrome OS D: 
I don't know for sure though.

`sudo apt-get install python3-pyqt5` Seems to work, but I have no idea what version it is

**Comment by srevinsaju** [comment]
```python
import inspect
from PyQt5 import Qt

vers = ['%s = %s' % (k,v) for k,v in vars(Qt).items() if k.lower().find('version') >= 0 and not inspect.isbuiltin(v)]
print('\n'.join(sorted(vers)))
```

**Comment by wolfy01** [comment]
Ah, ok. Yea, only `5.11.3`

**Comment by srevinsaju** [comment]
@wolfy01 See [this](https://pkgs.org/search/?q=PyQt5) for PyQt5 apt packages (5.14.2)

**Comment by wolfy01** [comment]
> @wolfy01 See [this](https://pkgs.org/search/?q=PyQt5) for PyQt5 apt packages (5.14.2)

I don't see `5.14.2`?

**Comment by srevinsaju** [comment]
its for `Debian sid`  aka `testing`

**Comment by srevinsaju** [comment]
@wolfy01 Try this
```bash
sudo apt-get update && apt-get install \
    -y --no-install-recommends \
    python3-pip \
    python3-setuptools
```
and then
```
pip3 install PyQt5==5.14.2
```

**Comment by wolfy01** [comment]
```
The scripts pylupdate5, pyrcc5 and pyuic5 are installed in '/home/user/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```
Everything worked, I just got this warning. Should I ignore it?

**Comment by srevinsaju** [comment]
Nah no problem 
Now, 
```bash
pip3 install guiscrcpy --no-deps
pip3 install pynput pystray
```

**Comment by wolfy01** [comment]
```
guiscrcpy 3.7 requires fonttools, which is not installed.
guiscrcpy 3.7 requires psutil, which is not installed.
guiscrcpy 3.7 has requirement PyQt5==5.14.2, but you'll have pyqt5 5.14.0 which is incompatible.
Installing collected packages: python-xlib, pynput, Pillow, pystray
Successfully installed Pillow-7.1.2 pynput-1.6.8 pystray-0.15.0 python-xlib-0.27
```

```
wolfy@penguin:~$ guiscrcpy
-bash: guiscrcpy: command not found
```

**Comment by srevinsaju** [comment]
Ok, 
run 
```bash
python3 -m guiscrcpy
```

**Comment by wolfy01** [comment]
> Ok,
> run
> 
> ```shell
> python3 -m guiscrcpy
> ```

Seems to be working!

**Comment by srevinsaju** [comment]
Yay! great

**Comment by wolfy01** [comment]
Besides `scrcpy` not being in path? Although it does work in the terminal itself.

**Comment by srevinsaju** [comment]
@wolfy01 Do you have `scrcpy` ?

**Comment by wolfy01** [comment]
> @wolfy01 Do you have `scrcpy` ?

Yes, and it works.
```
wolfy@penguin:~$ scrcpy
INFO: scrcpy 1.12.1 <https://github.com/Genymobile/scrcpy>
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 6.1 MB/s (26202 bytes in 0.004s)
INFO: Initial texture: 1440x2880
```

**Comment by srevinsaju** [comment]
@wolfy01 That is because, (if you do have scrcpy), 
scrcpy is installed to `/usr/bin` which is probably on your PATH
```bash
echo $PATH
```
You will see that `/home/wolfy3543/.local/bin` is not on `PATH`.
To fix that
```bash
export PATH=$PATH:/home/wolfy3543/.local/bin
```

**Comment by wolfy01** [comment]
Okay, I got it to work, but I can't move any of the windows when connecting to my device.

**Comment by srevinsaju** [comment]
After connecting, before connecting or while connecting?

**Comment by wolfy01** [comment]
> After connecting, before connecting or while connecting?

I mean the control bars that pop up after connecting. I tried using `ALT` + `Left Click` but that didn't work either.

**Comment by srevinsaju** [comment]
Oh ok, use the dots to move them

**Comment by wolfy01** [comment]
> Oh ok, use the dots to move them

Thats what i've been trying to do. 🤔

**Comment by srevinsaju** [comment]
Thats odd, anything in logs

**Comment by wolfy01** [comment]
> Thats odd, anything in logs

Nope, nothing.

**Comment by srevinsaju** [comment]
I will check that

**Comment by srevinsaju** [comment]
I will provide a fix in 5 mins

**Comment by wolfy01** [comment]
> I will check that, sorry about it

Alright

**Comment by srevinsaju** [comment]
Can you provide a screenshot of guiscrcpy with the popup windows?

**Comment by wolfy01** [comment]
> Can you provide a screenshot of guiscrcpy with the popup windows? If possible. I would be grateful to you

![image](https://user-images.githubusercontent.com/45273698/80288244-c00e4100-8704-11ea-9416-9e4378587c08.png)

**Comment by srevinsaju** [comment]
@wolfy01 Thanks, I have added the support to display title bars temporarily
```bash
pip3 install https://github.com/srevinsaju/guiscrcpy/archive/beta-37.zip --no-deps
```
Run guiscrcpy by 
```bash
guiscrcpy --force_window_frame
```
or 
```bash
python3 -m guiscrcpy --force_window_frame
```

**Comment by wolfy01** [comment]
> @wolfy01 Thanks, I have added the support to display title bars temporarily
> 
> ```shell
> pip3 install https://github.com/srevinsaju/guiscrcpy/archive/beta-37.zip --no-deps
> ```
> 
> Run guiscrcpy by
> 
> ```shell
> guiscrcpy --force_window_frame
> ```
> 
> or
> 
> ```shell
> python3 -m guiscrcpy --force_window_frame
> ```

Thanks! Also, I have discovered another interesting error while playing around with guiscrcpy. 
```
WARNING:root:Launching notification auditor
Traceback (most recent call last):
  File "/home/wolfy/.local/lib/python3.7/site-packages/guiscrcpy/launcher.py", line 540, in start_act
    NotifyAuditor()
  File "/home/wfoly/.local/lib/python3.7/site-packages/guiscrcpy/lib/notify.py", line 37, in __init__
    icon.visible = True
  File "/home/wolfy/.local/lib/python3.7/site-packages/pystray/_base.py", line 157, in visible
    self._update_icon()
  File "/home/wolfy/.local/lib/python3.7/site-packages/pystray/_xorg.py", line 276, in inner
    if threading.current_thread().ident == self._thread.ident:
AttributeError: 'Icon' object has no attribute '_thread'
Aborted
```

**Comment by srevinsaju** [comment]
Yup, notification aduitor is not used by anyone anymore. There are more modern implementaions to get the mobile notifications, see [KDE Connect](https://kdeconnect.kde.org/) a better implementation, and efficient too.

The current error you have got is because Chrome OS is not supported by the `pystray` module. You can only use the `notification aduitor` if you have a taskbar. On Linux (KDE), its the taskbar, on Windows OS, its the bottom taskbar etc. You can check about that. ChromeOS taskbar is not actually a taskbar, and is probably not supported by it. Thanks. I will add a fix for that too

**Comment by wolfy01** [comment]
> Yup, notification aduitor is not used by anyone anymore. There are more modern implementaions to get the mobile notifications, see [KDE Connect](https://kdeconnect.kde.org/) a better implementation, and efficient too.
> 
> The current error you have got is because Chrome OS is not supported by the `pystray` module. You can only use the `notification aduitor` if you have a taskbar. On Linux (KDE), its the taskbar, on Windows OS, its the bottom taskbar etc. You can check about that. ChromeOS taskbar is not actually a taskbar, and is probably not supported by it. Thanks. I will add a fix for that too

Ah, okay, also the tall display bar I cannot move because I can't make the top part of the window big enough to move it.

**Comment by srevinsaju** [comment]
Hmm, thats the best I can do as a temporary fix. I will check why it doesn't work on Chrome OS. Chrome OS has its own desktop manager and implements its functions in a different way a compared to other popular Linux Desktop Window managers like GNOME , KDE, XFCE and LXDE. I will check it on StackOverflow or some other website and try to find a fix about it. 

PS: Does Alt click help to move the window now?

**Comment by wolfy01** [comment]
> PS: Does Alt click help to move the window now?

Nope

**Comment by wolfy01** [comment]
Also, is it possible that you could add an option to disable the arrow panel?

**Comment by srevinsaju** [comment]
Sure

**Comment by srevinsaju** [comment]
@wolfy01 I have fixed the arrow panel. Repeat https://github.com/srevinsaju/guiscrcpy/issues/103#issuecomment-619428461

Please help me to find more bugs like this, before the next stable release 3.8

**Comment by wolfy01** [comment]
> @wolfy01 I have fixed the arrow panel. Repeat [#103 (comment)](https://github.com/srevinsaju/guiscrcpy/issues/103#issuecomment-619428461)
> 
> Please help me to find more bugs like this, before the next stable release 3.8

Will do
