### ISSUE TITLE
Please make it so you can type in custombitrate. 

### ISSUE THREAD

**Issue by wolfy01** [srevinsaju/guiscrcpy#104]
Believe it or not, it can actually be incredibly difficult to use the current way to set the bitrate. My WiFi can do 2M before some lag starts to happen, and I mean EXACTLY 2M xD, but thats very hard to set when using the gui.

`REQUEST`

**Comment by srevinsaju** [comment]
@wolfy01 can you please test `master` and let me know if it works

```bash
pip3 install https://github.com/srevinsaju/guiscrcpy/archive/master.zip --no-deps
guiscrcpy
```

**Comment by srevinsaju** [comment]
Merged to master
