### ISSUE TITLE
Error when scanning for network devices

### ISSUE THREAD

**Issue by Thyrador** [srevinsaju/guiscrcpy#107]
Getting this error, when trying to scan for network devices.
```python
Traceback (most recent call last):
  File "/snap/guiscrcpy/147/lib/python3.6/site-packages/guiscrcpy/ux/network.py", line 113, in refresh
    self.listView.addItems(self.nm.map_network())
  File "/snap/guiscrcpy/147/lib/python3.6/site-packages/guiscrcpy/network/network.py", line 63, in map_network
    jobs = multiprocessing.Queue()
  File "/snap/guiscrcpy/147/usr/lib/python3.6/multiprocessing/context.py", line 102, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/snap/guiscrcpy/147/usr/lib/python3.6/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/snap/guiscrcpy/147/usr/lib/python3.6/multiprocessing/context.py", line 67, in Lock
    return Lock(ctx=self.get_context())
  File "/snap/guiscrcpy/147/usr/lib/python3.6/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/snap/guiscrcpy/147/usr/lib/python3.6/multiprocessing/synchronize.py", line 59, in __init__
    unlink_now)
PermissionError: [Errno 13] Permission denied
```

My system informations:
```http
OS: Ubuntu 20.04 LTS x86_64 
Host: N85_N87,HJ,HJ1,HK1 
Kernel: 5.4.0-28-generic 
Uptime: 2 hours, 30 mins 
Packages: 2689 (dpkg), 9 (snap) 
Shell: bash 5.0.16 
Resolution: 1920x1080 
DE: Plasma 
WM: KWin 
WM Theme: Breeze 
Theme: Breeze Dark [Plasma], Breeze-Dark [GTK2/3] 
Icons: breeze-dark [Plasma], breeze-dark [GTK2/3] 
Terminal: konsole 
CPU: Intel i7-7700HQ (8) @ 3.800GHz 
GPU: NVIDIA GeForce GTX 1050 Ti Mobile 
GPU: Intel HD Graphics 630 
Memory: 4132MiB / 32002MiB 
```

**Comment by srevinsaju** [comment]
Thanks, I will check that and provide a fix before the release of 3.10 (within two or three days)

**Comment by srevinsaju** [comment]
@Thyrador Can you try this, and let me know if the issue persists
```bash

sudo snap connect guiscrcpy:netlink-audit 
sudo snap connect guiscrcpy:netlink-connector
sudo snap connect guiscrcpy:network
sudo snap connect guiscrcpy:network-bind
sudo snap connect guiscrcpy:network-control
sudo snap connect guiscrcpy:network-manager
sudo snap connect guiscrcpy:network-manager-observe
sudo snap connect guiscrcpy:network-observe
sudo snap connect guiscrcpy:network-setup-control
sudo snap connect guiscrcpy:network-setup-observe
sudo snap connect guiscrcpy:network-status

```

**Comment by Thyrador** [comment]
Running these commands will result in the following output:
```sh
Error: snap "guiscrcpy" has no plug named "netlink-audit"
Error: snap "guiscrcpy" has no plug named "netlink-connector"
Error: snap "guiscrcpy" has no plug named "network-control"
Error: snap "guiscrcpy" has no plug named "network-manager"
Error: snap "guiscrcpy" has no plug named "network-manager-observe"
Error: snap "guiscrcpy" has no plug named "network-observe"
Error: snap "guiscrcpy" has no plug named "network-setup-control"
Error: snap "guiscrcpy" has no plug named "network-setup-observe"
Error: snap "guiscrcpy" has no plug named "network-status"
```
Still getting this error when scanning for network devices (including app crashing)
```python
Traceback (most recent call last):
  File "/snap/guiscrcpy/147/lib/python3.6/site-packages/guiscrcpy/ux/network.py", line 113, in refresh
    self.listView.addItems(self.nm.map_network())
  File "/snap/guiscrcpy/147/lib/python3.6/site-packages/guiscrcpy/network/network.py", line 63, in map_network
    jobs = multiprocessing.Queue()
  File "/snap/guiscrcpy/147/usr/lib/python3.6/multiprocessing/context.py", line 102, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/snap/guiscrcpy/147/usr/lib/python3.6/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/snap/guiscrcpy/147/usr/lib/python3.6/multiprocessing/context.py", line 67, in Lock
    return Lock(ctx=self.get_context())
  File "/snap/guiscrcpy/147/usr/lib/python3.6/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/snap/guiscrcpy/147/usr/lib/python3.6/multiprocessing/synchronize.py", line 59, in __init__
    unlink_now)
PermissionError: [Errno 13] Permission denied
```

**Comment by srevinsaju** [comment]
Yes, I found the reason, it is because `snaps` are confined to start semaphores (threaded processes) on the host system due to confinement; I am trying to fix that

**Comment by Thyrador** [comment]
Great. No rush, take your time.
Just a quick question regarding this issue: will this also auto connect to adb, or do I still have to do it manually? (have to do it once my machine boots up and then ocassionally from time to time)

**Comment by srevinsaju** [comment]
> will this also auto connect to adb, or do I still have to do it manually? (have to do it once my machine boots up and then ocassionally from time to time)

You will have to connect to your android device once per session. `guiscrcpy` cannot do that; and that is android behavior. If you are skilled, you can create a shell script so that adb on your system automatically connects to your device at the start of the screen. Moreover, to enable mirroring over wifi, (if you are not rooted; looking at your gthub profiles, looks like you are an android modder); you will have to do some extra work; 
* Click the wifi icon on guiscrcpy's window
* connect your device 
* Accept permission on android
* click TCPIP button
* Then disconnect android
* Now enter your android's IP adresss; or scan for it 
* Click connect
* Close the child window
* Now start scrcpy normally 

If you are rooted, you can avoid some of the options, and go to developer options and enable ADB over WiIFi (On LOS and RR, its available) and click wifi button on guiscrcpy and enter IP address and then press button; it should connect

This will work as long as the adb-server is running on your system and you don't kill it

**Comment by Thyrador** [comment]
> (if you are not rooted; looking at your gthub profiles, looks like you are an android modder); 

I am? :D
Well, sort of. I am rooted, for sure and already told tasker to run adb and open a port on my android devices.
I did create some ***.desktop** shortcuts to run the typical adb connect before opening **scrcpy**.
Using the discovery feature of **guiscrcpy** I was hoping of not having to do that anymore (if not wanted) especially when testing devices.
Since the network adress will already be provided/discovered via the gui it could be executed right before starting **scrcpy**.
For example like:
```sh
adb connect $devaddr && scrcpy -s $devaddr
```
where **$devaddr** will be something like: `192.168.68.60:12345`
