### ISSUE TITLE
Error: No module named 'pystray'

### ISSUE THREAD

**Issue by Thyrador** [srevinsaju/guiscrcpy#108]
Getting this error when enabling **Notification Auditor**
```python
Traceback (most recent call last):
  File "/snap/guiscrcpy/147/lib/python3.6/site-packages/guiscrcpy/launcher.py", line 690, in start_act
    from guiscrcpy.lib.notify import NotifyAuditor
  File "/snap/guiscrcpy/147/lib/python3.6/site-packages/guiscrcpy/lib/notify.py", line 25, in <module>
    import pystray
ModuleNotFoundError: No module named 'pystray'
```
Installed pystray via pip and pip3:
```sh
$ pip3 install pystray
Requirement already satisfied: pystray in /home/user/.local/lib/python3.8/site-packages (0.15.0)
Requirement already satisfied: python-xlib>=0.17; sys_platform == "linux" in /home/user/.local/lib/python3.8/site-packages (from pystray) (0.27)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from pystray) (1.14.0)
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (from pystray) (7.0.0)
```
```sh
$ pip install pystray
Requirement already satisfied: pystray in /home/user/.local/lib/python2.7/site-packages (0.15.0)
Requirement already satisfied: Pillow in /home/user/.local/lib/python2.7/site-packages (from pystray) (6.2.2)
Requirement already satisfied: six in /home/user/.local/lib/python2.7/site-packages (from pystray) (1.14.0)
```

**Comment by srevinsaju** [comment]
@Thyrador, the `snap` package does not have support for the Notification Auditor support. You will have to manually install `guiscrcpy` as a `pip` package

```bash
pip3 install guiscrcpy
pip3 install pystray
```

**Comment by Thyrador** [comment]
@srevinsaju , thanks for your reply. Is there a way to provide the package (snapcraft.yaml?) somehow? So it would be either installed automatically or can I reference it in some way so it would appear inside the snap package?

**Comment by srevinsaju** [comment]
@Thyrador The notification aduitor is not commonly used by everyone, and is highy experimental and discontinued feature. If your aim is to show mobile notification your PC, I highly recommend you to use [KDE Connect](https://kdeconnect.kde.org/) which is available for all Linux distributions, and has a better implementation; Let me know if it works

**Comment by Thyrador** [comment]
Currently using [KDE Connect](https://kdeconnect.kde.org/), but wanted to avoid installing additional apps on my devices (if possible). Not quite happy with [KDE Connect](https://kdeconnect.kde.org/) so I was hoping for an alternative. If it is discontinued then we can close this ticket.

Thanks for your kind responses tho.

**Comment by srevinsaju** [comment]
Its ok, I am not sure if you would be satisfied with `guiscrcpy`'s notification aduitor too, I was planning to disable it for 3.10. Did you try out this `pip` package, and see how it feels?

**Comment by Thyrador** [comment]
No, didn't try it out yet, since you said it will be discontinued anyway. So there's no reason to get used to it :D
Until there's a better alternative than **KDE Connect** I'd probably stick with it for now.

**Comment by srevinsaju** [comment]
I am currently using KDE Connect and its been a cool app; hadn't had any issues with it so far. 

> No, didn't try it out yet, since you said it will be discontinued anyway. So there's no reason to get used to it :D

No, I meant, I can continue to develop it and not disable it on 3.10 tomorrow, when its released; if the current functionality is satisfactory.

For me `KDE Connect` >> `guiscrcpy's NotifAduitor`

**Comment by Thyrador** [comment]
Oh, I see. Doesn't seem to work anyway. Got a white square in my system tray but no notification is popping up.

**Comment by srevinsaju** [comment]
Ok, then I guess, I should better remove it; It works somewhat on some systems; not stable across desktop managers and OSes. Thanks for your test

**Comment by Thyrador** [comment]
You're welcome. In this regard **KDE Connect** is definitely more reliable.
