### ISSUE TITLE
venv/bin/python3 should rely on system python3 instead of a built one

### ISSUE THREAD

**Issue by pacho2** [srevinsaju/guiscrcpy#11]
Currently it seems a python3 binary is bundled in venv/bin/python3 instead of using system /usr/bin/python3, that would be preferable 

Thanks a lot

**Comment by srevinsaju** [comment]
I didn't get you. Could you please elaborate the problem. I don't use venv,
so yeah..

**Comment by pacho2** [comment]
Sorry

I was referring that, when reviewing the files in the tarball, I noticed that the file venv/bin/python3 looks to be a precompiled python3 version coming from... I guess your system. It even looks to rely on glibc-2.29 and, by default, it won't run if I don't give it a executable permission.

I was trying to see if I could package this on Gentoo getting inspired on Arch Linux package:
https://aur.archlinux.org/packages/guiscrcpy/

that one simply copies everything to a directory and adds a script to run the program from there (that is neither really optimal as it seems python files, documentation files... are all put together in the same location). 

Then, I noticed that, apart of that smaller issue, a python executable was getting installed and I was wondering if it would be possible to simply use system python3 instead of that executable.

**Comment by srevinsaju** [comment]
A question of concern, are you yochananmarqos who started packaging guiscrcpy for AUR?

I have created an installation script in the build guiscrcpy-installer.sh for adding desktop launcher as well. Use the original script for adding desktop launcher and adding it to path

**Comment by pacho2** [comment]
No, I am a Gentoo dev , but I don't find that installer

**Comment by srevinsaju** [comment]
Ok sorry about that. I am not the maintainer of the AUR repository. The AUR is built by yochananmarqos, athird party packager. You might need to raise an issue on pkgbuild website. Why don't you try my source code and my compiled binaries (official) from the release page or try guiscrcpy nightly (https://github.com/srevinsaju/github-nightly)

**Comment by pacho2** [comment]
Because in Gentoo we try to build from sources doing and ebuild that allows our users to compile and install software using "emerge". Then, I was trying to create an ebuild based on the sources found at
https://github.com/srevinsaju/guiscrcpy/releases

**Comment by srevinsaju** [comment]
Ok, I read through ebuild system of gentoo. Can you please share your terminal output while running the binary from GitHub guiscrcpy releases or the nightly release?

**Comment by pacho2** [comment]
Do you refer to __main__.py? That runs nice. I only wonder about what is using the python3 from venv/bin/python3 and if we could simply not install it. 

This is caused because, as this has no build system, it's not quite clear what files should we install or not. Also, it seems we need to keep all files together (instead of, for example, installing python files into /usr/lib/python3.6... and data files in /usr/share for example). That is the reason ArchLinux packager is simply putting all stuff under /opt instead of trying to use more standard FHS locations and don't install precompiled binaries like that python3 copy

**Comment by srevinsaju** [comment]
You can use venv to create separate virtual environment. There is particularly no need for using the guiscrcpy-binary package as python3 is faster. The only script needed to run it is: pip3 -r < requirements.txt and python3 __main__.py

**Comment by srevinsaju** [comment]
Did you mean a build system for python? Like meson?

**Comment by pacho2** [comment]
Yes, like meson, but usually python packages use distutils (I am not sure why as I am not a python guy :/)
https://docs.python.org/3/library/distutils.html

**Comment by srevinsaju** [comment]
@pacho2 , I did a lot of extensive testing on using distutils for python or creating a python package, but it doesn't work out as it has internal UI imports which are different from package dependencies. As an alternative, I have recently committed a bash script fiile which will automatically do the building for you. As nothing is there I can do for python build system, I am closing this issue. Apologize, i couldn't help you out

**Comment by pacho2** [comment]
No problem, thanks a lot

**Comment by srevinsaju** [comment]
@pacho2, I have added a python pip based build system for all OSes. It might help you to create the Ebuild. Installing guiscry is easy as pie now, run python3 -m pip install guiscrcpy

**Comment by pacho2** [comment]
OK, thanks

I will take a look about how to adapt it :)
