### ISSUE TITLE
udev adb error

### ISSUE THREAD

**Issue by probonopd** [srevinsaju/guiscrcpy#117]
GUI crashes when this is shown on the console:

> MSG: Please ensure you have enabled USB Debugging on your device. See README.md for more details

Interestingly, I think I do have USB debugging enabled on the device.

```
me@host:~$ Downloads/guiscrcpy-x86_64.AppImage 
                                  

guiscrcpy
by srevinsaju
3.7.post195.dev
Licensed under GNU GPL v3 (c) 2020  
                                  


MSG: Please ensure you have enabled USB Debugging on your device. See README.md for more details

(python3.8:31901): dbind-WARNING **: 10:21:56.701: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Traceback (most recent call last):
  File "/tmp/.mount_guiscrzbudZI/opt/python3.8/bin/guiscrcpy", line 9, in <module>
    sys.exit(bootstrap())
  File "/tmp/.mount_guiscrzbudZI/opt/python3.8/lib/python3.8/site-packages/guiscrcpy/launcher.py", line 1109, in bootstrap
    bootstrap0()
  File "/tmp/.mount_guiscrzbudZI/opt/python3.8/lib/python3.8/site-packages/guiscrcpy/launcher.py", line 1079, in bootstrap0
    guiscrcpy = InterfaceGuiscrcpy()
  File "/tmp/.mount_guiscrzbudZI/opt/python3.8/lib/python3.8/site-packages/guiscrcpy/launcher.py", line 337, in __init__
    self.refresh_devices()
  File "/tmp/.mount_guiscrzbudZI/opt/python3.8/lib/python3.8/site-packages/guiscrcpy/launcher.py", line 344, in refresh_devices
    self.scan_devices_update_list_view()
  File "/tmp/.mount_guiscrzbudZI/opt/python3.8/lib/python3.8/site-packages/guiscrcpy/launcher.py", line 625, in scan_devices_update_list_view
    devices = adb.devices_detailed(adb.path)
  File "/tmp/.mount_guiscrzbudZI/opt/python3.8/lib/python3.8/site-packages/guiscrcpy/lib/check.py", line 180, in devices_detailed
    'product': get(device, 2, ':').split(':')[1],
IndexError: list index out of range
```

**Comment by srevinsaju** [comment]
@probonopd Does  the appimage.github.io update automatically when the release is updated?

**Comment by srevinsaju** [comment]
@probonopd Can you please show me the output of 
```
adb devices -l
```

**Comment by srevinsaju** [comment]
@probonopd I have pushed a fix that prevents automatic releasing from other branches other than master; But I am still curious of what will be the output of `adb devices -l` on your system. I would be grateful to you if you provide of the output of them same, redacting any information, (if necessary)

**Comment by probonopd** [comment]
```
me@host:~$ adb devices -l
List of devices attached
adb server version (41) doesn't match this client (39); killing...
* daemon started successfully
XXXXXXXXXX             no permissions (user in plugdev group; are your udev rules wrong?); see [http://developer.android.com/tools/device.html] usb:9-2.3 transport_id:1
```

**Comment by srevinsaju** [comment]
Thanks; Seems like udev rules are not configured on your system; I will have to ask the user to configure the udev rules; but this happens rarely. I will add a fix for this; 

Thanks for reporting this; I had nearly forgotten about the same. I will update the documentation also accordingly

**Comment by probonopd** [comment]
Thank you very much. I'd be fine if there was a GUI dialog box telling me what to do, or even better asking me for permission to "just do it".

**Comment by srevinsaju** [comment]
Yes; I am implementing

**Comment by srevinsaju** [comment]
@probonopd I have added a fix. As I do not have a system with incorrect udev files; I could not test it; 

I hope this fix works. AppImage will be generated in the build artifacts section in the below link
https://github.com/srevinsaju/guiscrcpy/actions/runs/97493770

**Comment by probonopd** [comment]
Seems to have worked, altough I am not sure whether this in part has to do with the fact that I had installed `adb` from the distribution (and maybe udev rules along with it?) earlier today.

Is it normal that these palettes are in the middle of the screen?

![Screenshot](https://user-images.githubusercontent.com/2480569/81223749-0c476400-8fd6-11ea-9c24-3830282f5552.png)

**Comment by srevinsaju** [comment]
No, its not common, it rarely happens only on Chrome OS (chromium DE)
* Which Desktop Environment is yours?
* Is it possible to drag the toolkit and side panels using the dots?

**Comment by probonopd** [comment]
I am using Xubuntu 18.04, so XFCE.

**Comment by srevinsaju** [comment]
sure, I will test on Xubuntu. I have tested the dragging on Lubuntu, Kubuntu, Ubuntu, but unfortunately not Xubuntu. I will have to download the iso. (slow bandwidth)

**Comment by srevinsaju** [comment]
Ok @probonopd I have tested it on Xubuntu 

Version I have tested is 
v3.7.post115

I did not have any problems in moving the windows

I have confirmed it on Xubuntu XFCE 18.04 LTS

![guiscrcpy_xfce](https://user-images.githubusercontent.com/48695438/81422339-80f7db00-915b-11ea-9d3c-f585b86823c4.gif)

It is most likely that an update on your XFCE desktop environment that has probably caused the problem or might have been an outdated XFCE distribution. (I have seen in some of the forums stating that it was a bug in XFCE, and it later got fixed in a future release.)

For your reference, I have used exactly the same link https://github.com/srevinsaju/guiscrcpy/issues/117#issuecomment-625426111 to download the Xubuntu ISO

**Comment by srevinsaju** [comment]
@probonopd  If you are talking of the initial position of the side panels; it is not overriden by the code; it is the desktop manager's preference where to place the toolkits. For example KDE Plasma and i3 WM places it whereever there is a open space and not exactly at the centre of the screen .

**Comment by probonopd** [comment]
Thanks for checking out. Glad it is working, the position of those windows was just a minor nitpick. I think we can close this. Thanks :+1:
