### ISSUE TITLE
add support for usbaudio to forward audio from Android to pc

### ISSUE THREAD

**Issue by librewish** [srevinsaju/guiscrcpy#12]
https://github.com/rom1v/usbaudio

add an option in the gui to use this 
so that we can have audio from Android to pc.

**Comment by srevinsaju** [comment]
Good feature, will work on it!, But it will only work with Linux

**Comment by srevinsaju** [comment]
@librewish, with d112ac4ad9db02c47c7d97e6275708e32282d9b1 commit, the feature for usbaudio has been added
