### ISSUE TITLE
[BUG] Git tags not matching latest release tag

### ISSUE THREAD

**Issue by yochananmarqos** [srevinsaju/guiscrcpy#131]
**Describe the bug**
Generating the `pkgver` for [`guiscrpy-git`](https://aur.archlinux.org/packages/guiscrcpy-git) in the AUR does not match the latest release tag. Everything was working fine fetching the the most recent un-annotated tag before you started the continuous builds.

**To Reproduce**

Tags available using the most recent annotated tag reachable from the last commit:
```
git describe --long | sed 's/\([^-]*-\)g/r\1/;s/-/./g'
```
Produces:
```
3.7.r328.0bf2f9d
```

Tags available using the most recent un-annotated tag reachable from the last commit
```
git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
```
Produces:
```
continuous.r0.g0bf2f9d
```

Getting version from `setup.py` with latest commit SHA1:
```
printf "%s.g%s" "$(grep -oP "(?<=version=').*(?=')" setup.py)" "$(git rev-parse --short HEAD)"
```
Produces:
```
3.9.g0bf2f9d
```

**Expected behavior**
Right now it should look something like: `3.9.r0.gxxxxxxx`

**Comment by srevinsaju** [comment]
Somethings which I found out:
```bash
git describe --long --tags
```
gives
```
3.9-1-g0bf2f9d
```

```
git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
```
produces 
```
3.9.r1.g0bf2f9d
```
on my system

This is probably because `continuous` is the most recent tag on your system.

You may try this, and let me know if it works
```bash
git describe --long --tags --match "[0-9]*"
```

**Comment by srevinsaju** [comment]
I had forgotten to annotate the tag; I may not edit the tag, because it will trigger another release by `github-actions`.

**Comment by yochananmarqos** [comment]
Yes, that works (for now). Thanks!

```
git describe --long --tags --match "[0-9]*" | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
```
```
3.9.r7.g4d4f931
```

**Comment by srevinsaju** [comment]
@yochananmarqos Shall I close this issue?
