### ISSUE TITLE
guiscrcpy ~ mapper is not initialized v 3.9 [BUG]

### ISSUE THREAD

**Issue by eslamsidereel** [srevinsaju/guiscrcpy#133]
Hi, I followed your tutorial in issue #85 to try and initialize the mapper but nothing seams to happen. 
![01](https://user-images.githubusercontent.com/45595948/82156159-e9406e00-9879-11ea-9e36-b470a2233bb1.jpg)
![02](https://user-images.githubusercontent.com/45595948/82156161-ed6c8b80-9879-11ea-9c3d-3bb398a3db71.jpg)

My phone is Honor 8C
Windows 10 1909 64-bit
runing latest version of scrcpy (v1.13) and guiscrcpy (v3.9)

![03](https://user-images.githubusercontent.com/45595948/82156362-0aee2500-987b-11ea-9894-15b880d937e8.jpg)

How can I initialize the mapper?

**Comment by srevinsaju** [comment]
@eslamsidereel ,
Open a command prompt in the window where you downloaded the guiscrcpy exe, 
* how to open command prompt?

* On `file explorer` go to the guiscrcpy downloaded directory
* Press the file menu on the top left, and then, click open Power shell window here
* Then type 
```bash
.\guiscrcpy.exe --mapper
```

It should then work

**Comment by eslamsidereel** [comment]
Executing .\guiscrcpy.exe --mapper in CMD gives me an error "error: ambiguous option: --mapper could match --mapper-delay, --mapper-reset, --mapper-device-id"
![01](https://user-images.githubusercontent.com/45595948/82157677-468ced00-9883-11ea-90c8-fcc0cbd737ed.jpg)

**Comment by srevinsaju** [comment]
```bash
./guiscrcpy --mapper mapper-delay=1
```

Does this work?

**Comment by eslamsidereel** [comment]
Sadly that didn't work.
![01](https://user-images.githubusercontent.com/45595948/82157888-725ca280-9884-11ea-96b4-507924bac181.jpg)

**Comment by srevinsaju** [comment]
Ok, maybe this would,
```bash
./guiscrcpy --mapper --mapper-delay
```

--------------

Unfortunately, I donot have a windows device right now. I apologize for the error caused so

**Comment by eslamsidereel** [comment]
Still the same issue. "guiscrcpy: error: ambiguous option: --mapper could match --mapper-delay, --mapper-reset, --mapper-device-id".

Take your time to fix the issue I can wait.

**Comment by srevinsaju** [comment]
I have initiated a fix on #134. I will let you know when the server has created an exe which you can test

**Comment by srevinsaju** [comment]
@eslamsidereel Can you test this exe : 
https://github.com/srevinsaju/guiscrcpy/suites/690516409/artifacts/6505103

I guess it will be fixed; If it does, I will merge to master. Thanks for find a bug

**Comment by eslamsidereel** [comment]
The mapper now is initialized thanks for the fix, but i can't register any keys guiscrcpy hangs and the console gives me "E: 'Key' object has no attribute 'char'" over and over again.
![01](https://user-images.githubusercontent.com/45595948/82205890-931a0c00-9907-11ea-8da0-ba169d904070.jpg)

**Comment by srevinsaju** [comment]
@eslamsidereel Can you remove the `guiscrcpy.mapper.json` and then try again? 

Please follow the `docs` after removing the `guiscrcpy.mapper.json`

It lis likely to be in `C:/Users/Eslam/AppData/Local/guiscrcpy/guiscrcpy.mapper.json`

**Comment by eslamsidereel** [comment]
Unfortunately, there is no `guiscrcpy.mapper.json` in `C:/Users/Eslam/AppData/Local/guiscrcpy/`. The folder only contains `guiscrcpy.json`

**Comment by sosahoi** [comment]
hello, 
i'm having the same behavior described here, i can test the exe if you need further testing on this issue, (link above expired)

> https://github.com/srevinsaju/guiscrcpy/suites/690516409/artifacts/6505103

**Comment by srevinsaju** [comment]
@sosahoi you can find the new exe here https://github.com/srevinsaju/guiscrcpy/releases/tag/continuous

**Comment by srevinsaju** [comment]
@eslamsidereel Can you please run 
`guiscrcpy.exe --mapper` again to make it register the new keys;. Btw you need to keep your phone connected and test if you can use scrcpy, then close `guiscrcpy` and then run
```bash
guiscrcpy --mapper
```
It will open a new window then

**Comment by sosahoi** [comment]
Hi, 

from my side after testing the new EXE. 

same behavior described in here: 
> The mapper now is initialized thanks for the fix, but i can't register any keys guiscrcpy hangs and the console gives me "E: 'Key' object has no attribute 'char'" over and over again.
> ![01](https://user-images.githubusercontent.com/45595948/82205890-931a0c00-9907-11ea-8da0-ba169d904070.jpg)

and in here as well:
> Unfortunately, there is no `guiscrcpy.mapper.json` in `C:/Users/Eslam/AppData/Local/guiscrcpy/`. The folder only contains `guiscrcpy.json`
> I tried resetting the mapper, but it says `guiscrcpy mapper configuration is not created yet`
> ![00](https://user-images.githubusercontent.com/45595948/82208221-71bb1f00-990b-11ea-99db-364c1c898ff5.jpg)

and even after doing these steps:
> @eslamsidereel Can you please run
> `guiscrcpy.exe --mapper` again to make it register the new keys;. Btw you need to keep your phone connected and test if you can use scrcpy, then close `guiscrcpy` and then run
> 
> ```shell
> guiscrcpy --mapper
> ```
> 
> It will open a new window then

guiscrcpy turns unresponsive right after trying to init the mapper. 
as a note, no guiscrcpy.mapper.json file is being generated, o copied a template file just to check if it worked, but got the same results, so i deleted the guiscrcpy.mapper.json again.

**Comment by eslamsidereel** [comment]
Hi,
Sorry for the late reply I was super busy lately.
I tested the new guiscrcpy, but the same issue occurred:
`E: 'Key' object has no attribute 'char`
no new window opened and no `guiscrcpy.mapper.json` created in Appdata

**Comment by srevinsaju** [comment]
Ok, I will provide a fix in a while. Sorry for the delay from my side too. :smile:

**Comment by srevinsaju** [comment]
@eslamsidereel @sosahoi can you please tell me which key you tried to assign to mapping
Is it a visible ASCII character like `[A-Z], [a-z], [0-9]` or is it `Ctrl`, `Alt` or any other modifier?

**Comment by sosahoi** [comment]
On my side, I tried with the keys [A-Z], [a-z] and [0-9] without any CTRL or ALT modifier, no difference between them, as soon as I click the Mapper button, guiscrcpy gets unresponsive, you can check the attached video to check the the full procedure. 
[2020-06-01 22-15-26-146.zip](https://github.com/srevinsaju/guiscrcpy/files/4714913/2020-06-01.22-15-26-146.zip)

**Comment by ercanezin** [comment]
I have the same issue on MacOS too. It would really help if we could get a preconfigured keys example without need of opening an interface and select the location. Eg: [Config in Chinese](https://github.com/barry-ran/QtScrcpy/blob/master/docs/%E6%8C%89%E9%94%AE%E6%98%A0%E5%B0%84%E8%AF%B4%E6%98%8E.md) . And  [Example Pubg](https://github.com/barry-ran/QtScrcpy/blob/master/keymap/gameforpeace.json)

**Comment by eslamsidereel** [comment]
Same as @sosahoi tried [A-Z], [a-z] and [0-9], as soon as I click the Mapper button "E: 'Key' object has no attribute 'char'" keeps repeating and guiscrcpy gets unresponsive.

**Comment by srevinsaju** [comment]
Seen the video, @sosahoi is pressing the `ENTER` key. There is no need to press enter. When the key is pressed immediately, the action is executed. The part you missed is the configuration of keys when the mapper is resetted. See previous issues for a detailed approach on how to write configuration file

**Comment by eslamsidereel** [comment]
Those are the steps I have taken to try and get it working (I followed the steps in #85 ):
- connected my phone.
- ran `guiscrcpy.exe`.
- checked that my phone is in the list and USB debugging is running.
- pressed `start scrcpy`.
- closed guiscrcpy.
- ran `guiscrcpy --mapper` in a new CMD window.
From here `you should now see a window with your phone's screenshot` as mentioned in #85 not appearing.
Going to `AppData\Local\guiscrcpy`, no `scr` image and no mapping configuration only guiscrcpy config file.
Back in the CMD,
When pressing `ENTER` `Arrow keys` `CTRL` `ALT` this message keeps repeating `"E: 'Key' object has no attribute 'char'"`.
Not sure what I am doing wrong.

**Comment by sosahoi** [comment]
wondering if there's been any updates on this, thanks.

**Comment by srevinsaju** [comment]
@sosahoi would you like to test `4.0.a0` ?

**Comment by eslamsidereel** [comment]
I was wondering the same thing as @sosahoi , @srevinsaju  I would lie to test `4.0.a0`

**Comment by srevinsaju** [comment]
Great! I will create a binary exe for you both. Or is python source possible to install. Which distribution do you prefer (`exe` or `.whl`)

**Comment by sosahoi** [comment]
> Great! I will create a binary exe for you both. Or is python source possible to install. Which distribution do you prefer (`exe` or `.whl`)

i'll gladly test the EXE 4.0.a0

**Comment by eslamsidereel** [comment]
> Great! I will create a binary exe for you both. Or is python source possible to install. Which distribution do you prefer (`exe` or `.whl`)

Me too I will go with the EXE.

**Comment by srevinsaju** [comment]
@eslamsidereel @sosahoi Can you please test https://github.com/srevinsaju/guiscrcpy/suites/951784002/artifacts/11876079

Remove `C:/Users/<username>/AppData/Local/guiscrcpy` before running the app. then execute the mapper by

`./guiscrcpy.exe --mapper` to configure the mapper

**Comment by srevinsaju** [comment]
@eslamsidereel @sosahoi you might be interested in our discord chat (link on README)

**Comment by eslamsidereel** [comment]
Downloaded `4.0.a0` but once I initialize the mapper this appear `No conda env active, defaulting to base`
![{FF869B41-0A26-4373-B803-AF4699141614} png](https://user-images.githubusercontent.com/45595948/88421064-25e39500-cde8-11ea-832d-d0a36e0d4b02.jpg)

**Comment by srevinsaju** [comment]
You may ignore the `conda` message. Can you please show me the output og `adb devices` ?

**Comment by eslamsidereel** [comment]
Do you mean this 👇
![{F5878512-4895-4B96-AE4F-DF00FC84C3DA} png](https://user-images.githubusercontent.com/45595948/88421705-495b0f80-cde9-11ea-8ed3-df24a43c3853.jpg)
Sorry I don't know how to get the `output og adb devices`

**Comment by srevinsaju** [comment]
Yes, you see those `BBPBB...` in the green box? thats your device id. 
so run
```
guiscrcpy.exe --mapper --mapper-device-id BBPBB...
```

Let me know if you fall into some errors.

**Comment by eslamsidereel** [comment]
The mapper finally made a screenshot and I was able to register some key maps.

![{A52D5786-969D-4A42-BF0F-B881259DB3B0} png](https://user-images.githubusercontent.com/45595948/88422977-54af3a80-cdeb-11ea-9afd-6d6a1af2e3a3.jpg)

But when I press the `initialize mapper` button in `guiscrcpy` it says that mapper is not initialized like this 👇

![{DF027619-D4FA-4E63-8229-E78D63F2C131} png](https://user-images.githubusercontent.com/45595948/88423148-9fc94d80-cdeb-11ea-8a50-9fa6a661e312.jpg)

So I tried initializing it again from a CMD like this 👇 but the keys not working

![{D9B37A21-45FF-4180-99D3-4FB5E05FF0B2} png](https://user-images.githubusercontent.com/45595948/88423265-cc7d6500-cdeb-11ea-819c-0ff47e20101c.jpg)

After a while the same error appears again `E: 'Key' object has no attribute 'char'` 👇

![{B3CF85C7-31BD-4CD8-9405-5BAEF914768A} png](https://user-images.githubusercontent.com/45595948/88423361-f3d43200-cdeb-11ea-8c36-72d5bd0ea401.jpg)

**Comment by srevinsaju** [comment]
You may ignore the E: `key` errors, those come because you press enter. you may ignore those. Were you able to trigger key mapping ?

**Comment by eslamsidereel** [comment]
Unfortunately no all the registered keys wont trigger.

**Comment by srevinsaju** [comment]
Can you sen me `guiscrcpy.mapper.json` ?

**Comment by srevinsaju** [comment]
Which are those keys which won't trigger?

**Comment by eslamsidereel** [comment]
Yes, `guiscrcpy.mapper.json` was created in AppData after registration two keys `{"b": [573.0177514792899, 1404.6612466124661], "n": [692.3076923076924, 1433.4959349593496]}` , but both of them wont trigger.

**Comment by srevinsaju** [comment]
Hmm, thats odd: Could you join our discord chat : https://discord.gg/TpJvDX 
Did you start the mapper by clicking on the mapper button on guiscrcpy?

**Comment by eslamsidereel** [comment]
I joined the discord chat thanks 😊
I tried starting the mapper by clicking on the mapper button on guiscrcpy but a windows appears saying that the mapper is not initialized.

**Comment by srevinsaju** [comment]
Ok, Let me check that too. Thanks for testing

**Comment by eslamsidereel** [comment]
You are welcome 😊
I tried resetting the mapper and restringing different keys. Everything works perfect at the begining but then all the keys wont trigger.

**Comment by srevinsaju** [comment]
I will push a commit and send a fixed exe in a while.

**Comment by srevinsaju** [comment]
@eslamsidereel fixed it; EXE:  https://github.com/srevinsaju/guiscrcpy/suites/961690952/artifacts/12101889

**Comment by eslamsidereel** [comment]
It works now great 👍 Although clicking on the mapper button on guiscrcpy brings a windows saying that the mapper is not initialized, initializing it from a CMD solves the issue.
Just one last problem. It seems that there is a delay before triggering the keys.
I will continue testing the mapper.
Thanks for the fix 😄

**Comment by srevinsaju** [comment]
Great. I have some more things on the main GUI to do. I hope the mapper functionality is fixed

**Comment by eslamsidereel** [comment]
The mapper now is fully functional. Great work. 👍
There is only a little delay before triggering the keys.

**Comment by srevinsaju** [comment]
Mapper got a new CLI interface, and mapper can now be run through GUI. with the latest release.
Assuming the issue was fixed, I am closing this issue. Please feel free to reopen this issue or create another issue.

Thanks to all who helped test guiscrcpy and make it great so far!! :tada:
