### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by KaKi87** [srevinsaju/guiscrcpy#14]
Please add support for HiDPI (UHD 15" screen in my case), thanks !

**Comment by srevinsaju** [comment]
Is it regarding the mobile screen, or the GUI panels?

**Comment by KaKi87** [comment]
The GUI, of course. `scrcpy` is working fine.

**Comment by srevinsaju** [comment]
Is the GUI appearing small in siz? Can you share me a screen shot?

**Comment by srevinsaju** [comment]
As no response was taken on this issue, I assume it is fixed with v2.0
