### ISSUE TITLE
guiscrcpy won't connect to phone

### ISSUE THREAD

**Issue by xbfrog** [srevinsaju/guiscrcpy#142]
I am using Ubuntu 20.04 fully updated and Samsung s10 phone also updated.  Guiscrcpy 3.9.2 just updated today from 3.9.0.  I installed Guiscrcpy from snaps. Enabled permissions in the app and enabled developer mode in Samsung. It worked for a few days. This morning turning it on brought up the Gui but no tools or directional pad. The gui said can not find any devices. Ubuntu see the phone and can transfer files no issues. I tried restarting the gui with no change. The progress bar each time stops at 5%. Checked debugging, on, checked permissions, on. So I uninstalled guiscrcpy and reinstalled, no change. rebooted Ubuntu, no change. Rebooted phone, no change. Tried to start it a couple more times and then the gui with tools appeared with directional pad. The progress bar now says 100%. And the message in the center of the screen says checking device connection. Still no phone screen. So I tried another cell phone Droid Maxx, turned on developer mode, same issue, can not find device. But again Ubuntu sees it. At this time I reconnected the samsung, gui comes up with tools and directional pad but no phone screen. Each time the gui progress bar goes to 100% twhen it seems to get farther while the white banner in the middle of the gui says checking device connection.  I'm stuck as how to proceed.

**Comment by srevinsaju** [comment]
@xbfrog Can you connect your device to the PC and then run this in the terminal
```bash
guiscrcpy.adb devices -l
```
Even if ubuntu detects it, for adb (the tool used to connect to mobile and send commands to the device) might not have detected it. Thats why you are getting error

**Comment by xbfrog** [comment]
i ran guiscrcpy.adb devices -l the result was: List of devices attached
RF8M64D8N0J            device usb:2-3 product:beyond1qlteue model:SM_G973U1 device:beyond1q transport_id:3

dj@greenfrog:~$ List of devices attached

Command 'List' not found, did you mean:

  command 'mist' from snap mist (master)
  command 'gist' from deb yorick (2.2.04+dfsg1-10)
  command 'dist' from deb mmh (0.4-2)
  command 'dist' from deb nmh (1.7.1-6)
  command 'hist' from deb loki (2.4.7.4-10)

See 'snap info <snapname>' for additional versions.

dj@greenfrog:~$ RF8M64D8N0J            device usb:2-3 product:beyond1qlteue model:SM_G973U1 device:beyond1q transport_id:3

**Comment by srevinsaju** [comment]
@xbfrog can you now try running 
```
export GUISCRCPY_DEBUG=True
guiscrcpy
```

and then send me the output, also please check if your device is getting detected now

**Comment by xbfrog** [comment]
guiscrcpy
Scanning /snap/guiscrcpy/192/bin/guiscrcpy
Complete args ['/snap/guiscrcpy/192/bin/guiscrcpy', '/snap/guiscrcpy/192/usr/bin/python3', '/snap/guiscrcpy/192/bin/guiscrcpy']
Received []
Parsed Namespace(connect='', debug=3, disable_swipe=False, force_window_frame=False, install=False, killserver=False, mapper=False, mapper_delay=False, mapper_device_id='', mapper_reset=False, noscrcpy=False, output=False, panels_not_always_on_top=False, reset=False, start=False, start_scrcpy_device_id='', theme='Breeze', version=False)
                                  

guiscrcpy
by srevinsaju
3.9.2
Licensed under GNU GPL v3 (c) 2020  
                                  


MSG: Please ensure you have enabled USB Debugging on your device. See README.md for more details
[{'identifier': 'RF8M64D8N0J', 'status': 'device', 'product': '2-3', 'model': 'beyond1qlteue', 'device': 'SM_G973U1', 'transport_id': 'beyond1q'}]
pairfilter: 3
Pairing status: True
[{'identifier': 'RF8M64D8N0J', 'status': 'device', 'product': '2-3', 'model': 'beyond1qlteue', 'device': 'SM_G973U1', 'transport_id': 'beyond1q'}]
pairfilter: 1
Pairing status: True
DEVICE LIST 1 [{'identifier': 'RF8M64D8N0J', 'status': 'device', 'product': '2-3', 'model': 'beyond1qlteue', 'device': 'SM_G973U1', 'transport_id': 'beyond1q'}]
scrcpy launched in 0.31s

GUI still says checking device connection

**Comment by srevinsaju** [comment]
@xbfrog, Seems like its only a problem with the message. Please see 
```bash
guiscrcpy.scrcpy
```
And please let me know of the output of the same

Please ignore the message, (I forgot to put a CONNECTION COMPLETED Message in that box and thats why you have confusion. I am sorry about that)

Are you able to see a window of your mobile ? Thanks for your testing

**Comment by xbfrog** [comment]
guiscrcpy.scrcpy
INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
/snap/guiscrcpy/192/usr/... (27694 bytes in 0.009s)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: The server version (1.13) does not match the client (1.14)
	at com.genymobile.scrcpy.Server.createOptions(Server.java:78)
	at com.genymobile.scrcpy.Server.main(Server.java:176)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:339)

**Comment by xbfrog** [comment]
no, i do not get phone screen

**Comment by srevinsaju** [comment]
@xbfrog How did you get `scrcpy v1.14` ?
Have you installed scrcpy before in any other way?
Please provide me the output of 
```bash
which scrcpy
ls /usr/local/share/scrcpy
echo next
ls /usr/share/scrcpy
```

**Comment by xbfrog** [comment]
as you mentioned it now, i did try to install scrcpy via terminal before i found it in snaps. terminal install was unsuccessful.
which scrcpy
/snap/bin/scrcpy
dj@greenfrog:~$ ls /usr/local/share/scrcpy
ls: cannot access '/usr/local/share/scrcpy': No such file or directory
dj@greenfrog:~$ echo next
next
dj@greenfrog:~$ echo next ls /usr/share/scrcpy
next ls /usr/share/scrcpy

**Comment by srevinsaju** [comment]
thank you; Its because you installed `scrcpy` from another source; Hence `guiscrcpy` is conficting with your installed scrcpy.
You can uninstall `scrcpy` by 
```bash
sudo snap remove scrcpy
```
And it will then solve your problem

Its not a bug with `guiscrcpy`. You can still use `scrcpy` by
```bash
guiscrcpy.scrcpy
```

Remove all installation of SCRCPY or use the AppImage of `guiscrcpy` as an alternative

**Comment by srevinsaju** [comment]
Can you also execute 
```bash
ls /usr/share/scrcpy
```
Which distro are you running @xbfrog

**Comment by xbfrog** [comment]
Thank you for finding the issue. I"m glad its not a bug, I would have never found it on my own. Guiscrcpy is the best app for its kind out there across any platform. You are doing a great job. I look to seeing more great features

**Comment by xbfrog** [comment]
i'm running Ubuntu 20.04

**Comment by srevinsaju** [comment]
Great! Alternatively, if you do not want to uninstall scrcpy, you can try out the AppImage from the [releases](https://github.com/srevinsaju/guiscrcpy/releases/tag/3.9.3) which will work without configuration;

Thank you
