### ISSUE TITLE
Starting Guiscrcpy

### ISSUE THREAD

**Issue by xbfrog** [srevinsaju/guiscrcpy#145]
I followed your last instructions with no success the app starts either with terminal or gui, but no tools no phone screen. Since then i have uninstalled snap, reinstalled snap, no change. uninstalled/purged from terminal, verified no packages of either scrcpy or guiscrcpy remained, reinstalled from snap. No change. I get the desktop gui only, no tools no phone screen. Please tell me what i'm missing.

**Comment by srevinsaju** [comment]
@xbfrog Please try AppImage, seems like you have broken something while you installed `scrcpy` snap.

**Comment by xbfrog** [comment]
You can close this I am using guiscrpy appimage even on a second computer with a fresh install. guiscrcpy installed from snap would not work there either. Clicking start server would only progress 5% then stop. So i guess i'll have to be happy with appimage thanks for your help
