### ISSUE TITLE
[FR] Map swipe jestures to keyboard shortcuts

### ISSUE THREAD

**Issue by saildata** [srevinsaju/guiscrcpy#147]
**Is your feature request related to a problem? Please describe.**
It would be helpful with Android 10 gestures to be able to map something like `right arrow` and `left arrow` on my keyboard to swipe left and right between apps. Example: [here in example 9](https://www.computerworld.com/article/3439060/android-10-gestures.html).

**Describe the solution you'd like**
A way to map the swipe gesture to a keyboard key. The swipe panel (`guiscrcpy.ux.swipe.SwipeUX`) works right now! I would like to add a keyboard shortcut that maps to the swipe panel.

**Describe alternatives you've considered**
Third party tools and digging around the mapper utility already in the code. If the [touch key mapper](https://github.com/srevinsaju/guiscrcpy/blob/f16575a2ce716edcb6271f57f2eaf0341b65c08f/docs/FEATURES.md#touch---key-mapper) is the solution here, can someone tell me how to map to the swipe panel?

**Comment by saildata** [comment]
> @saildata what would be your preferred shortcut for swipe? you get to decide; for your feature request tada

Sorry, I didn't see the response until now : ) Are you asking what keyboard key(s) to use? If so, then user defined / default to arrow keys I would think makes sense.

**Comment by srevinsaju** [comment]
@saildata great, scrcpy has a pinch option too. I will implement that along with swipes in a nearby release
