### ISSUE TITLE
[FR] sndscrcpy support for guiscrcpy 

### ISSUE THREAD

**Issue by Da-Viper** [srevinsaju/guiscrcpy#148]
usbaudio is deprecated for android 10 and above the author of both scrcpy and [usbaudio ](https://github.com/rom1v/usbaudio/blob/master/README.md) created [sndcpy](https://github.com/rom1v/sndcpy) for android 10 and above 

is it possible to add support for it in gui-scrcpy? 

thanks

**Comment by srevinsaju** [comment]
@Da-Viper Thanks. I did not know @rom1v released sndscrcpy. Thanks for letting me know. I will add the support for guscrcpy in v4

**Comment by srevinsaju** [comment]
Fixed in #201 :tada:
