### ISSUE TITLE
[BUG] Config files aren't being used in GUI

### ISSUE THREAD

**Issue by Raymo111** [srevinsaju/guiscrcpy#149]
**Describe the bug**
Every time I open the GUI it defaults to the default options, ignoring the config file.
**To Reproduce**
1. Verify that the config file contains stuff
2. Launch guiscrcpy
3. Tickbox options are back to default

**Expected behavior**
Tickboxes are initialized not from default but from config file.

**Desktop (please complete the following information):**
`uname -a`: `Linux ARCHANGEL 5.7.2-arch1-1 #1 SMP PREEMPT Wed, 10 Jun 2020 20:36:24 +0000 x86_64 GNU/Linux`

**Additional context**
`guiscrcpy -v`:
```
                                  

guiscrcpy
by srevinsaju
3.9.3
Licensed under GNU GPL v3 (c) 2020  
                                  


MSG: Please ensure you have enabled USB Debugging on your device. See README.md for more details

== PyQt5 Version ==
PYQT_VERSION = 331520
PYQT_VERSION_STR = 5.15.0
QOpenGLVersionProfile = <class 'PyQt5.QtGui.QOpenGLVersionProfile'>
QOperatingSystemVersion = <class 'PyQt5.QtCore.QOperatingSystemVersion'>
QT_VERSION = 331520
QT_VERSION_STR = 5.15.0
QVersionNumber = <class 'PyQt5.QtCore.QVersionNumber'>

== CairoSVG version ==
CairoSVG == 2.4.2

```

**Comment by srevinsaju** [comment]
@Raymo111 how did you install guiscrcpy : `snap`, `pip`, `AppImage` ?

**Comment by Raymo111** [comment]
@srevinsaju I installed it from the [AUR](https://aur.archlinux.org/packages/guiscrcpy/).

**Comment by srevinsaju** [comment]
@Raymo111 Do you have
* `~/.config` folder
* What is the output of `echo $XDG_CONFIG_HOME` ?
* Is there no files in `~/.config/guiscrcpy/` ?

xdg is a freedesktop specification for apps. Apps use the data provided by XDG to save the configuration files. I assume you installed Arch from scratch; I had the same feeling, because some important parts of the installation are not done manually or are not mentioned in the Arch Installation Wiki, making some programs work oddly. I used Arch for two months, but for production systems,  I could not verify the results with others. Manjaro Linux solved my problem. 

On KDE Plasma, there are options to set the XDG_CONFIG_HOME. You can check those there too. It depends on the applets installed on the KDE system. I am not sure of GNOME or other desktop environments 

Some more information, directly from [Arch Wiki](https://wiki.archlinux.org/index.php/XDG_Base_Directory)

**Comment by Raymo111** [comment]
@srevinsaju ~/.config/guiscrcpy contains the config file, and since I'm on KDE, `$XDG_CONFIG_HOME` is set to ~/.config

**Comment by srevinsaju** [comment]
@Raymo111  Thats odd, I wonder which checkboxes did check?

**Comment by Raymo111** [comment]
@srevinsaju so after doing that (reset settings, restart, uncheck bottom and swipe panels, lock rotation to landscape, and changing bitrate to 10000KB/s), start, exit, restart, the checkbox configs I did show up in ~/.config/guiscrcpy/guiscrcpy.json, but are reset in gui. The most interesting thing is 10000 shows in the config, but the gui now shows 1000 KB/s.

**Comment by srevinsaju** [comment]
its possible that
* its a bug in guiscrcpy
* the window is not big enough to show the extra zero
* the max size in KB/s is 9999 KB/s
* To use a higher value, use a multiplier instead, for example 10000 KB/s is approximately 10 MB/s

**Comment by Raymo111** [comment]
@srevinsaju window is big enough, and I tried MB/s but it doesn't seem to work either. What about the checkboxes? Is this just an issue for me or do you have a similar thing?

**Comment by srevinsaju** [comment]
I am not sure; the last time I worked on this was over a month ago. And `guiscrcpy` is not my main project, so I do not keep a track over it. Do you know how to read python code?

**Comment by Raymo111** [comment]
@srevinsaju Ahh I see, no worries. I'm not much of a Python guy. I guess I don't mind manually reconfiguring it each time, it's not like I use it every day.

**Comment by srevinsaju** [comment]
I will consider this bug before the release of v4.0, and I will also add confuration for each of checkboxes. I did not add them because options like Record screen might not be used Frequently by a user. Thanks for reporting the bug.

**Comment by Raymo111** [comment]
Great!

**Comment by SamLukeYes** [comment]
I'm using Manjaro GNOME (unstable branch). Tried `guiscrcpy` and `guiscrcpy-git` from AUR, and `guiscrcpy` from PyPI. The same issue with all of them.

**Comment by srevinsaju** [comment]
Yes. Its a known bug. Its not yet fixed. Not all options are saved to the configuration. Only some of them.

**Comment by srevinsaju** [comment]
I am adding `hacktoberfest` tag to this issue, for someone interested this October!!
