### ISSUE TITLE
打包一个.deb包

### ISSUE THREAD

**Issue by liyepan** [srevinsaju/guiscrcpy#15]
希望楼主可以打包一个deb的包,这样我就可以把guiscrcpu上传到软件源里面,我们是Linux人社区,新的发行版即将发布.

**Comment by srevinsaju** [comment]
@liyepan, i will try to release a Deb package as soon as possible. 

PS: please make future issues in English

**Comment by srevinsaju** [comment]
@liyepan, I am not planning to release Deb package. Creating a Deb package will inhibit a lot of libraries. It is better to use pip
