### ISSUE TITLE
How do you get the Key Mapper on MacOS to work? 

### ISSUE THREAD

**Issue by Abeelme** [srevinsaju/guiscrcpy#150]
```
MacBook-Pro-de-pc:~ pc$ guiscrcpy adb-interface devices
ERROR:root:MacOS is untested. guiscrcpy is trying to use Linux config on Mac
ERROR:root:MacOS is untested. guiscrcpy is trying to use Linux config on Mac
ERROR:root:MacOS is untested. guiscrcpy is trying to use Linux config on Mac
ERROR:root:MacOS is untested. guiscrcpy is trying to use Linux config on Mac
ERROR:root:MacOS is untested. guiscrcpy is trying to use Linux config on Mac
ERROR:root:MacOS is untested. guiscrcpy is trying to use Linux config on Mac
List of devices attached
49byfqfiscs8dq6h	device
192.168.1.9:5555	device



MacBook-Pro-de-pc:~ pc$ guiscrcpy --mapper
ERROR:root:MacOS is untested. guiscrcpy is trying to use Linux config on Mac
ERROR:root:MacOS is untested. guiscrcpy is trying to use Linux config on Mac
ERROR:root:MacOS is untested. guiscrcpy is trying to use Linux config on Mac
ERROR:root:MacOS is untested. guiscrcpy is trying to use Linux config on Mac
ERROR:root:MacOS is untested. guiscrcpy is trying to use Linux config on Mac
ERROR:root:MacOS is untested. guiscrcpy is trying to use Linux config on Mac
                                  

guiscrcpy
by srevinsaju
3.9.3
Licensed under GNU GPL v3 (c) 2020  
                                  


MSG: Please ensure you have enabled USB Debugging on your device. See README.md for more details
ERROR:root:MacOS is untested. guiscrcpy is trying to use Linux config on Mac
+++++++++++++++++++++++++++++++++++++++
guiscrcpy ~ mapper by srevinsaju
=======================================
Make sure that your device is turned on, and connected to your PC
With USB debugging turned on.
+++++++++++++++++++++++++++++++++++++++
Waiting for device
Device : OK!
E: Command 'adb shell wm size' exited with 1
Initializing guiscrcpy mapper v3.5-
LOG: Key:Pos JSON Configuration filename found in  /Users/pc/.config/guiscrcpy/  directory
KEY:A {'key': [], 'pos': []}
[SERVER] LISTENING VALUES: Your keys are being listened by server. 
{'key': [], 'pos': []}
```

**Comment by srevinsaju** [comment]
@Abeelme please remove '/Users/pc/.config/guiscrcpy/` directory and try again?

**Comment by Abeelme** [comment]
> @Abeelme please remove `/Users/pc/.config/guiscrcpy/` directory and try again?

Thank you so much 
My problem is the screenshot window won't open !


MacBook-Pro-de-pc:~ pc$ guiscrcpy --mapper
ERROR:root:MacOS is untested. guiscrcpy is trying to use Linux config on Mac
ERROR:root:MacOS is untested. guiscrcpy is trying to use Linux config on Mac
ERROR:root:MacOS is untested. guiscrcpy is trying to use Linux config on Mac
ERROR:root:MacOS is untested. guiscrcpy is trying to use Linux config on Mac
ERROR:root:MacOS is untested. guiscrcpy is trying to use Linux config on Mac
ERROR:root:MacOS is untested. guiscrcpy is trying to use Linux config on Mac
                                  

guiscrcpy
by srevinsaju
3.9.3
Licensed under GNU GPL v3 (c) 2020  
                                  


MSG: Please ensure you have enabled USB Debugging on your device. See README.md for more details
ERROR:root:MacOS is untested. guiscrcpy is trying to use Linux config on Mac
+++++++++++++++++++++++++++++++++++++++
guiscrcpy ~ mapper by srevinsaju
=======================================
Make sure that your device is turned on, and connected to your PC
With USB debugging turned on.
+++++++++++++++++++++++++++++++++++++++
Waiting for device
Device : OK!
Initializing guiscrcpy mapper v3.5-
LOG: Initializing guiscrcpy.mapper() for first time use...
LOG: Key:Pos JSON Configuration filename created in  /Users/pc/.config/guiscrcpy/  directory
/sdcard/scr.png: 1 file pulled, 0 skipped. 31.3 MB/s (1540458 bytes in 0.047s)


Lets Check

**Comment by srevinsaju** [comment]
Okay, seems like its not working on MacOS. Which macOS are you using? Is it 10.15 Catalina?

**Comment by Abeelme** [comment]
MacOs Mojave 10.14.4

**Comment by srevinsaju** [comment]
@Abeelme  can you try out 4.0 if it works on Mac now?

**Comment by srevinsaju** [comment]
Awaiting response, closing this as we did not receive any response. Feel free to open another issue, or reopen this issue. Thanks

**Comment by ilplaymo** [comment]
i'm on Big Sur 11.5.2 and 4.10.0 but the error messages still appears:

playmo@HackOS ~ % guiscrcpy
ERROR:root:MacOS is untested. guiscrcpy is trying to use Linux config on Mac
ERROR:root:MacOS is untested. guiscrcpy is trying to use Linux config on Mac
ERROR:root:MacOS is untested. guiscrcpy is trying to use Linux config on Mac

guiscrcpy v4.10.0
by @srevinsaju
https://github.com/srevinsaju/guiscrcpy


ERROR:root:MacOS is untested. guiscrcpy is trying to use Linux config on Mac
ERROR:root:MacOS is untested. guiscrcpy is trying to use Linux config on Mac
ERROR:root:MacOS is untested. guiscrcpy is trying to use Linux config on Mac
qt.qpa.fonts: Populating font family aliases took 569 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost. 

after this the app start and works very well
is there a way to fix and remove this messages?
thanks

**Comment by srevinsaju** [comment]
Yes, it is possible to remove the messages, but can you confirm if the app works ok? because, I don't own a macOS device to test it, and the macOS compatibility layer for guiscrcpy was added just by guessing...
