### ISSUE TITLE
[BUG] Failed to execute command "guiscrcpy"

### ISSUE THREAD

**Issue by Chachaandini** [srevinsaju/guiscrcpy#153]
I installed with pip3

`Failed to execute child process command "guiscrcpy"(no such file or direcctory)`

any help?

**Comment by srevinsaju** [comment]
```
python3 -m guiscrcpy
```

**Comment by Chachaandini** [comment]
> ```
> python3 -m guiscrcpy
> ```

Work Thanks... :)

but i didnt know how to setting keymapping

**Comment by Chachaandini** [comment]
![scr](https://user-images.githubusercontent.com/20607931/88065660-14f01500-cb97-11ea-8e7f-c9bb1cfe63ad.png)


all button its normal can use, but not for that button
It try with this 
`python3 -m guiscrcpy`
and close guiscrcpy, and use this command on terminal
`python3 -m guiscrcpy --mapper`

                                  

guiscrcpy
by srevinsaju
3.9.3
Licensed under GNU GPL v3 (c) 2020  
                                  


MSG: Please ensure you have enabled USB Debugging on your device. See README.md for more details
+++++++++++++++++++++++++++++++++++++++
guiscrcpy ~ mapper by srevinsaju
=======================================
Make sure that your device is turned on, and connected to your PC
With USB debugging turned on.
+++++++++++++++++++++++++++++++++++++++
Waiting for device
Device : OK!
Initializing guiscrcpy mapper v3.5-
LOG: Initializing guiscrcpy.mapper() for first time use...
LOG: Key:Pos JSON Configuration filename created in  /home/svlad/.config/guiscrcpy/  directory
LOG: Detected a Linux Operating System ::  5.6.0-kali2-amd64 #1 SMP Debian 5.6.14-2kali1 (2020-06-10)

(python3:52795): Gtk-WARNING **: 21:08:11.328: Theme parsing error: gtk.css:2794:15: Not using units is deprecated. Assuming 'px'.
[  2%] /sdcard/scr.png
[  5%] /sdcard/scr.png
[  8%] /sdcard/scr.png
[ 10%] /sdcard/scr.png
[ 13%] /sdcard/scr.png
[ 16%] /sdcard/scr.png
[ 19%] /sdcard/scr.png
[ 21%] /sdcard/scr.png
[ 24%] /sdcard/scr.png
[ 27%] /sdcard/scr.png
[ 30%] /sdcard/scr.png
[ 32%] /sdcard/scr.png
[ 35%] /sdcard/scr.png
[ 38%] /sdcard/scr.png
[ 40%] /sdcard/scr.png
[ 43%] /sdcard/scr.png
[ 46%] /sdcard/scr.png
[ 49%] /sdcard/scr.png
[ 51%] /sdcard/scr.png
[ 54%] /sdcard/scr.png
[ 57%] /sdcard/scr.png
[ 60%] /sdcard/scr.png
[ 62%] /sdcard/scr.png
[ 65%] /sdcard/scr.png
[ 68%] /sdcard/scr.png
[ 71%] /sdcard/scr.png
[ 73%] /sdcard/scr.png
[ 76%] /sdcard/scr.png
[ 79%] /sdcard/scr.png
[ 81%] /sdcard/scr.png
[ 84%] /sdcard/scr.png
[ 87%] /sdcard/scr.png
[ 90%] /sdcard/scr.png
[ 92%] /sdcard/scr.png
[ 95%] /sdcard/scr.png
[ 98%] /sdcard/scr.png
[100%] /sdcard/scr.png
/sdcard/scr.png: 1 file pulled. 33.5 MB/s (2397387 bytes in 0.068s)


Lets Check

What should i do next?

**Comment by srevinsaju** [comment]
@Chachaandini the mapper has some bugs. You may like to wait until `4.0.a0` is released. See #133

**Comment by Omi231** [comment]
> ```
> python3 -m guiscrcpy
> ```

Getting this error: 

![image](https://user-images.githubusercontent.com/44071105/88331716-da2cdf00-cd46-11ea-8f09-4e0cb6c1ca55.png)

**Comment by srevinsaju** [comment]
@Omi231 Please do 
```bash
pip3 install guiscrcpy
python3 -m guiscrcpy
```

**Comment by Omi231** [comment]
Already did that. Not working! :(

**Comment by srevinsaju** [comment]
@Omi231 show me the output of 
```bash
pip3 list 
```

**Comment by srevinsaju** [comment]
@Omi231 you may like to join our Discord chat?

**Comment by Omi231** [comment]
I downloaded the source code and build solved the issue. Thanks

**Comment by Chachaandini** [comment]
> @Omi231 you may like to join our Discord chat?

cant i join? i want ask

**Comment by srevinsaju** [comment]
Anyone can join :smile:

**Comment by Chachaandini** [comment]
@srevinsaju link?

**Comment by srevinsaju** [comment]
Link on the README, there is a badge with discord icon, just click that!

**Comment by Chachaandini** [comment]
> Link on the README, there is a badge with discord icon, just click that!

i didn't see that...
`https://camo.githubusercontent.com/64777c9a55daa815b421db747a75a7d83c0eb0d4/68747470733a2f2f696d672e736869656c64732e696f2f646973636f72642f3637393734363637303432323236313738333f6c6162656c3d636861742532306f6e253230446973636f7264266c6f676f3d646973636f7264266c6f676f436f6c6f723d7768697465267374796c653d666c61742d737175617265`

**Comment by srevinsaju** [comment]
https://discord.gg/TGfMf3G
