### ISSUE TITLE
[BUG]Phone screen does not display but the key-mapping woks perfectly.

### ISSUE THREAD

**Issue by Lycan-Xx** [srevinsaju/guiscrcpy#156]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
* [ ] Windows
- **Architecture**: Example: 32-bit / 64-bit
- **Version**: Example: 10, 8.1, 7

* [ ] Linux
 - Please paste your `neofetch` here. (What is a [neofetch](https://github.com/dylanaraps/neofetch))
A `neofetch` is always available in your package repositories. 

- > If you do not want to install neofetch; Please provide the name of your desktop environment, distro and architecture

* [ ] MacOS
 - **Version**: Example Catalina 10.15

**Additional context**

**Comment by srevinsaju** [comment]
@Lycan-Xx Please provide more information

**Comment by Lycan-Xx** [comment]
I installed the app from the ubuntu app store, It works perfectly but my
phone screen does not appear, i'am able to control the phone using the
navigation tabs that appear.

**Comment by srevinsaju** [comment]
@Lycan-Xx thanks, can you try out the AppImage of guiscrcpy (not from Ubuntu app store), it's right over here (https://github.com/srevinsaju/guiscrcpy/releases).

Download the file that ends with .AppImage

After the download is complete, please double click it to run guiscrcpy

**Comment by slop-me** [comment]
I'm having the same issue but I installed it using snap all the keybinds work but no display. Also weird sidenote I have to kill adb and start it again for guiscrcpy to even see my phone when installed from snap. The appimagie works great but I can't do guiscrcpy --mapper which is the whole reason I'm using guiscrcpy

**Comment by srevinsaju** [comment]
@slop-me why is that you can't do `--mapper` on the AppImage?

After downloading the AppImage, open a terminal, 
```bash
cd /path/to/appimage/
./guiscrcpy*.AppImage --mapper
```

**Comment by slop-me** [comment]
> @slop-me why is that you can't do `--mapper` on the AppImage?
> 
> After downloading the AppImage, open a terminal,
> 
> ```shell
> cd /path/to/appimage/
> ./guiscrcpy*.AppImage --mapper
> ```

It throws 3 errors one says screenshot failed. Second one throws a very large error that I completely don't understand and third it throws another error saying to do --mapper-reset when I haven't set up a mapper. It cycle between these 3 I tried around 30 times and then just gave up

**Comment by srevinsaju** [comment]
@slop-me I would be glad if you could send me the output, so that I can fix it.

**Comment by slop-me** [comment]
> @slop-me I would be glad if you could send me the output, so that I can fix it, in a future release

Sure now I'm getting 5 different errors. I can't get the other 3 to pop up today for some reason I'll post then when I get them

First one is adb crashes with the title being "ADB crashed with SIGABRT in fatal()" This causes guiscrcpy to hang
This happens after doing --mapper and when I try to click the device point to key mapper button

Similar to the first one ADB crashes with the same error when trying to ./guiscrcpy.appimage --mapper then it stops on saying "Lets check"

**Comment by srevinsaju** [comment]
@slop-me Are you using AppImage? If yes, which version?

**Comment by slop-me** [comment]
> @slop-me Are you using AppImage? If yes, which version?

Those errors are on 3.9.3
This error is on 4.0b1
```Detected SurfaceOrientation, processing...
Detected Landscape orientation...
Traceback (most recent call last):
  File "/tmp/.mount_guiscr7lmsVs/opt/python3.8/bin/guiscrcpy", line 6, in <module>
    from guiscrcpy.launcher import bootstrap
  File "/tmp/.mount_guiscr7lmsVs/opt/python3.8/lib/python3.8/site-packages/guiscrcpy/launcher.py", line 366, in <module>
    mp = Mapper(mapper_device_id)
  File "/tmp/.mount_guiscr7lmsVs/opt/python3.8/lib/python3.8/site-packages/guiscrcpy/lib/mapper/mapper.py", line 70, in __init__
    self.dimensions = self.dimensions[::-1]
TypeError: 'bool' object is not subscriptable
```

**Comment by srevinsaju** [comment]
Thanks, let me check. Thanks for testing

**Comment by srevinsaju** [comment]
Can you give me the output of 
```
guiscrcpy --adb shell wmctrl size
```

**Comment by slop-me** [comment]
Error on 4.0b1. This happens when I it does take a screen shot and I click a spo type a letter and click okay it crashes with this
```Generating Screenshot: c0b39bc107df4b329a8e3c0f867b1d74
Please wait. A full definition screenshot is being captured
[LOG] Screenshot captured. Saved to /home/name/.config/guiscrcpy/
PyQt5.QtCore.QPoint(65, 702) LAST
Traceback (most recent call last):
  File "/tmp/.mount_guiscrqPnicW/opt/python3.8/lib/python3.8/site-packages/guiscrcpy/lib/mapper/ux.py", line 136, in register_key
    fixx = relx * int(self.dimensions[0])
TypeError: 'bool' object is not subscriptable
/tmp/.mount_guiscrqPnicW/AppRun: line 23: 14735 Aborted                 (core dumped) ${APPDIR}/usr/bin/python3.8 -s ${APPDIR}/opt/python3.8/bin/guiscrcpy "$@"```

**Comment by slop-me** [comment]
```guiscrcpy --adb shell wmctrl size
usage: guiscrcpy v3.9.3 [-h] [-i] [-s]
                        [--start-scrcpy-device-id START_SCRCPY_DEVICE_ID] [-r]
                        [--mapper] [--mapper-reset] [--mapper-delay]
                        [--mapper-device-id MAPPER_DEVICE_ID] [-w]
                        [--connect CONNECT] [-q] [--panels-not-always-on-top]
                        [--theme THEME] [-f] [-o] [-k] [-d DEBUG] [-v]
guiscrcpy v3.9.3: error: unrecognized arguments: --adb shell wmctrl size
```

**Comment by srevinsaju** [comment]
Yes, its related to the first error. 

If https://github.com/srevinsaju/guiscrcpy/issues/156#issuecomment-673577424 does not work, try this
```
adb shell wmctrl size
```

**Comment by slop-me** [comment]
```sudo adb shell wmctrl size
[sudo] password for name: 
/system/bin/sh: wmctrl: inaccessible or not found``` Same for both sudo and not sudo

**Comment by srevinsaju** [comment]
```
adb shell wm size
```
?

**Comment by slop-me** [comment]
`adb shell wm size
Physical size: 1440x3200
Override size: 1080x2400
`

**Comment by srevinsaju** [comment]
Which device are you using? Model Number?

**Comment by slop-me** [comment]
SM-G988W

**Comment by srevinsaju** [comment]
Thanks

**Comment by slop-me** [comment]
Np just let me know if you figure something out. Thanks

**Comment by srevinsaju** [comment]
@slop-me can you do this.
```
./guiscrcpy*.AppImage --appimage-extract
cd squashfs-root
usr/bin/adb shell wm size
```

**Comment by srevinsaju** [comment]
This is an odd case, and I cannot reproduce. `adb` did not return a value

**Comment by slop-me** [comment]
usr/bin/adb shell wm size
adb server version (39) doesn't match this client (41); killing...
* daemon started successfully
Physical size: 1440x3200
Override size: 1080x2400

**Comment by srevinsaju** [comment]
Can you now do 
```
./AppRun
```

**Comment by slop-me** [comment]
I did ./AppRun it loaded worked fine but then when I did ./AppRun --mapper it crashed for the ADB error and getting stuck on Lets check

**Comment by srevinsaju** [comment]
Did it crash?

**Comment by slop-me** [comment]
Yeah

"I did ./AppRun --mapper it crashed for the ADB error and getting stuck on Lets check"
> I did ./AppRun it loaded worked fine but then when I did ./AppRun --mapper it crashed for the ADB error and getting stuck on Lets check

**Comment by srevinsaju** [comment]
Can you paste the terminal output?
What is the output of 
```uname -a```

**Comment by slop-me** [comment]
Linux Name 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by srevinsaju** [comment]
@slop-me Hey, it looks like you are running `guiscrcpy 3.9.3` instead of `guiscrcpy 4.0.b1`. Am I right>

**Comment by slop-me** [comment]
I am trying with both. Both result in a crash but different crashes

**Comment by slop-me** [comment]
The output you were getting was from 3.9.3 tho

**Comment by srevinsaju** [comment]
Please try with only `4.0.b1` and paste the errors from there

**Comment by slop-me** [comment]
usr/bin/adb shell wm size
adb server version (39) doesn't match this client (41); killing...
* daemon started successfully
adb: no devices/emulators found

**Comment by srevinsaju** [comment]
Makes sense, device is not detected;

**Comment by srevinsaju** [comment]
`./usr/bin/adb devices` to confirm

**Comment by slop-me** [comment]
Intializing GUI window
False
Creating QtCore window Application instance
Make sure your phone display is switched on.
Generating Screenshot: 02ed8c56275947bd817143ad3812d01d
Please wait. A full definition screenshot is being captured
[LOG] Screenshot captured. Saved to /home/name/.config/guiscrcpy/
PyQt5.QtCore.QPoint(155, 585) LAST
Traceback (most recent call last):
  File "/home/name/Downloads/squashfs-root/opt/python3.8/lib/python3.8/site-packages/guiscrcpy/lib/mapper/ux.py", line 136, in register_key
    fixx = relx * int(self.dimensions[0])
TypeError: 'bool' object is not subscriptable
./AppRun: line 23: 16906 Aborted                 (core dumped) ${APPDIR}/usr/bin/python3.8 -s ${APPDIR}/opt/python3.8/bin/guiscrcpy "$@"

**Comment by slop-me** [comment]
That's from the mapper when I try to set a key it crashes with that error and adb crashes when I run --mapper

**Comment by srevinsaju** [comment]
https://github.com/srevinsaju/guiscrcpy/issues/156#issuecomment-673590028 Please

**Comment by slop-me** [comment]
List of devices attached
R3CN3016MFE	device

**Comment by srevinsaju** [comment]
```bash
./usr/bin/adb devices -l
./usr/bin/adb shell wm size
./AppRun --mapper
```
I want the output of the following code executed together

**Comment by slop-me** [comment]
./usr/bin/adb devices -l
List of devices attached
R3CN3016MFE            device usb:1-5 product:z3qcsw model:SM_G988W device:z3q transport_id:1

./usr/bin/adb shell wm size
Physical size: 1440x3200
Override size: 1080x2400

./AppRun --mapper
./AppRun: line 12: cert-file: command not found
                                  

guiscrcpy
by srevinsaju
4.0.b1
Licensed under GNU GPL v3 (c) 2020  
                                  


MSG: Please ensure you have enabled USB Debugging on your device. See README.md for more details
+++++++++++++++++++++++++++++++++++++++
guiscrcpy ~ mapper by srevinsaju
=======================================
Make sure that your device is turned on, and connected to your PC
With USB debugging turned on.
+++++++++++++++++++++++++++++++++++++++
Waiting for device
Device : OK!

Initializing guiscrcpy mapper v3.5-
E: Command 'adb shell wm size' exited with 1
Detected SurfaceOrientation, processing...
Detected Landscape orientation...
Traceback (most recent call last):
  File "/home/name/Downloads/squashfs-root/opt/python3.8/bin/guiscrcpy", line 6, in <module>
    from guiscrcpy.launcher import bootstrap
  File "/home/name/Downloads/squashfs-root/opt/python3.8/lib/python3.8/site-packages/guiscrcpy/launcher.py", line 366, in <module>
    mp = Mapper(mapper_device_id)
  File "/home/name/Downloads/squashfs-root/opt/python3.8/lib/python3.8/site-packages/guiscrcpy/lib/mapper/mapper.py", line 70, in __init__
    self.dimensions = self.dimensions[::-1]
TypeError: 'bool' object is not subscriptable

**Comment by slop-me** [comment]
./AppRun --mapper
./AppRun: line 12: cert-file: command not found
                                  

guiscrcpy
by srevinsaju
4.0.b1
Licensed under GNU GPL v3 (c) 2020  
                                  


MSG: Please ensure you have enabled USB Debugging on your device. See README.md for more details
+++++++++++++++++++++++++++++++++++++++
guiscrcpy ~ mapper by srevinsaju
=======================================
Make sure that your device is turned on, and connected to your PC
With USB debugging turned on.
+++++++++++++++++++++++++++++++++++++++
Waiting for device
Device : OK!

Initializing guiscrcpy mapper v3.5-
E: Command 'adb shell wm size' exited with 1
Detected SurfaceOrientation, processing...
Detected Portait orientation...
guiscrcpy.mapper.json does not exist. 
Initializing Mapper Configuration for the first time use.
Setting up guiscrcpy-mapper for the first time use...
Intializing GUI window
False
Creating QtCore window Application instance
Make sure your phone display is switched on.
Generating Screenshot: a6285735e0c642e8a284a16be412e210
Please wait. A full definition screenshot is being captured
[LOG] Screenshot captured. Saved to /home/name/.config/guiscrcpy/
PyQt5.QtCore.QPoint(294, 318) LAST
Traceback (most recent call last):
  File "/home/name/Downloads/squashfs-root/opt/python3.8/lib/python3.8/site-packages/guiscrcpy/lib/mapper/ux.py", line 136, in register_key
    fixx = relx * int(self.dimensions[0])
TypeError: 'bool' object is not subscriptable
./AppRun: line 23: 19344 Aborted                 (core dumped) ${APPDIR}/usr/bin/python3.8 -s ${APPDIR}/opt/python3.8/bin/guiscrcpy "$@"

**Comment by slop-me** [comment]
I gave it a try on windows and it doesn't work either it just gets stuck at initializing mapper forever

**Comment by srevinsaju** [comment]
@rr10 Do you want to use AppImages?

**Comment by rr10** [comment]
i prefer apt or snap

**Comment by zuzuca** [comment]
Hello, i reopen this with same problem, i have samsung A21s and i have mapper ok, its work perfectly but i cant see the display
