### ISSUE TITLE
guiscrcpy crashed on Ubuntu 18.04 when i use mouse  to click some button

### ISSUE THREAD

**Issue by moluoyu** [srevinsaju/guiscrcpy#16]
i down guiscrcpy from pip. when i click other button ,it doesn't any response.when i click  "full screen "  button.it crash. the log in the below:

> Hello!
/home/luoyu/anaconda3/lib/python3.7/site-packages/guiscrcpy/app.py
DETECTED OS :: *NIX
 luoyu@luoyu-pc  /etc/udev/rules.d  LOG: Received flag False                         
guiscrcpy
by srevinsaju
released on 03102019
Licensed under GNU GPL v3 (c) 2019  
MSG: Please ensure you have enabled USB Debugging on your device. See README.md for more details
LOG: Current Working Directory /home/luoyu/anaconda3/lib/python3.7/site-packages/guiscrcpy
LOG: Script       Path         >>  /home/luoyu/anaconda3/lib/python3.7/site-packages/guiscrcpy/
LOG: Configuration file found in USER_HOME directory
LOG: Importing modules...
ADB:  adb server version (39) doesn't match this client (36); killing...
LOG: Options received by class are :  1273 None False False False
SCRCPY SERVER IS INACTIVE
ADB:  ['8f219a030404', 'offline\n']
ADB:  ['8f219a030404', 'offline\n']
ADB:  ['8f219a030404', 'device\n']
LOG: CONNECTION ESTABLISHED
LOG: Flags passed to scrcpy engine :   -b 1273K
LOG: SCRCPY is launched in 1.538116455078125 seconds
LOG: Passing HOME
LOG: Passing MENU
LOG: Passing APP_SWITCH
LOG: Passing REORIENT [POTRAIT]
LOG: Passing REORIENT [LANDSCAPE]
Traceback (most recent call last):
  File "__main__.py", line 507, in fullscreen
    + bcolors.ENDC
NameError: name 'bcolor' is not defined
Aborted (core dumped)

**Comment by srevinsaju** [comment]
@moluoyu the fullscreen option is not currently functional. Read README.md. You can alternatively use Ctrl+F or Meta+F to Fullscreen your devcie.

**Comment by moluoyu** [comment]
no.it not just for the fullscreen option. other buttons also not functional,besides the windows of the devices will disappear .and I can't use my mouse to lick any app on the screen of my cellphone.
the output like this:

![Selection_020](https://user-images.githubusercontent.com/27038644/68035666-0b6c0780-fcff-11e9-8755-73dcb1f82e2f.png)

**Comment by moluoyu** [comment]
i   found  the reason.It the configure of my phone.Thanks.
[https://github.com/Genymobile/scrcpy/issues/70#issuecomment-373286323](url)
