### ISSUE TITLE
[BUG]guiscrcpy 4.5.0 [9548] Failed to execute script entry

### ISSUE THREAD

**Issue by Papotito123** [srevinsaju/guiscrcpy#172]
**Describe the bug**
Tested version 3.9.3 works well.When run version 4.5.0 crashed.

G:\scrcpy(scrcpy GUI version) 4.5.0_(7SEPT2020)>guiscrcpy.exe
No conda env active, defaulting to base

guiscrcpy 4.5.0
by @srevinsaju
https://github.com/srevinsaju/guiscrcpy

Traceback (most recent call last):
  File "entry.py", line 1, in <module>
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1236, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "guiscrcpy\cli.py", line 91, in cli
  File "guiscrcpy\launcher.py", line 1246, in bootstrap
  File "guiscrcpy\launcher.py", line 1202, in set_scrcpy_server_path
  File "os.py", line 680, in __setitem__
  File "os.py", line 736, in check_str
TypeError: str expected, not NoneType
[9548] Failed to execute script entry

**Expected behavior**
To run well as other versions

**Desktop (please complete the following information):**
* [x] Windows 10 1809 
- **Architecture**: 64-bit
- **Version**: build 17763.1282

Thanks for any info.

**Comment by srevinsaju** [comment]
@Papotito123 Thanks for reporting the bug. I will push a fix soon!

**Comment by srevinsaju** [comment]
@Papotito123 simple fix 

Remove this file

`C:\Users\< Your user name>\AppData\Local\guiscrcpy\guiscrcpy.json`

cheers!

**Comment by srevinsaju** [comment]
It normally happens when you use two version of guiscrcpy. Each as different configs, and they get mixed up. Before running a new version of guiscrcpy, it is recommended to delete the config file.

**Comment by Papotito123** [comment]
Hello:
Thanks for answer and explanation.

I will do later and post.

**Comment by Papotito123** [comment]
Hello:
I did what you recommend.
When run guiscrcpy.exe the app just flash for less than 1 second but still gives:
C:\Users\TESTACCOUNT\Downloads\scrcpy(scrcpy GUI version) 4.5.0_(7SEPT2020)>guiscrcpy.exe
No conda env active, defaulting to base

guiscrcpy 4.5.0
by @srevinsaju
https://github.com/srevinsaju/guiscrcpy


Traceback (most recent call last):
  File "entry.py", line 1, in <module>
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1236, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "guiscrcpy\cli.py", line 91, in cli
  File "guiscrcpy\launcher.py", line 1246, in bootstrap
  File "guiscrcpy\launcher.py", line 1202, in set_scrcpy_server_path
  File "os.py", line 680, in __setitem__
  File "os.py", line 736, in check_str
TypeError: str expected, not NoneType
[4668] Failed to execute script entry

**Comment by Papotito123** [comment]
Hello:
Downloaded latest guiscrcpy continuos version.

[papotito123_guiscrcpy.json.txt](https://github.com/srevinsaju/guiscrcpy/files/5205206/papotito123_guiscrcpy.json.txt)

Here's the json file.

I see "adb": null .

**Comment by srevinsaju** [comment]
@Papotito123 , can you go to your scrcpy folder, and then copy the path to `scrcpy.exe` and paste it the configuration file, like

```json
"scrcpy": "C:/path/to/scrcpy.exe"
```

Similarly, replace `adb` and `scrcpy-server` with their respective paths

```json
"scrcpy-server": "C:/path/to/scrcpy-server"
"adb": "C:/path/to/adb.exe"
```

**Comment by Papotito123** [comment]
Hello:
I'll try later.

I  tried by copyingthe scrcpy 1.16 folder containing guiscrcpy.exe latest continuous to C: root and deleting guiscrcpy.json before.
And gives same error.

**Comment by Papotito123** [comment]
Hello:
Sorry I'm not a so skilled.
I did not have any configuration file in my C:\scrcpy folder.

What I did was to add scrcpy.exe/ scrcpy-server / guiscrcpy.exe to PATH in Environment Variables . But same error

Then , I modify the C:\Users< Your user name>\AppData\Local\guiscrcpy\guiscrcpy.json file and add these files paths.
{ Then I realized that was what you want me to accomplish}

And yes, guiscrcpy.exe opens.

But, why in this way ?
I'm certain that after using v3.9.3 I used v4.3 continuous and with some issue(no run well at first, then works but seems adb.exe keeps hangs after closing guiscrcpy.exe)

So I should have this .\.\guiscrcpy.json file as a dummy ?

So much thanks for support.

**Comment by srevinsaju** [comment]
> Hello:
> Sorry I'm not a so skilled.
> I did not have any configuration file in my C:\scrcpy folder.
> 

Its okay to not be skilled. No one was born genius including me. :smile:


> What I did was to add scrcpy.exe/ scrcpy-server / guiscrcpy.exe to PATH in Environment Variables . But same error
> 
> Then , I modify the C:\Users< Your user name>\AppData\Local\guiscrcpy\guiscrcpy.json file and add these files paths.
> { Then I realized that was what you want me to accomplish}
> 
> And yes, guiscrcpy.exe opens.
> 
> But, why in this way ?
> I'm certain that after using v3.9.3 I used v4.3 continuous and with some issue(no run well at first, then works but seems adb.exe keeps hangs after closing guiscrcpy.exe)
> 
> So I should have this .\.\guiscrcpy.json file as a dummy ?
> 
> I noticed that even using the red (x) button to finish (and stop sub-process) , and even closing the cmd , still adb.exe shows as running in Task Manager. Should be normal?


Adb keeps running in the background. Thats extremely normal. I will attempt to fix that bug. You can take a copy of your edited `guiscrcpy.json` in some safe place, so that in case something goes wrong, you can replace. You are testing a continuous / beta build, so sometimes, things might not work properly. This is one of the reason why I still have not published 4.5 to stable channel. I will try to do a lot of testing. We do not have many testers at guiscrcpy. Its mostly me and yochananmarqos who tests guiscrcpy beta. If we have more people testing, we can find more bugs, and more people could fix bugs. 

Anyway thanks for reporting this bug. i will attempt to fix it soon and make a stable release!!


> 
> So much thanks for support.

Youre welcome :)

**Comment by Papotito123** [comment]
Thanks for your support.

**Comment by Papotito123** [comment]
Hello:
I'm just looking thru v 3.9.3 launcher.py and compare to v4.5.0 continuous and see this part that is not in 4.5.0 ,and talks about adb is None and what to do; 

Launch the guiscrcpy window
    :return:
    """
    # enable High DPI scaling
    QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)
    QApplication.setAttribute(
        QtCore.Qt.AA_UseHighDpiPixmaps, True
    )  # use HIGH DPI icons
    app = QtWidgets.QApplication(sys.argv)

    app.setStyle(args.theme)

    if args.theme == 'Breeze':
        # The Qdarkstylesheet is based on Breeze, lets load them on default
        app.setStyleSheet(dark_stylesheet())

    splash_pix = QPixmap(":/res/ui/guiscrcpy-branding.png")
    splash = QtWidgets.QSplashScreen(splash_pix)
    splash.setMask(splash_pix.mask())
    splash.show()
    app.processEvents()
    cfg_edited = False

    if (adb.path is None) or (not os.path.exists(adb.path)):
        adb.path = open_exe_name_dialog(None, 'adb')
        cfg_edited = True
        config['adb'] = adb.path

    if (scrcpy.path is None) or (not os.path.exists(scrcpy.path)):
        scrcpy.path = open_exe_name_dialog(None, 'scrcpy')
        cfg_edited = True
        config['scrcpy'] = scrcpy.path

    # on windows, users are likely not to add the scrcpy-server to the
    # SCRCPY_SERVER_PATH
    scrcpy_server_path_env = os.getenv('SCRCPY_SERVER_PATH', None)
    if scrcpy_server_path_env:
        if os.path.exists(scrcpy_server_path_env):
            config['scrcpy-server'] = scrcpy.server_path
        else:
            scrcpy.server_path = open_exe_name_dialog(None, 'scrcpy-server')
            cfg_edited = True
            config['scrcpy-server'] = scrcpy.server_path
            os.environ['SCRCPY_SERVER_PATH'] = scrcpy.server_path
    elif (
        (scrcpy.server_path is None) or
        (not os.path.exists(scrcpy.server_path))
    ) and (
        platform.System().system() == 'Windows'
    ):
        scrcpy.server_path = open_exe_name_dialog(None, 'scrcpy-server')
        cfg_edited = True
        config['scrcpy-server'] = scrcpy.server_path
        os.environ['SCRCPY_SERVER_PATH'] = scrcpy.server_path
    elif platform.System().system() == "Windows":
        os.environ['SCRCPY_SERVER_PATH'] = scrcpy.server_path

Just looking.

**Comment by srevinsaju** [comment]
@Papotito123 Thanks for trying to fix the bug. These lines have been moved to this file now `guiscrcpy/lib/check.py`, I have done a lot of code refactoring and performance improvements. In the process of adding features, I might have missed this bug. Thanks for finding it and reporting it. I have an open Pull Request #177 which should solve this bug. I will wait for the tests to pass, and then I will merge the PR so that it gets released to continuous release

**Comment by Papotito123** [comment]
Hello:
Cool.
I'll test and post.

Thanks.

**Comment by srevinsaju** [comment]
#177 merged. An exe will be created in 12 minutes

**Comment by srevinsaju** [comment]
You can track this link https://github.com/srevinsaju/guiscrcpy/actions/runs/252030367 to see when guiscrcpy is going to be released ( so that you don't download the wrong release :smile:))

**Comment by Papotito123** [comment]
Hello:
I tested pre-release 4.6.1 and guiscrpy opens and run.
Now ask for adb-server path.

With a phone connected and then running guiscrcpy.exe ,phone didn't showed.
So I have to close guiscrcpy.exe , run adb.exe kill-server and disconnect phone.
Then run guiscrcpy.exe  and after opens then connect the phone.

But it works.

So much thanks.

**Comment by Papotito123** [comment]
Hello:
I tested release 4.7,2 and opens and run well.

I only can copy-paste file-foder from phone to sdcard in phone.But not from phonr to pc.
There's a way to do it ?

As a workaround I can use a file explorer that manage transfer files in network and with a shared folder in Windows.

Thanks.

**Comment by srevinsaju** [comment]
No, its not possible through guiscrcpy. but is possible over `adb`

```bash
adb pull /sdcard/path/to/file/in/mobile .
```
will transfer the file from mobile to the current directory

**Comment by srevinsaju** [comment]
Closing this issue, as it looks like the original issue has been solved. Thanks @Papotito123
