### ISSUE TITLE
[BUG][AppImage] Doesn't contain all needed libraries

### ISSUE THREAD

**Issue by Justinzobel** [srevinsaju/guiscrcpy#173]
**Describe the bug**
AppImage won't start

**To Reproduce**
Download AppImage versioned build
chmod +x
Launch
Error:
```
Traceback (most recent call last):
  File "/tmp/.mount_guiscrlbta8X/opt/python3.8/bin/guiscrcpy", line 6, in <module>
    from guiscrcpy.launcher import bootstrap
  File "/tmp/.mount_guiscrlbta8X/opt/python3.8/lib/python3.8/site-packages/guiscrcpy/launcher.py", line 44, in <module>
    from PyQt5 import QtCore, QtWidgets
ImportError: libbsd.so.0: cannot open shared object file: No such file or directory
```

**Expected behavior**
Launch

**Desktop (please complete the following information):**
* [X] Linux
Solus 4.1 Plasma x86_64

**Comment by srevinsaju** [comment]
@Justinzobel can you test the new `continuous` tag build (pre release) https://github.com/srevinsaju/guiscrcpy/releases/tag/continuous

**Comment by Justinzobel** [comment]
Thanks @srevinsaju that seems to have done it but now I have a different issue. The GUI loads but when running scrcpy I get the following:
```
/tmp/.mount_guiscreYZRgQ/usr/bin/adb: symbol lookup error: /tmp/.mount_guiscreYZRgQ/usr/libscrcpy/libc.so.6: undefined symbol: _dl_fatal_printf, version GLIBC_PRIVATE
```

**Comment by srevinsaju** [comment]
Thanks, I tested it yesterday on XUbuntu 18.04 and it crashed with the same error. I will try a fix. Its easy to package guiscrcpy alone, but packagong scrcpy is very painful. Hopefully I fix it today

**Comment by srevinsaju** [comment]
@Justinzobel I rebuilt the appimage. Hopefully it works now. I would be glad if you could test it and let me know. Now all whats not bundled are graphic drivers. I hope that would be found on default on the host system

**Comment by Justinzobel** [comment]
/tmp/.mount_guiscrknn0Zo/scrcpy/usr/bin/scrcpy: error while loading shared libraries: libnuma.so.1: cannot open shared object file: No such file or directory

**Comment by Justinzobel** [comment]
^ downloaded AppImage from 12hours ago.

**Comment by srevinsaju** [comment]
Thanks, I will bundle that one too.

**Comment by srevinsaju** [comment]
@Justinzobel fixed it on `continuous` release. Tested on Solus Budgie 4.1. Looks good. Please test and let me know

**Comment by Justinzobel** [comment]
Thanks, all fixed now.

**Comment by Justinzobel** [comment]
Sorry, premature, wmctrl is not included in the AppImage for fullscreen support.

**Comment by srevinsaju** [comment]
@Justinzobel I might not bundle wmctrl. Its an optional dependency. For making `scrcpy` full screen, I guess, you could do `Alt + F` or `Ctrl + F`. I hope that would be ok, right?

**Comment by srevinsaju** [comment]
The `PyGetWindow` library is not mature yet for Linux, and using wmctrl is not the right way of doing things. I will wait for `PyGetWindow` (a helper library of PyAutoGUI, a famous window management library).

**Comment by Justinzobel** [comment]
Ah yes that works, might I suggest removing the button for full-screen and or just make it a null button and the tooltip say to use Alt + F.

**Comment by srevinsaju** [comment]
Yes. I agree. Thanks for the suggestion
