### ISSUE TITLE
gciscrcpy don't display the window of devices on ubuntu 18.04

### ISSUE THREAD

**Issue by moluoyu** [srevinsaju/guiscrcpy#18]
I found another bug.when I click some button. For example, "volume up" or "volume down ".From my cell phone, I see it work. but on the pc, I can't see the window of my cell phone.

my device: xiaomi 5x
android version: 8.1.0
`MSG: Please ensure you have enabled USB Debugging on your device. See README.md for more details
LOG: Current Working Directory /home/luoyu/anaconda3/lib/python3.7/site-packages/guiscrcpy
LOG: Script       Path         >>  /home/luoyu/anaconda3/lib/python3.7/site-packages/guiscrcpy/

LOG: Configuration file found in USER_HOME directory
LOG: Importing modules...
ADB:  adb server version (39) doesn't match this client (36); killing...

LOG: Options received by class are :  8000 None False False False
SCRCPY SERVER IS INACTIVE
ADB:  ['8f219a030404', 'device\n']
LOG: CONNECTION ESTABLISHED
LOG: Flags passed to scrcpy engine :   --always-on-top -b 8000K
LOG: SCRCPY is launched in 1.9268434047698975 seconds
LOG: Passing BACK
LOG: Passing BACK
LOG: Passing BACK
LOG: Passing BACK
LOG: Passing BACK
LOG: Passing APP_SWITCH
LOG: Passing APP_SWITCH
LOG: Passing POWER
LOG: Passing APP_SWITCH
`

**Comment by srevinsaju** [comment]
@moluoyu , is guiscrcpy installed from pip? Can you share a screenshot of the guiscrcpy ui window.

**Comment by moluoyu** [comment]
yes.i install guisdisappaearedcrcpy from pip. when i click the "HOME" button .the window of cell phone 
disappeared.And sometimes, the guiscrcpy ui window will crash(the second screenshot)

![image](https://user-images.githubusercontent.com/27038644/68087017-bbbb4680-fe8c-11e9-90b3-37c623558f2e.png)

![image](https://user-images.githubusercontent.com/27038644/68087155-ebb71980-fe8d-11e9-8387-ab9875d35d33.png)

**Comment by srevinsaju** [comment]
@moluoyu , you are not running the latest version of guiscrcpy. Guiscrcpy v1.11.3 was a bugfix release. Probably, that might solve your error. This error normally happens when you try to drag the panel by clicking on any button. Please try updating, and check the new results. Looking forward to hear from you.

**Comment by moluoyu** [comment]
Thanks, it work!.i'm so sorry to bother you because of some fake bug.
