### ISSUE TITLE
[BUG] scrcpy window is not showing

### ISSUE THREAD

**Issue by MikolajKakol** [srevinsaju/guiscrcpy#188]
**Describe the bug**
After clicking start scrcpy button nothing really happens. In console I've got:
```
➜  ~ guiscrcpy

guiscrcpy
by srevinsaju
3.9.3
Licensed under GNU GPL v3 (c) 2020  
                                  


MSG: Please ensure you have enabled USB Debugging on your device. See README.md for more details
scrcpy launched in 0.15s

```

**To Reproduce**
1. Launch app 
2. Click on 'start scrcpy'
3. See that only bars appeared but no phone window

**Expected behavior**
I would expect to scrcpy window with my phone display. Regular scrcpy application (v1.16) is working and displaying my phone content.

**Desktop (please complete the following information):**
* [ ] Linux
```
            .-/+oossssoo+/-.               mikolaj@miko-Z97-HD3 
        `:+ssssssssssssssssss+:`           -------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04.1 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: Z97-HD3 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.4.0-48-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 3 days, 23 hours, 8 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 1736 (dpkg), 14 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: zsh 5.8 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 3440x1440 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Yaru-dark [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Yaru [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: gnome-terminal 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i7-4790 (8) @ 4.000GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: NVIDIA GeForce GTX 760 
      -+sssssssssssssssssyyyssss+-         GPU: Intel HD Graphics 
        `:+ssssssssssssssssss+:`           Memory: 16657MiB / 31986MiB 
            .-/+oossssoo+/-.
                                                           
```        
   
**Additional context**
I had one issue before in log `sh: 1: wmctrl: not found` after installing it main issue remained.

**Comment by srevinsaju** [comment]
:smile: v3.9.3 is deprecated :) A new version had been released quite a while ago. How did you get the old version (3.9.3) ? Are there any broken links leading to the old release?

**Comment by MikolajKakol** [comment]
I used `snap` to install this version :)

**Comment by srevinsaju** [comment]
Thanks. I have been not focusing on snaps recently. Can you try out the appimage and let me know if the issue persists?

**Comment by srevinsaju** [comment]
Release 4.7.2 to `stable` channel on `snapstore`

**Comment by MikolajKakol** [comment]
Thank you for the update now I have new version, however now I've got
```
➜  ~ guiscrcpy   
Usage: guiscrcpy [OPTIONS] COMMAND [ARGS]...
Try 'guiscrcpy --help' for help.

Error: No such command '/snap/guiscrcpy/224/usr/bin/python3'.
➜  ~ python3
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on linux
```
it's looking for python in the wrong place or maybe dependencies are not properly defined

**Comment by srevinsaju** [comment]
Thanks. `snaps` have their own local python interpreter. However snaps don't work on my system (Arch Linux), and I could not test it. Possibly I have to update snap script. I always wished I could stop distributing snaps, but a lot of people are dependent on the snaps.

**Comment by srevinsaju** [comment]
Thanks for reporting, I shall find a fix.

**Comment by MikolajKakol** [comment]
I tried to use this appimage it worked. Snap I think offers a better install experience, with auto-updates and creating shortcuts. Thank you for all effort.

**Comment by srevinsaju** [comment]
@MikolajKakol see [`zap`](https://github.com/srevinsaju/zap) for Desktop Integration, Delta Updates and seamless configuration of AppImage

**Comment by JMarianoIFSTTAR** [comment]
> Thank you for the update now I have new version, however now I've got
> 
> ```
> ➜  ~ guiscrcpy   
> Usage: guiscrcpy [OPTIONS] COMMAND [ARGS]...
> Try 'guiscrcpy --help' for help.
> 
> Error: No such command '/snap/guiscrcpy/224/usr/bin/python3'.
> ➜  ~ python3
> Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
> [GCC 9.3.0] on linux
> ```
> 
> it's looking for python in the wrong place or maybe dependencies are not properly defined

Same issue. (exactly / except python3 --> python 3.6.9)

**Comment by srevinsaju** [comment]
I attempted a fix, lets see how it goes. 
The fixed snap will be released to the `edge` channel on snapcraft within a few minutes

**Comment by srevinsaju** [comment]
Tested on Ubuntu 20.10 "Groovy Gorilla", `guiscrcpy` now starts.

**Comment by srevinsaju** [comment]
![image](https://user-images.githubusercontent.com/48695438/94994452-57bf6780-05a0-11eb-8aef-50a42e73a67a.png)

**Comment by srevinsaju** [comment]
@JMarianoIFSTTAR @MikolajKakol Fixed the snap release :tada: Let me know if anything's wrong!!
