### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Fuadrtx** [srevinsaju/guiscrcpy#194]
![Screenshot (171)](https://user-images.githubusercontent.com/75134519/101208935-7d064a00-36a5-11eb-855f-f492771dfca9.png)

**Comment by srevinsaju** [comment]
The solution is to remove `C:/Users/<Username>/AppData/Local/guiscrcpy/*.json`

It would be also helpful if you post this file `C:/Users/<Username>/AppData/Local/guiscrcpy/*.json` here, so I can make sure nothing is going wrong before deleting

**Comment by Fuadrtx** [comment]
thanks work
