### ISSUE TITLE
"Aborted" Shows when trying to start scrcpy, No display but buttons work fine.

### ISSUE THREAD

**Issue by Ufinexa** [srevinsaju/guiscrcpy#195]
**To Reproduce**
1. Open Guiscrcpy
2. Click on "Start Scrcpy"
3. See error

**Expected behavior**
Click start and the window would display

**Screenshots**
**How the issue looks**
![](https://ufihost.xyz/i/bzL7W.png)
**Result Of Logcat**
![](https://ufihost.xyz/i/EzJtP.png)

**Desktop (please complete the following information):**
* [ ] Windows
- **Architecture**: 64-bit
- **Version**: Windows 10

**Additional context**
Running scrcpy on it's own displays the image just fine, trying to do it through this causes it to not work. I am running Lineage OS on a Google Pixel 2 XL.

**Comment by srevinsaju** [comment]
Wow, interesting. Does running `scrcpy` alone (i.e., not through guiscrcpy work?)

**Comment by Ufinexa** [comment]
Yes, running scrcpy alone works just fine.

**Comment by srevinsaju** [comment]
@Ufinexa you might like to try the new release [Continuous](https://github.com/srevinsaju/guiscrcpy/releases/tag/continuous)

**Comment by Ufinexa** [comment]
Sorry for the late response, this worked perfectly. Thank you so much :)
