### ISSUE TITLE
Run scrcpy through the gui with "--render-expired-frames" enabled?

### ISSUE THREAD

**Issue by vorikx2** [srevinsaju/guiscrcpy#20]
Pretty much what the title says. Is there anyway to launch scrcpy through the gui with "--render-expired-frames" enabled?

**Comment by srevinsaju** [comment]
The upcoming version 2.0 releasing today itself is featuring a TextBox which allows to add custom flags to scrcpy. Stay tuned

**Comment by srevinsaju** [comment]
@vorikx2 Your issue is fixed now. See guiscrcpy v2.0 https://github.com/srevinsaju/guiscrcpy/releases/tag/2.0

**Comment by vorikx2** [comment]
Fucking awesome, thanks! @srevinsaju

**Comment by srevinsaju** [comment]
:blush:
