### ISSUE TITLE
[BUG] guiscrcpy window does not show up

### ISSUE THREAD

**Issue by renanwp2** [srevinsaju/guiscrcpy#212]
The guiscrcpy window does not show up on Debian Buster ( 64-bit )  with stable repositories and guiscrcpy installed from snap repositories. 

1) install guiscrcpy package with "snap install guiscrcpy";
2) install scrcpy package with "snap install scrcpy";
3) Reboot your computer;
4) Open a terminal;
5) Connect your phone with USB Debugging on and with USB Connection mode (MTP);
3) Execute /snap/bin/guiscrcpy;
4) Click on "Start scrcpy" button;
5) No window opens and  it stops with 5% "Could not find any devices";

Neofetch: 
renan@debian
OS: Debian GNU/Linux 10 (buster) x86_64
Host: Nitro AN515-52 V1.28
Kernel: 4.19.0-13-amd64
Uptime: 30 mins
Packages: 2479 (dpkg), 5 (snap)
Shell: bash 5.0.3
Resolution: 1920x1080
WM: dwm
Theme: Brightest blackout [GTK2/3]
Icons: Breeze-Nordian-Dark-Icons [GTK2/3]
Terminal: st
Terminal Font: Liberation Mono
CPU: Intel i7-8750H (6) @ 4.100GHz
GPU: Intel UHD Graphics 630
Memory: 1098MiB / 32010MiB

I tested scrpy and everything looks good. I could enable USB Debugging mode with my device and start the adb server with my system installed adb server. For example, the sequence of commands 

0) USB Debugging on and with USB Connection mode (MTP);
1) sudo adb kill-server;
2) sudo adb start-server;
3) Then an Windows pop up on my phone;

But

0) USB Debugging on and with USB Connection mode (MTP);
1) sudo /snap/bin/guiscrcpy.adb kill-server;
2) sudo /snap/bin/guiscrcpy.adb start-server;
3) No Windows pop up on my phone;

Furthermore, when I try to enter GUI with my system's adb server to execute the command  /snap/bin/guiscrcpy and click on "start scrcpy" button, the following error shows up on terminal:

restarting in TCP mode port: 5555
scrcpy launched in 0.19s
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
/snap/guiscrcpy/249/usr/local/share/scrc...pushed. 1.0 MB/s (33622 bytes in 0.032s)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: The server version (1.16) does not match the client (1.17)
	at com.genymobile.scrcpy.Server.createOptions(Server.java:119)
	at com.genymobile.scrcpy.Server.main(Server.java:221)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338

**Comment by srevinsaju** [comment]
> java.lang.IllegalArgumentException: The server version (1.16) does not match the client (1.17)

Looks like you are using an older version of `guiscrcpy` and `scrcpy`. Can you tell me the version with

```bash
guiscrcpy --version
```
```
scrcpy --version
```
```
guiscrcpy.scrcpy --version
```

**Comment by renanwp2** [comment]
> guiscrcpy --version

My output is: 
guiscrcpy v4.8.0
by @srevinsaju
guiscrcpy v4.8.0 

> scrcpy --version

My output is: 
scrcpy 1.17

dependencies:
 - SDL 2.0.8
 - libavcodec 57.107.100
 - libavformat 57.83.100
 - libavutil 55.78.100

> guiscrcpy.scrcpy --version

and my output is: 
scrcpy 1.17

dependencies:
 - SDL 2.0.8
 - libavcodec 57.107.100
 - libavformat 57.83.100
 - libavutil 55.78.100

**Comment by srevinsaju** [comment]
Right. I would say, restarting your phone should now fix the problem. Perhaps, an older version of the server is still

**Comment by srevinsaju** [comment]
Ok, hold on. I found the bug. Fixing in a while

**Comment by renanwp2** [comment]
> Ok, hold on. I found the bug. Fixing in a while

That's quite surprising! Thanks for your support. =)

**Comment by srevinsaju** [comment]
Ok, done. Update the snap
```
sudo snap refresh guiscrcpy
```

**Comment by renanwp2** [comment]
The fastest bug fix in my life! Now the scrcpy window is opening. =) Great work! I will test the software now.

**Comment by srevinsaju** [comment]
Thanks for testing!!
