### ISSUE TITLE
[BUG] GUI Still Has Issues Reading Config File: Bitrate Not Used

### ISSUE THREAD

**Issue by esotericDisciple** [srevinsaju/guiscrcpy#213]
**Describe the bug**
Even though the bitrate is being saved to the JSON file, and the radial-slider-widget-thingie reflects the same value as the config, the gui always initializes with the lowest value (1600 KB/S) 

**To Reproduce**
1. Go to 'Application Launcher (Favorites in a Grid)'
2. Click on 'guiscrcpy'
3. Scroll down to 'Bitrate (Why is this in the template? The gui is fixed; scrolling is impossible)'

**Expected behavior**
Bitrate should have the saved value from the config file ("16000 KB/S") in the teal-green-gradient box, and scrcpy should start with that same bitrate....
 

**Screenshots**
![Screenshot_20210123_114651](https://user-images.githubusercontent.com/577091/105612507-817be480-5d71-11eb-8b47-a30f86633ade.jpg)
**Desktop (please complete the following information):**
![Screenshot_20210123_115846](https://user-images.githubusercontent.com/577091/105612731-a91f7c80-5d72-11eb-8899-9a8568b517e3.jpg)

* [ ] Linux
 - Please paste your `neofetch` here. (What is a [neofetch](https://github.com/dylanaraps/neofetch))
A `neofetch` is always available in your package repositories. 
![Screenshot_20210123_120151](https://user-images.githubusercontent.com/577091/105612784-f56abc80-5d72-11eb-948e-3432c3b154a0.png)

- > If you do not want to install neofetch; Please provide the name of your desktop environment, distro and architecture

* [ ] MacOS
 - **Version**: Example Catalina 10.15

**Additional context**
Have already skimmed #149 and searched through the issue titles to avoid duplicates...

**Comment by srevinsaju** [comment]
@esotericDisciple did you install from the AUR?

**Comment by esotericDisciple** [comment]
> @esotericDisciple did you install from the AUR?

Yes, and I switched to the git version as well

**Comment by srevinsaju** [comment]
Thanks for reporting the bug. Fixed on https://github.com/srevinsaju/guiscrcpy/commit/7c49eba574fab74b635ff4180633227b7a329c48

**Comment by esotericDisciple** [comment]
Thanks for fixing  that so fast! So I can rebuild the git version and it will work?

**Comment by srevinsaju** [comment]
Yes, ideally. It should. :smile: :crossed_fingers:

**Comment by esotericDisciple** [comment]
It does, thanks again!

**Comment by srevinsaju** [comment]
https://github.com/srevinsaju/guiscrcpy/releases/tag/v4.9.0 released, I have attributed you for discovering the bug.
