### ISSUE TITLE
Should I create a Windows Installer for this app

### ISSUE THREAD

**Issue by agam778** [srevinsaju/guiscrcpy#214]
Should I create a **guiscrcpy Windows Installer** which installs this Program in Program Files (x86) directory and also shows a shortcut in a Start Menu. Also I Will put the icon of the app as below. (Please Reply as soon as possible)

I will reduce the size of image and put it as an App Icon

![image](https://user-images.githubusercontent.com/68941022/105861074-5533c280-6014-11eb-8cd2-9e0fb82d0bc6.png)

**Comment by srevinsaju** [comment]
Do you mean [`choco`](https://chocolatey.org/)?

**Comment by srevinsaju** [comment]
I would not like to have any other installer which uses `nsis`, `msi`, `InstallShield` etc, but I am interested in getting a `choco` installer of a `winget` or a `Windows Store` entry working. If its this case, then I am fine with it, and happy to add you to the list of contributors on your first successful submission.

**Comment by agam778** [comment]
Ok. So first i will try to publish in Chocolately. And if possible, I will also try to put it in Microsoft Store. But it will be with the name - Agampreet Singh Bajaj. Is it Fine?

**Comment by srevinsaju** [comment]
Provided you keep them updated. Chocolatey & Winget supports multiple authors, so you can add me too. I should be able to update the software if at a time you stop contributing to guiscrcpy. As long as both these conditions are accepted, its okay.

**Comment by agam778** [comment]
So your name is Srevin Saju

**Comment by srevinsaju** [comment]
Yes.

**Comment by agam778** [comment]
Cant

**Comment by srevinsaju** [comment]
Wait, is it a problem with the name?

**Comment by agam778** [comment]
No because your app requires python installation and pip scrcpy as rooy which is not possible through Chocolately and Winger

**Comment by agam778** [comment]
If you can compile guiscrcpy with already inluded python and main scrcpy then i could upload it

**Comment by srevinsaju** [comment]
Well, looks like you are new comer to `guiscrcpy`. I will wait for someone else to package `guiscrcpy`. Thanks for your suggestions.
