### ISSUE TITLE
[Issue]Changing logo not reflecting after install & launch

### ISSUE THREAD

**Issue by rajesh0745** [srevinsaju/guiscrcpy#219]
HI Sir,
Could you please help me to change the logos in guiscrcpy, i have replaced my own logos with same name (guiscrcpy.png) in pyappimage and in guiscrcpy\ui\ui\guiscrcpy_logo.png and run below commands
1. pip install .
2. python -m guiscrcpy.cli

but new logos not changing/reflecting and displaying previous/old logos only in main screen.

Could you please help us in this regard.

Thank You Sir
B. Rajesh

**Comment by srevinsaju** [comment]
btw, why do you want to change the logo :thinking: ?

**Comment by rajesh0745** [comment]
I am trying to understand the project sir. I am checking & learning by doing some modifications in the project. but  i unable to understand where its taking the logos. Even though i have changed it, its not reflecting it after running above commands. 
can you please guide me sir

Thanks & Regards
B.Rajesh

**Comment by rajesh0745** [comment]
HI Sir,
Could please help us for audio sharing and copy , paste file functionality from clip board.

**Comment by srevinsaju** [comment]
See #201
