### ISSUE TITLE
[BUG] Force close - Sndcpy

### ISSUE THREAD

**Issue by thoiruddin** [srevinsaju/guiscrcpy#221]
**Describe the bug**
The application close and not detect when try to manually select sndcpy file in Windows 10.

1. sndcpy <- If select this one, will be force close.
2. sndcpy.bat <- If select this one, program not responding.

Which files should we select, number 1 or number 2?

**Comment by thoiruddin** [comment]
I just got the bug from the command line.

Traceback (most recent call last):
  File "guiscrcpy\launcher.py", line 335, in launch_usb_audio
  File "guiscrcpy\lib\bridge\audio\sndcpy.py", line 17, in run
  File "guiscrcpy\lib\utils.py", line 174, in open_process
  File "subprocess.py", line 947, in __init__
  File "subprocess.py", line 1416, in _execute_child
OSError: [WinError 193] %1 is not a valid Win32 application

I'm using both guiscrcpy-4.9.0-PyQt5-x64.exe and guiscrcpy-4.9.0-PySide2-x64.exe.

**Comment by srevinsaju** [comment]
Try removing `C:/Users/<username>/AppData/guiscrcpy/guiscrcpy.json` and try again

**Comment by thoiruddin** [comment]
Done do that, but still auto force close. May I know, which files for Sndcpy should I put if I click the Audio button?

sndcpy or sndcpy.bat?

**Comment by srevinsaju** [comment]
`sndcpy`, not `sndcpy.bat` iirc

**Comment by thoiruddin** [comment]
Okay, seem like it's not working for me to set the path for sndcpy. Auto close again. Already clear the json files, still the same.

**Comment by srevinsaju** [comment]
Does running `sndcpy` from your command prompt work? 

i.e from any directory, basically, is `sndcpy` added to your PATH?

**Comment by thoiruddin** [comment]
If I'm using directly from sndcpy, command prompt provided by them, it's work and I always use it standalone since guiscrcpy not detect my audio sound. 

No, there is no path added inside json files. Do you want me to put it manually? Please let me know the code.

**Comment by srevinsaju** [comment]
No, not in the `json` files, @thoiruddin , sndcpy's directory should be added to PATH in the Windows environment variables. https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/

**Comment by thoiruddin** [comment]
Hi,

Thanks for the guide. I have followed the guide and add 2 folders (I suppose to PATH the folder right?). One is usbaudio and another one is sndcpy and then restart my computer.

The problem come after I click AUDIO Icon and it's showing NOT RESPONDING. I'm using the latest version 4.10 / guiscrcpy-PyQt5-x64.exe. I also clean the json file and try to reset using Reset button.
