### ISSUE TITLE
[BUG] main guiscrcpy screen mirroring window not showing

### ISSUE THREAD

**Issue by scropion86** [srevinsaju/guiscrcpy#222]
**Describe the bug** and **To Reproduce**

after launching guiscrcpy-4.9.0-PyQt5-x64 and clearly see the connected android device
after clicking the start scrcpy the CMD windows will will show "crcpy launched in 0.XX s"
and the bottom panel and swipe panel appears but not the main mirroring screen

if i used the default scrcpy it work as expected

**Expected behavior**

to see the main mirroring screen and the enabled panels

**Screenshots**
guiscrcpy scrrenshoot

![guiscrcpy](https://user-images.githubusercontent.com/5569470/108996212-28c0a400-76af-11eb-845f-243828fd7d6c.jpg)

scrcpy screenshoot

![scrcpy](https://user-images.githubusercontent.com/5569470/108996388-5b6a9c80-76af-11eb-816c-4759560a9529.jpg)

**Desktop (please complete the following information):**
* [ ] Windows 10 Pro 20H2
- **Architecture**: 64-bit
- **Version**: OS build: 19042.804 - Windows Feature Experience Pack 120.2212.551.0

**Additional context**

scrcpy-win64-v1.17
guiscrcpy-4.9.0-PyQt5-x64

**Comment by srevinsaju** [comment]
Restarting your device might help, if not, try:

```bash
GUISCRCPY_DEBUG=true ./guiscrcpy.exe
```
on a command prompt / power shell window in the folder you have shown, and then upload the results.

**Comment by scropion86** [comment]
The guiscrcpy-4.9.0-PyQt5-x64.exe file don't support the provided command ,below is the list supported by exe and i can't find
any debug enable mode



```
D:\scrcpy-win64-v1.17>guiscrcpy-4.9.0-PyQt5-x64 --help
No conda env active, defaulting to base
Usage: guiscrcpy-4.9.0-PyQt5-x64 [OPTIONS] COMMAND [ARGS]...

  guiscrcpy: Graphical user interface for scrcpy

Options:
  --version
  --license, --lic
  -T, --theme TEXT                Set the default theme (based on PyQt5 themes
                                  - Fusion, Breeze, Windows) (stored in
                                  configuration, override by --theme-no-cfg)

  -W, --hide-wm-frame / --show-wm-frame
                                  Show window manager border frame.
  --debug-disable-scrcpy          Do not launch scrcpy even when 'Start
                                  Scrcpy' is pressed

  -A, --always-on-top / --disable-always-on-top
                                  Forces the panels to be always of top
  --help                          Show this message and exit.

Commands:
  adb        Create an interface with the Android Debugging bridge
  config     View / Edit the configuration file
  fast-init  Init scrcpy before guiscrcpy
  mapper     Run the guiscrcpy mapper
  scrcpy     Create an interface with scrcpy

```

**Comment by srevinsaju** [comment]
You have to prefix the command, not postfix


```bash
D:\scrcpy-win64-v1.17>GUISCRCPY_DEBUG=true guiscrcpy-4.9.0-PyQt5-x64 
```

**Comment by scropion86** [comment]
i have tried this already before responding so i tried the help to see the supported commands , it is not working

```
D:\scrcpy-win64-v1.17>GUISCRCPY_DEBUG=true guiscrcpy-4.9.0-PyQt5-x64.exe
'GUISCRCPY_DEBUG' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by srevinsaju** [comment]
ok, once again after deleting the `guiscrcpy.json` file, then.. do

```batch
set GUISCRCPY_DEBUG=true
.\guiscrcpy-4.9.0-PyQt5-x64.exe
```

**Comment by scropion86** [comment]
after trying this here is the Log , and the main mirrored window for the android device is not appearing

```
D:/scrcpy-win64-v1.17/scrcpy.exe
Options received by class are : 8000 None False False False
SCRCPY RUNNING
[{'identifier': 'b0ec6caa', 'status': 'device', 'product': 'OnePlus8T_IND', 'model': 'KB2001', 'device': 'OnePlus8T', 'transport_id': '1'}]
Pairing status: False
[{'identifier': 'b0ec6caa', 'status': 'device', 'product': 'OnePlus8T_IND', 'model': 'KB2001', 'device': 'OnePlus8T', 'transport_id': '1'}]
pairfilter: 1
Pairing status: True
DEVICE LIST 1 [{'identifier': 'b0ec6caa', 'status': 'device', 'product': 'OnePlus8T_IND', 'model': 'KB2001', 'device': 'OnePlus8T', 'transport_id': '1'}]
CONNECTION ESTABLISHED
Flags passed to scrcpy engine :   -b 8000K
Device connection completed successfully.
Private message box updated successfully
scrcpy launched in 0.21s
```

**Comment by srevinsaju** [comment]
Perhaps this is fixed in 4.10.0. Can you test that out?

**Comment by mikenik4** [comment]
Just tried out 4.10.0 and had the same issue

**Comment by scropion86** [comment]
same issue on 4.10.0

**Comment by srevinsaju** [comment]
Can you try checking it in Task Manager, in Windows, if `scrcpy` process is running?

**Comment by utsavbalhara** [comment]
> Can you try checking it in Task Manager, in Windows, if `scrcpy` process is running?
I have the excat issue.
Checked in Task Manager `scrcpy` is not running

**Comment by utsavbalhara** [comment]
I have the exact issue.
Checked in Task Manager, `scrcpy` is not running.

> Can you try checking it in Task Manager, in Windows, if `scrcpy` process is running?

**Comment by srevinsaju** [comment]
Can you send me your `guiscrcpy.json` from `C:/AppData/Local/guiscrcpy`?

I wonder why this always happens with windows only :face_with_head_bandage:

**Comment by scropion86** [comment]
> Can you send me your `guiscrcpy.json` from `C:/AppData/Local/guiscrcpy`?
> 
> I wonder why this always happens with windows only 🤕

Here is the json file 

```
{
    "adb": ".\\adb.EXE",
    "bitrate": 8000,
    "cmx": "",
    "device": {},
    "dimension": null,
    "dispRO": false,
    "extra": "",
    "fullscreen": false,
    "mapper": "",
    "panels": {
        "bottom": true,
        "swipe": true,
        "toolkit": true
    },
    "paths": [
        "bin"
    ],
    "scrcpy": ".\\scrcpy.EXE",
    "scrcpy-server": "D:/scrcpy-win64-v1.17/scrcpy.exe",
    "sha_shift": 5,
    "swtouches": false,
    "theme": "Breeze",
    "version": 1
}
```

**Comment by srevinsaju** [comment]
Ah, makes sense:

The `scrcpy-server` was wrongly set. 

Replacing that file with the contents from the following block might fix that bug.
```json
{
    "adb": ".\\adb.EXE",
    "bitrate": 8000,
    "cmx": "",
    "device": {},
    "dimension": null,
    "dispRO": false,
    "extra": "",
    "fullscreen": false,
    "mapper": "",
    "panels": {
        "bottom": true,
        "swipe": true,
        "toolkit": true
    },
    "paths": [
        "bin"
    ],
    "scrcpy": "D:/scrcpy-win64-v1.17/scrcpy.exe",
    "scrcpy-server": "D:/scrcpy-win64-v1.17/scrcpy-server",
    "sha_shift": 5,
    "swtouches": false,
    "theme": "Breeze",
    "version": 1
}
```

**Comment by scropion86** [comment]
> Ah, makes sense:
> 
> The `scrcpy-server` was wrongly set.
> 
> Replacing that file with the contents from the following block might fix that bug.
> 
> ```json
> {
>     "adb": ".\\adb.EXE",
>     "bitrate": 8000,
>     "cmx": "",
>     "device": {},
>     "dimension": null,
>     "dispRO": false,
>     "extra": "",
>     "fullscreen": false,
>     "mapper": "",
>     "panels": {
>         "bottom": true,
>         "swipe": true,
>         "toolkit": true
>     },
>     "paths": [
>         "bin"
>     ],
>     "scrcpy": "D:/scrcpy-win64-v1.17/scrcpy.exe",
>     "scrcpy-server": "D:/scrcpy-win64-v1.17/scrcpy-server",
>     "sha_shift": 5,
>     "swtouches": false,
>     "theme": "Breeze",
>     "version": 1
> }
> ```

after trying the json provided by you ,  can confirm the app start working as it used to work before.

**Comment by srevinsaju** [comment]
Closing this issue, feel free to open another if you face any other problems.

**Comment by scropion86** [comment]
> Closing this issue, feel free to open another if you face any other problems.

have you fixed the issue in the new release ?
so automatically the json file will store the correct full path for scrcpy.exe
as it will keep happeneing to other users since the `guiscrcpy.json` is auto generated by the guiscrcpy application.
