### ISSUE TITLE
[BUG] Mapper initialized, but not working?

### ISSUE THREAD

**Issue by ImNotEnd** [srevinsaju/guiscrcpy#223]
I'm initializing the mapper from the GUI menu, but I don't see any way to map buttons to the screen.

**Comment by tjssoldier** [comment]
I have the same problem on Linux

**Comment by srevinsaju** [comment]
Which version of guiscrcpy?

**Comment by srevinsaju** [comment]
Can you send any associated error messages, warnings? Did you follow the mapper setup-guide?

![image](https://user-images.githubusercontent.com/48695438/111824185-ec234980-88f6-11eb-9afc-8a6d055856a2.png)

Pressing the :rocket: button should start an interactive wizard to set up the mapper.

**Comment by srevinsaju** [comment]
Closing this, and marking as stale. Feel free to reopen this issue.

**Comment by jwaxy** [comment]
I have the same issue it initializes and listens for the keys but it doesnt open a mapping wizard.
