### ISSUE TITLE
[FR] Display hidden files on Windows in the explorer on startup

### ISSUE THREAD

**Issue by MrOrigan** [srevinsaju/guiscrcpy#226]
****
When starting up guiscrcpy for the first time, scrcpy itself needs to be selected via a built in explorer.
But the explorer does not display hidden folders like "ProgramData" on the C:\ Drive.

This is a problem if you have installed scrcpy via chocolatey [https://chocolatey.org/packages/scrcpy](https://chocolatey.org/packages/scrcpy) because by default is it placed under C:\ProgramData\chocolatey\bin and cannot be selected via the build in explorer.

**Describe the solution you'd like**
I would like to suggest that hidden folder are displayed or a check box to display them in case scrcpy is located in a path where there is a hidden folder in its way.

**Workaround**
A Workaround is to create a link to the hidden scrcpy location and place it in a non hidden path. Then the link can be selected and guiscrcpy can be used.

**Comment by srevinsaju** [comment]
Hmm, you are right. I will try to find a fix for the file chooser to show hidden files by default. Thanks for letting me know

**Comment by srevinsaju** [comment]
@MrOrigan fixed in #228 , `continuous` builds will be out any minute.

**Comment by MrOrigan** [comment]
@srevinsaju WoW, impressive speed. Thank you very much

**Comment by srevinsaju** [comment]
@MrOrigan Thanks :heart: , the compiled EXE is now available here https://github.com/srevinsaju/guiscrcpy/releases/tag/continuous
