### ISSUE TITLE
Flatpak package format

### ISSUE THREAD

**Issue by realgrm** [srevinsaju/guiscrcpy#232]
This is a request for distribute this app in flatpak format.
Do you have any plans on doing this? If not, can someone help doing?
This is issue is being linked in https://discourse.flathub.org/t/guiscrcpy-android-screen-mirroring-gui-for-scrcpy/1269 for someone that may be interested to help.

**Comment by srevinsaju** [comment]
Awesome, guiscrcpy as a flatpak would be cool! 

If someone can help me maintaining the flatpak, it would be very helpful. :smile: 
I can provide all the help required for the same,

**Comment by realgrm** [comment]
Thanks. We appreciate.

For someone that wants to help:
As stated in [discourse.flathub.org - scrcpy (CLI)](https://discourse.flathub.org/t/scrcpy-screen-mirroring-android/1268/2), there is some work done for scrcpy (CLI) in https://github.com/nexustar/scrcpy-flatpak with the PR [https://github.com/flathub/flathub/pull/1551 ](https://github.com/flathub/flathub/pull/1551), maybe it will help.

**Comment by srevinsaju** [comment]
@realgrm https://github.com/flathub/flathub/pull/2652#issuecomment-976242563

**Comment by srevinsaju** [comment]
https://flathub.org/apps/details/in.srev.guiscrcpy
