### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by C8forT** [srevinsaju/guiscrcpy#233]
Guiscrcpy App Image version 4.10.0

**Describe the bug**
In sum, I have to re-connect my phone via a USB cable each time I re-open guiscrcpy, even though I am able to connect to my phone using guiscrcpy's Network Manager without the USB cable.

I am able to connect to my phone using guiscrcpy's Network Manager, but the phone does not show up in the list view, even after I have connected to it in the Network Manager.  If I select "START SCRCPY" I receive a notification "Please select a device from the list view," but the list view is blank.

If I connect the phone via a USB cable, then the phone shows up in the list view and I am able to disconnect the USB cable.  It then works fine so long as I do not close guiscrcpy.  If I close guiscrcpy, then restart it some time later, the phone again does not show up in the list view, even after connecting to it in the Network Manager.  I then have to again connect via the USB cable.

The following terminal commands output the following:

$ adb devices
List of devices attached
192.168.137.208:5555    device

$ guiscrcpy.adb devices -l
bash: guiscrcpy.adb: command not found

Thus, the issue appears to be with the guiscrcpy.adb command not being recognized.  

Is there a link that needs to be created to resolve this issue?  If so, could you provide the appropriate terminal command?

**To Reproduce**

1. Open 'Network Manager' using the network icon in guiscrcpy
2. In the 'Network Manager' click on 'REFRESH'
3. My phone's IP Address shows up in the Network Manager's 'List of Network Devices' and I select it, then I select 'CONNECT'
4. Message appears 'Connected to IP:192.168.137.208:5555'
5. Close Network Manager
6. guiscrcpy's list view is blank 
7. Select refresh icon in guiscrcpy
8. guiscrcpy's list view still is blank 

**Expected behavior**
I expect that after connecting to my phone in the Network Manager and receiving the message 'Connected to IP:192.168.137.208:5555' my phone should show up in the list view after closing Network Manager and selecting the refresh icon in guiscrcpy.

**Screenshots**

![Network_Manager](https://user-images.githubusercontent.com/82325210/114310451-cda90c00-9ab8-11eb-8478-0c627a4008fc.png)

![guiscrcpy](https://user-images.githubusercontent.com/82325210/114310472-d7327400-9ab8-11eb-89df-c72d15dc5a8d.png)

**Desktop (please complete the following information):**

* [X] Linux

![neofetch](https://user-images.githubusercontent.com/82325210/114310486-e0234580-9ab8-11eb-8e99-060e06362c84.png)

**Additional context**

I have also tried the snap package of guiscrcpy and guiscrcpy from the AUR, but those currently do not work on my Arch system.  The snap package used to work, up until about a few weeks ago after I uninstalled and reinstalled snapd while trouble shooting another snap package.  I presumed the issue may be with snapd, which is why I am currently trying to get the app image to work.

The guiscrcpy app image is in my Home directory in a folder named .AppImages.  Does the app image need to be executed from a different directory in the system?

The permissions for the app image currently are set for Owner 'Can View & Modify' but Group and Others are set to 'Can Only View'.  I have tried changing Group and Others to 'Can View & Modify' but this did not solve the issue.

![Permissions](https://user-images.githubusercontent.com/82325210/114311902-a48b7a00-9abe-11eb-9132-059ecae7d24f.png)

**Comment by C8forT** [comment]
Further context:  

The guiscrcpy app image is in my Home directory in a folder named .AppImages.  Does the app image need to be executed from a different folder in the system?

The permissions for the app image currently are set for Owner 'Can View & Modify' but Group and Others are set to 'Can Only View'.  I have tried changing Group and Others to 'Can View & Modify' but this did not solve the issue.

**Comment by srevinsaju** [comment]
After connecting using Network Manager, and once you get "Connected to IP: XX.XX.XX.XXX", can you restart guiscrcpy from the appimage, and see if your device is being detected now?

I hope you are not using anything like sandboxing.

```bash
 guiscrcpy.adb devices -l
 ```
 
 this is only applicable for snaps, in appimages, it wont work

**Comment by C8forT** [comment]
Thank you!!!

It did not work the first time, but I tried two more times and it finally worked!!!

You are awesome!!!

**Comment by C8forT** [comment]
srevinsaju's recommendation worked.  I was closing guiscrcpy using the 'x' close button on the upper right corner of the window.  But closing guiscrcpy using the orange icon, with the 'x' inside the white circle, worked to save my settings after a few tries.
