### ISSUE TITLE
[BUG] Unable to connect wirelessly after update to lineage 18 / Android 11

### ISSUE THREAD

**Issue by DillonMenefee** [srevinsaju/guiscrcpy#235]
**Describe the bug**
Wireless (TCPIP) connections no longer work after upgrading to Android 11 / Lineage 18. 

**To Reproduce**
1. Attempt to connect via 'abd pair ipaddr:port' (where the ipaddr and port are the details provide by the android device in the wireless debug menu). 
2. Resutls was an error to start pairng client
2. Attempt to connect via guiscrcpy with manual entering IP address of device and the port number provided in the wireless debug menu
3. Results in guiscrcpy crashing
4. Repeat step 4 but used port 5555
5. Results in guiscrcpy crashing

**Expected behavior**
Connecting / pairing the device with the guiscrcpy software. 

**Desktop (please complete the following information):**

OS: Ubuntu 20.04.2 LTS x86_64 
Host: Surface Pro 7 124I:00046T:000 
Kernel: 5.11.18-surface 
Uptime: 20 hours, 58 mins 
Packages: 2151 (dpkg), 8 (snap) 
Shell: bash 5.0.17 
Resolution: 3648x2432, 5120x2160 
DE: GNOME 
WM: Mutter 
WM Theme: Adwaita 
Theme: Yaru-dark [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-1035G4 (8) @ 3.700GHz 
GPU: Intel Device 8a5a 
Memory: 6066MiB / 7548MiB

**Comment by srevinsaju** [comment]
Try 
```bash
adb connect ipaddr:port
adb devices
```

Let me know what is the output.
