### ISSUE TITLE
Device not detected

### ISSUE THREAD

**Issue by giTran-s** [srevinsaju/guiscrcpy#238]
Hi, I've installed the latest AppImage  guiscrcpy-.dev.r.glibc2.27-x86_64.AppImage
My phone and desktop are on the same network, I even plugged the phone to the computer but the app say: "Couldn't find any devices".
Thanks for the help

**Comment by giTran-s** [comment]
Linux Mint Cinammon 20.1 and Moto G plus 5 android 8.1

**Comment by srevinsaju** [comment]
Did you try restarting `guiscrcpy`?

**Comment by giTran-s** [comment]
Yes I did, restarted everything: guiscrcpy, computer and phone. scrcpy works though... any idea? thanks

**Comment by srevinsaju** [comment]
You will probably have to open the network manager, and do a network scan. See [this](https://github.com/srevinsaju/guiscrcpy/blob/master/docs/FEATURES.md#network-management) page for more instructions on how to do it.

**Comment by giTran-s** [comment]
The network scan refresh gives no results. Trying to enter my IP address manually = no results.
thanks for your help

**Comment by srevinsaju** [comment]
It's the IP address of the mobile, not your computer's IP address :thinking:

**Comment by srevinsaju** [comment]
I am closing this for now, feel free to reopen.
