### ISSUE TITLE
permissions

### ISSUE THREAD

**Issue by xbfrog** [srevinsaju/guiscrcpy#244]
after reinstalling Ubuntu i installed guiscrcpy from snap in Ubuntu software  it worked great for several months. now for some unknown reason it stopped. i could not uninstall from the software manager cause it didn't show it as installed. and the software manager search for it showed no app by that name. so i uninstalled it from the cli, and reinstalled it the same way. i cannot access any "details" cause the software manager says sorry! there are no details for that application. what i see on screen is scrcpy server is not running. is there another way to turn it on?

**Comment by srevinsaju** [comment]
Can you send me any screenshots or system information demonstrating the problem? I quite didnt understand what your issue is :thinking:

**Comment by xbfrog** [comment]
here are two screenshots
![scrcpy not running](https://user-images.githubusercontent.com/59119517/121759134-273daf00-cad9-11eb-94e1-e6b067401ab5.png)
![no devices found](https://user-images.githubusercontent.com/59119517/121759145-315fad80-cad9-11eb-8f0d-54b66bed2702.png)

**Comment by srevinsaju** [comment]
I think you should try using the AppImage from the [releases](https://github.com/srevinsaju/guiscrcpy/releases).
