### ISSUE TITLE
Crash while activating audio

### ISSUE THREAD

**Issue by mrfoxie** [srevinsaju/guiscrcpy#248]
Crash while activating audio, I also downloaded usbaudio but when it tried to active the button it gave me this error.

**Desktop (please complete the following information):**
* [x] Windows
- **Architecture**: 64-bit
- **Version**: 11

![image](https://user-images.githubusercontent.com/25217451/126066085-7daa9f50-f5e6-4d43-b428-f58b9a7d341e.png)

```
guiscrcpy v4.10.0
by @srevinsaju
https://github.com/srevinsaju/guiscrcpy


scrcpy launched in 1.20s
Traceback (most recent call last):
  File "guiscrcpy\launcher.py", line 328, in launch_usb_audio
  File "guiscrcpy\lib\bridge\adb.py", line 18, in get_target_android_version
ValueError: invalid literal for int() with base 10: '8.1.0\r\n'
```

**Comment by srevinsaju** [comment]
oh, Interesting. What is your android device version? Oreo?

**Comment by mrfoxie** [comment]
yes

**Comment by srevinsaju** [comment]
Attempted a fix in dd301d0, builds will complete in 2 minutes. Will let you know when an update build is available

**Comment by mrfoxie** [comment]
ok thank you i will be waiting for it

**Comment by srevinsaju** [comment]
https://github.com/srevinsaju/guiscrcpy/releases/tag/continuous

**Comment by mrfoxie** [comment]
well usbaudio is not supporting windows so it's useless for me and also sndcpy is used for android 10.0
