### ISSUE TITLE
Not launching

### ISSUE THREAD

**Issue by arnauldb** [srevinsaju/guiscrcpy#25]
Hello,

On Linux Mint Sylvia 18.3, with scrcpy installed & working and guiscrcpy v2.0 successfully installed with no errors with `python3 -m pip install guiscrcpy --user`.

I can see the guiscrcpy launcher, but it doesn't launch anything. When I do `guiscrcpy` I obtain this:

> guiscrcpy
> /usr/local/bin/python3: can't find '__main__' module in '/home/arnauld/.local/share/guiscrcpy/guiscrcpy'

Thank you.

**Comment by srevinsaju** [comment]
Does running `guiscrcpy` in terminal run `guiscrcpy`

**Comment by srevinsaju** [comment]
Try 
```
import guiscrcpy
guiscrcpy.__path__
```
Alternatively try 

`python3 -m pip install guiscrcpy` without the `--user` flag

**Comment by srevinsaju** [comment]
@arnauldb is it fixed?

**Comment by arnauldb** [comment]
Hello @srevinsaju 

Sorry for the late reply.
I just tried `$ python3 -m guiscrcpy` and it works fine. For my system (Linux Mint 18.3 Sylvia) it is the only way to launch Guiscrcpy. Clicking the icon doesn't work...

Thank you.

**Comment by srevinsaju** [comment]
@arnauldb thanks for the reply. Its an error in the desktop shortcut created with `pyshortcuts`, the code was not working, so I have to independently work on that. I will  work on that , thanks for the feedback.

**Comment by arnauldb** [comment]
Thks for your work. I just installed version 3 and the launcher (icon) works for that version on my system.

**Comment by srevinsaju** [comment]
Yup, I fiexed that. Thanks for you interest in guiscrcpy. Hope you like v3.0
