### ISSUE TITLE
[BUG] Its not a bug but error in display and now the app crash

### ISSUE THREAD

**Issue by zuzuca** [srevinsaju/guiscrcpy#255]
**Describe the bug**
nothing showing in display but the mapper its works..
and now i enter i get error 

**To Reproduce**
1. Go to guiscrcpy 
2 See error

![Screenshot_3](https://user-images.githubusercontent.com/89316293/130335365-562fa8f7-40a3-45d4-83a5-249cd77666ef.png)

**Expected behavior**
i dont know what happened now not even entering the program

**Screenshots**

**Desktop (please complete the following information):**
* [ ] Linux garuda dragonite
- **Architecture**: / 64-bit
- **Version**: dragonite 

* [ ] Linux

![Screenshot_6](https://user-images.githubusercontent.com/89316293/130335270-9eaef7c5-6e93-4330-9bfe-2c3bbea2e578.png)

**Additional context**
First i have a problem with the display, it didn't appear but the mapper was ok, i tried to fix but i large the problem xDD

**Comment by zuzuca** [comment]
guiscrcpy v4.10.0
by @srevinsaju
https://github.com/srevinsaju/guiscrcpy


Icon theme "adwaita" not found.
Icon theme "ubuntu-mono" not found.
Icon theme "yaru" not found.
Icon theme "Mint-X" not found.
Icon theme "elementary" not found.
scrcpy launched in 0.17s
INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 440.8 MB/s (37330 bytes in 0.000s)
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  151 (GLX)
Minor opcode of failed request:  3 (X_GLXCreateContext)
Value in failed request:  0x0
Serial number of failed request:  105
Current serial number in output stream:  106
[server] INFO: Device: samsung SM-A217M (Android 11)

**Comment by srevinsaju** [comment]
that's because you have two different versions of guiscrcpy, which wasn't compatible with each other..


to fix it, open a terminal and type 
```bash
rm -r ~/.config/guiscrcpy
```

**Comment by srevinsaju** [comment]
```
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 440.8 MB/s (37330 bytes in 0.000s)
X Error of failed request: BadValue (integer parameter out of range for operation)
Major opcode of failed request: 151 (GLX)
Minor opcode of failed request: 3 (X_GLXCreateContext)
Value in failed request: 0x0
Serial number of failed request: 105
Current serial number in output stream: 106
[server] INFO: Device: samsung SM-A217M (Android 11)
```

i haven't tested your Linux yet, let me see why scrcpy doesn't start.. thanks for reporting..

**Comment by zuzuca** [comment]
![Screenshot_8](https://user-images.githubusercontent.com/89316293/130336283-640984f2-3730-47f0-a3a1-6f4048d370e5.png)

**Comment by zuzuca** [comment]
now start ok but i cant see the pone

**Comment by zuzuca** [comment]
guiscrcpy v4.10.0
by @srevinsaju
https://github.com/srevinsaju/guiscrcpy


Icon theme "adwaita" not found.
Icon theme "ubuntu-mono" not found.
Icon theme "yaru" not found.
Icon theme "Mint-X" not found.
Icon theme "elementary" not found.
scrcpy launched in 0.17s
INFO: scrcpy 1.18 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 390.9 MB/s (37330 bytes in 0.000s)
bind: Address already in use
WARN: Could not listen on port 27183, retrying on 27184
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  151 (GLX)
Minor opcode of failed request:  3 (X_GLXCreateContext)
Value in failed request:  0x0
Serial number of failed request:  105
Current serial number in output stream:  106
[server] INFO: Device: samsung SM-A217M (Android 11)

**Comment by zuzuca** [comment]
OpenGL?

**Comment by srevinsaju** [comment]
Yea, look like some OpenGL driver problem

**Comment by srevinsaju** [comment]
ok.... do this.. it might work for u:
* remove all the other versions of guiscrcpy
* do `rm -r ~/.config/guiscrcpy`
* open pamac, and install guiscrcpy from AUR

**Comment by zuzuca** [comment]
3 aur/guiscrcpy-git 4.9.0.r1221.gd681dd3-1 [+3 ~0.00]
Open Source GUI based Android Screen Mirroring System
2 chaotic-aur/guiscrcpy-git 4.10.0.r1242.gdd301d0-1 [0B 20.84MiB]
Open Source GUI based Android Screen Mirroring System
1 aur/guiscrcpy 4.10.0-1 [+13 ~0.16]
Open Source GUI based Android Screen Mirroring System


wich of these?

**Comment by zuzuca** [comment]
1 aur/guiscrcpy 4.10.0-1 [+13 ~0.16]
Open Source GUI based Android Screen Mirroring System not working

**Comment by zuzuca** [comment]
i installed from the apps launcher

**Comment by zuzuca** [comment]
![Screenshot_9](https://user-images.githubusercontent.com/89316293/130383220-42b5bde5-8190-4bc4-9750-f8d3a4918132.png)
its fixed now you can close. 
Installing all again is the solution
