### ISSUE TITLE
It wont find my device[BUG]

### ISSUE THREAD

**Issue by Kurodoku** [srevinsaju/guiscrcpy#256]
I am downloaded using the .exe from the4.10.00 build with the 1.8 scrcpy and a Xiaomi MiA1
I had just found scrcpy couple hours ago and downloaded it
I wanted to find a way to map keys and found guiscrcpy
when I finished downloading I run it and it said it didn't find any devices even though I have my phone plugged in so I tried the wireless solution when I tried connecting the app just stopped working
I have no prior knowledge on scrcpy
other types of scrcpy work fine with no problems just guiscrcpy
I haven't tried using other cables yet

screenshots:
![image](https://user-images.githubusercontent.com/89916392/131673328-3d716c20-ce1b-41b9-8c3d-b8390e436f33.png)

is this a bug on my part or is it me not understanding how it works?

update : so it somehow broke
![image](https://user-images.githubusercontent.com/89916392/131693819-ce02f1c6-f304-4529-ab2e-f2c4e3cb56bd.png)

im going to try downloading it by the PyPI
i dont know how to run it ill try figuring it out later
but i found something interesting i tried downloading an old version and it had noproblems while the newer one broke

**Comment by Kurodoku** [comment]
[guiscrcpy.zip](https://github.com/srevinsaju/guiscrcpy/files/7097390/guiscrcpy.zip)
 there it is

**Comment by srevinsaju** [comment]
Are you sure this path exists? `C:/Users/Tigger/Desktop/scrcpy/adb.exe` 

Can you send me the output of 
```bat
C:/Users/Tigger/Desktop/scrcpy/adb.exe devices -l
```

**Comment by Kurodoku** [comment]
the path doesnt exist anymore i moved the folder to another place

**Comment by srevinsaju** [comment]
Yes, makes sense. That's why guiscrcpy is failing. The solution is, to remove that file which you sent me [here](https://github.com/srevinsaju/guiscrcpy/issues/256#issuecomment-911387426), and then, guiscrcpy will ask you for the new location.

**Comment by Kurodoku** [comment]
oh ok ill try that

**Comment by Kurodoku** [comment]
Oh it finally detected it thanks for the help

**Comment by Kurodoku** [comment]
ok now i have a new problem :(

**Comment by srevinsaju** [comment]
What is the problem?

**Comment by Kurodoku** [comment]
when i try tp start scrcpy it tries to connect till it reaches 80% then closes

**Comment by srevinsaju** [comment]
Any logs in the command prompt window?

**Comment by Kurodoku** [comment]
here 
![image](https://user-images.githubusercontent.com/89916392/131822831-f00be802-3519-4fb8-b31d-5d4c26fd0e93.png)

**Comment by srevinsaju** [comment]
Can you send that configuration json file from AppData (the one u sent earlier, but the newer version of it again?)

**Comment by srevinsaju** [comment]
Can you close guiscrcpy, replace the `guiscrcpy.json` with the following contents, and start again?
```json
{
    "adb": "C:/Users/Tigger/Desktop/scrcpy/adb.exe",
    "bitrate": 8000,
    "cmx": "",
    "device": {},
    "dimension": null,
    "dispRO": false,
    "extra": "",
    "fullscreen": false,
    "mapper": "",
    "panels": {
        "bottom": true,
        "swipe": true,
        "toolkit": true
    },
    "paths": [
        "bin"
    ],
    "scrcpy": "C:/Users/Tigger/Desktop/scrcpy/scrcpy.exe",
    "scrcpy-server": "C:/Users/Tigger/Desktop/scrcpy/scrcpy-server",
    "sha_shift": 5,
    "swtouches": false,
    "theme": "Breeze",
    "version": 1
}
```

You selected the wrong item for scrcpy-server, and scrcpy.... basically, you swapped both of them

**Comment by Kurodoku** [comment]
so what is the order ?

**Comment by srevinsaju** [comment]
When `guiscrcpy` asks you for scrcpy-server, you need to select scrcpy-server, when it asks you for scrcpy, u need to select scrcpy.exe `¯\_(ツ)_/¯`
