### ISSUE TITLE
[BUG] guiscrcpy cannot start after upgrade to version 4.10.0-1

### ISSUE THREAD

**Issue by MioMil** [srevinsaju/guiscrcpy#263]
**Describe the bug**
guiscrcpy cannot start after upgrade to version 4.10.0-1

**To Reproduce**
1. Upgrade to version 4.10.0-1
2. Run guiscrcpy
3. See screenshot

**Expected behavior**
guiscrcpy runs without any error from start.

**Screenshots**
![image](https://user-images.githubusercontent.com/2685305/136601820-98765d6d-7df3-4f40-8a63-dfc79a0d1936.png)

**Desktop:**
* [ ] Linux
- **OS**: Arch Linux x86_64
- **Kernel**: 5.14.9-arch2-1
- **DE**: Plasma 5.22.5

**Comment by srevinsaju** [comment]
Do `guiscrcpy config -r` and restart guiscrcpy.

**Comment by MioMil** [comment]
Problem solved. Thank you!
