### ISSUE TITLE
I can't start!

### ISSUE THREAD

**Issue by fanmli** [srevinsaju/guiscrcpy#27]
I can't start!
Windows 10 system has installed scrcpy and will successfully connect the phone, boot without any reaction, there is hope that the author compiles an EXE version, thank you for your efforts!
`https://i.loli.net/2019/11/08/nRCLBS1MIzJ5Qcr.png`
`https://i.loli.net/2019/11/08/tTNjqmE3dOrvPQD.png`

**Comment by srevinsaju** [comment]
Hey there, 

Thanks for contacting me for this issue.

The correct way to run guiscrcpy is :

```
> guiscrcpy

OR (if it doesn't work)

python3 -m guiscrcpy
```

**Comment by fanmli** [comment]
> 嘿，
> 
> 感谢您与我这个问题。
> 
> 运行guiscrcpy正确的方法是：
> 
> ```
> > guiscrcpy
> 
> OR (if it doesn't work)
> 
> python -m guiscrcpy
> ```
> 
> 希望它的作品！
> 如果第一个不能正常工作，考虑将其添加到路径，该目录将给予您何时安装PIP包
> 要手动获取DIR
> 
> ```
> Enter python
> 
> >>> import guiscrcpy
> >>> guiscrcpy.__path__
> ```
> 
> _从我的银河注2使用发送[FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
Still can't start! There is no problem with having guiscrcpy v11.2 installed before, and the trouble author is wrong to see if that step is wrong.
`https://ae01.alicdn.com/kf/Hb727a8b487be4172917462b81359a956p.png`
`https://ae01.alicdn.com/kf/H99f9d6d6a7ba4752947fd6ac94ebfe2eT.png`
`https://ae01.alicdn.com/kf/H0976597d94d0459498af384f18dc9bf6A.png`
`https://ae01.alicdn.com/kf/H4317d0c2f7f44e55a1aedd9b3d1387a62.png`

**Comment by srevinsaju** [comment]
No, it's not in python interpreter, do it in the command prompt
The same command run it on the command prompt console. It should work now

**Comment by fanmli** [comment]
> 不，它不是在Python解释器，这样做在命令提示符下
> 同样的命令在命令提示符控制台上运行它。现在应该工作

I can't use it in the command prompt before Trying the Python interpreter.
`https://ae01.alicdn.com/kf/Hf673cc044aca4252ad714cddfee0eda77.png`

**Comment by srevinsaju** [comment]
Don't type python in front of guiscrcpy

Try 

```
>>> guiscrcpy

OR

>>> python -m guiscrcpy
```

**Comment by srevinsaju** [comment]
Hope the issue is fixed
