### ISSUE TITLE
Potentially wrong links in README

### ISSUE THREAD

**Issue by gouravkhunger** [srevinsaju/guiscrcpy#273]
Hey!
I was going through the [README](https://github.com/srevinsaju/guiscrcpy/blob/main/README.md) and found that the links for reporting bug or for feature request point to another repository's issue page([zap](https://github.com/srevinsaju/zap)) instead of this one.

For some reason code preview didn't render for README, so including hyperlinks to the lines numbers:

[Line number 9](https://github.com/srevinsaju/guiscrcpy/blob/main/README.md?plain=1#L9)
[Line number 11](https://github.com/srevinsaju/guiscrcpy/blob/main/README.md?plain=1#L11)

Is it intentional?

**Comment by srevinsaju** [comment]
Oh it was a mistake, would you like to create a PR to fix that?

**Comment by gouravkhunger** [comment]
Done 😄
