### ISSUE TITLE
[BUG] Pip installs version 4.10 on python >= 3.10 with error

### ISSUE THREAD

**Issue by RCristiano** [srevinsaju/guiscrcpy#280]
Describe the bug

When the package is installed with pip on python 3.10, it uses version 4.10, but there is a conversion error when running it.

To Reproduce

    Open guiscrcpy
    Select device
    Click on start

Expected behavior
Opens scrcpy with chosen device

Screenshots

Traceback (most recent call last):
  File "/home/rcristiano/.local/lib/python3.10/site-packages/guiscrcpy/launcher.py", line 926, in start_act
    progress = self.progress(progress)
  File "/home/rcristiano/.local/lib/python3.10/site-packages/guiscrcpy/launcher.py", line 806, in progress
    self.progressBar.setValue(val)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'

Desktop (please complete the following information):

Linux

Distribution: Fedora Linux 35 (Workstation Edition) x86_64
Desktop Environment: GNOME 41.1
Architecture: Intel 64-bit

Additional context
Python: 3.10

**Comment by RCristiano** [comment]
I made a small mistake in #277
The error only occurs when the package is installed with pip in python >= 3.10 because the 4.10 version didn't use poetry yet and didn't have a validation for minimum python version

I will suggest a patch for version 4.10 as it works with the fix

Regarding patch #278, I believe it will be useful in future releases when python >= 3.10 is supported.

**Comment by srevinsaju** [comment]
Released in v4.11.3
