### ISSUE TITLE
ArchLinux: guiscrcpy core dumped on start scrcpy

### ISSUE THREAD

**Issue by GTRONICK** [srevinsaju/guiscrcpy#282]
Using latest version from the AUR.
Clicking on start scrcpy button gives the following error:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/guiscrcpy/launcher.py", line 934, in start_act
    progress = self.progress(progress)
  File "/usr/lib/python3.10/site-packages/guiscrcpy/launcher.py", line 814, in progress
    self.progressBar.setValue(val)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
[1]    44241 abort (core dumped)  guiscrcpy

**Comment by RCristiano** [comment]
Hi!

This issue is fixed in #278, however it is not yet in the latest release.
You can try installing on another version of Python <3.10
Or you can install with another method like Flatpak or appimage.

Hope this helps

**Comment by srevinsaju** [comment]
Since this commit made it to 4.11.3, I will be closing this issue. Feel free to open a new issue if it still exists.
