### ISSUE TITLE
[BUG] OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by Zeyrox1090** [srevinsaju/guiscrcpy#287]
**Describe the bug**

**To Reproduce**
1. Go to guiscrcpy path
2. Click on the exe
3. See error

**Expected behavior**
to see the menu

**Screenshots**
![image](https://user-images.githubusercontent.com/73925046/148034068-25aa7768-2c4b-4f4f-80b3-a7fcb576cc5a.png)

**Desktop (please complete the following information):**
* Windows
- **Architecture**:  64-bit
- **Version**: Example: 11

**Comment by Zeyrox1090** [comment]
fixed but you still need to fix this bug when a directory has space it doesnt work

**Comment by srevinsaju** [comment]
After a year, I think this is fixed now. Please create a new issue if this issue still exists.

**Comment by halilnevzat** [comment]
> After a year, I think this is fixed now. Please create a new issue if this issue still exists.

still exist, i also tried directories without space
