### ISSUE TITLE
[BUG] guiscrcpy won't start - segmentation fault

### ISSUE THREAD

**Issue by serenova** [srevinsaju/guiscrcpy#295]
I cannot get guiscrcpy to start on my computer.

I honestly have NO idea how to recreate this error.

When running "guiscrcpy" in my terminal toopen the app i get the following:
````
[user]:~$ guiscrcpy

guiscrcpy v4.9.0
by @srevinsaju
https://github.com/srevinsaju/guiscrcpy


Fontconfig warning: FcPattern object width does not accept value [75 100)
Segmentation fault (core dumped)

````

I'd honestly expect the app to start when i try to run it. It **also** doesn't when started from my program list.

**My system:**
OS: Kubuntu 21.10 x86_64 
Host: OMEN by HP Laptop 17-cb0xxx 
Kernel: 5.13.0-28-generic 
Uptime: 11 mins 
Packages: 3162 (dpkg), 18 (snap) 
Shell: bash 5.1.8 
Resolution: 3840x2160, 3840x2160 
DE: Plasma 5.22.5 
WM: KWin 
Theme: Breeze Light [Plasma], Breeze [GTK2/3] 
Icons: [Plasma], breeze [GTK2/3] 
Terminal: konsole 
CPU: Intel i9-9880H (16) @ 4.800GHz 
GPU: NVIDIA GeForce RTX 2080 Mobile 
Memory: 3342MiB / 31974MiB                                 

I read through the documentation here and just... could NOT figure out why it won't start. If anyone could help me out I'd appreciate it.

**Comment by srevinsaju** [comment]
How did you install guiscrcpy?

**Comment by srevinsaju** [comment]
Closing this issue as stale / needs more information.
