### ISSUE TITLE
[BUG] Error: Unhandled exception

### ISSUE THREAD

**Issue by ghost** [srevinsaju/guiscrcpy#296]
Hello,

After upgrading guiscrcpy to latest version 4.12.0 `pipx upgrade guiscrcpy` I got errors at launch:

I got those errors at first:
```
Traceback (most recent call last):
  File "/usr/local/bin/guiscrcpy", line 5, in <module>
    from guiscrcpy.cli import cli
  File "/usr/local/lib/venvs/guiscrcpy/lib/python3.9/site-packages/guiscrcpy/cli.py", line 9, in <module>
    from qtpy.QtWidgets import QApplication
  File "/usr/local/lib/venvs/guiscrcpy/lib/python3.9/site-packages/qtpy/QtWidgets.py", line 36, in <module>
    from PyQt5.QtWidgets import *
ModuleNotFoundError: No module named 'PyQt5'
```
```
Traceback (most recent call last):
  File "/usr/local/bin/guiscrcpy", line 5, in <module>
    from guiscrcpy.cli import cli
  File "/usr/local/lib/venvs/guiscrcpy/lib/python3.9/site-packages/guiscrcpy/cli.py", line 13, in <module>
    from .launcher import bootstrap
  File "/usr/local/lib/venvs/guiscrcpy/lib/python3.9/site-packages/guiscrcpy/launcher.py", line 63, in <module>
    from .ux import Ui_MainWindow
  File "/usr/local/lib/venvs/guiscrcpy/lib/python3.9/site-packages/guiscrcpy/ux/__init__.py", line 24, in <module>
    from guiscrcpy.ui.pyside.main import Ui_MainWindow  # noqa: F401
  File "/usr/local/lib/venvs/guiscrcpy/lib/python3.9/site-packages/guiscrcpy/ui/pyside/main.py", line 11, in <module>
    from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
ModuleNotFoundError: No module named 'PySide6'
```
Then I added PyQt5 and PySide6 modules `pipx inject guiscrcpy pyqt5 pyside6` and this happened:

```
Traceback (most recent call last):
  File "/usr/local/lib/venvs/guiscrcpy/lib/python3.9/site-packages/guiscrcpy/cli.py", line 157, in cli
    bootstrap(
  File "/usr/local/lib/venvs/guiscrcpy/lib/python3.9/site-packages/guiscrcpy/launcher.py", line 1283, in bootstrap
    guiscrcpy = InterfaceGuiscrcpy(
  File "/usr/local/lib/venvs/guiscrcpy/lib/python3.9/site-packages/guiscrcpy/launcher.py", line 111, in __init__
    self.setupUi(self)
  File "/usr/local/lib/venvs/guiscrcpy/lib/python3.9/site-packages/guiscrcpy/ui/pyside/main.py", line 35, in setupUi
    MainWindow.setSizePolicy(sizePolicy)
TypeError: arguments did not match any overloaded call:
  setSizePolicy(self, QSizePolicy): argument 1 has unexpected type 'PySide6.QtWidgets.QSizePolicy'
  setSizePolicy(self, QSizePolicy.Policy, QSizePolicy.Policy): argument 1 has unexpected type 'PySide6.QtWidgets.QSizePolicy'
```

Any ideas ?

**Comment by nikhilsheoran** [comment]
This error is on macbook air m1.
Go to  "/usr/local/lib/venvs/guiscrcpy/lib/python3.9/site-packages/guiscrcpy/ui/pyside/main.py" file and change all 3 import statements.

Old File import statements.
`from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QCheckBox, QComboBox,
    QDial, QFrame, QGridLayout, QHBoxLayout,
    QLabel, QLayout, QLineEdit, QListView,
    QListWidget, QListWidgetItem, QMainWindow, QProgressBar,
    QPushButton, QSizePolicy, QSlider, QStatusBar,
    QVBoxLayout, QWidget)
from  . import rsrc_rc`

To
`from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide2.QtWidgets import (QAbstractScrollArea, QApplication, QCheckBox, QComboBox,
    QDial, QFrame, QGridLayout, QHBoxLayout,
    QLabel, QLayout, QLineEdit, QListView,
    QListWidget, QListWidgetItem, QMainWindow, QProgressBar,
    QPushButton, QSizePolicy, QSlider, QStatusBar,
    QVBoxLayout, QWidget)
from  . import rsrc_rc`

NOTE: Notice that I only changed PySide6 To PySide2. If PySide2 is not installed, install it using `pip3 install PySide2`.

Doing the above fixed this error for me.

**Comment by jJit0** [comment]
Ok so I added PySide2 into guiscrcpy venv, and I changed PySide6 to PySide2 in this file `/usr/local/lib/venvs/guiscrcpy/lib/python3.9/site-packages/guiscrcpy/ui/pyside/main.py` but I have a different error
```
Traceback (most recent call last):
  File "/usr/local/lib/venvs/guiscrcpy/lib/python3.9/site-packages/guiscrcpy/cli.py", line 157, in cli
    bootstrap(
  File "/usr/local/lib/venvs/guiscrcpy/lib/python3.9/site-packages/guiscrcpy/launcher.py", line 1283, in bootstrap
    guiscrcpy = InterfaceGuiscrcpy(
  File "/usr/local/lib/venvs/guiscrcpy/lib/python3.9/site-packages/guiscrcpy/launcher.py", line 111, in __init__
    self.setupUi(self)
  File "/usr/local/lib/venvs/guiscrcpy/lib/python3.9/site-packages/guiscrcpy/ui/pyside/main.py", line 35, in setupUi
    MainWindow.setSizePolicy(sizePolicy)
TypeError: arguments did not match any overloaded call:
  setSizePolicy(self, QSizePolicy): argument 1 has unexpected type 'PySide2.QtWidgets.QSizePolicy'
  setSizePolicy(self, QSizePolicy.Policy, QSizePolicy.Policy): argument 1 has unexpected type 'PySide2.QtWidgets.QSizePolicy'
```
It seems that there is a conflict between PySide2 and PySide6 if both installed

Also, I tried to remove PySide6 module from the venv, and changed import PySide6 to import PySide2 in all files `/usr/local/lib/venvs/guiscrcpy/lib/python3.9/site-packages/guiscrcpy/ui/pyside/*` and I still have the same error

**Comment by C8forT** [comment]
Same or similar error in Arch.  Initially it would not upgrade using Yay - it indicated python-qtpy was the wrong version.  I tried installing the latest version of qtpy (2.0.1), but then my system indicated it was already installed.  So I uninstalled Guiscrcpy using Yay, then reinstalled it.  That seemed to get it installed.

When launching it I then received the following error: ModuleNotFoundError: No module named 'PySide6'.  So I installed PySide6.

Below is the information Guiscrcpy posted when trying to launch it after installing PySide6:

Traceback (most recent call last):
  File "/home/tforsythe/.local/lib/python3.10/site-packages/guiscrcpy/cli.py", line 157, in cli
    bootstrap(
  File "/home/tforsythe/.local/lib/python3.10/site-packages/guiscrcpy/launcher.py", line 1283, in bootstrap
    guiscrcpy = InterfaceGuiscrcpy(
  File "/home/tforsythe/.local/lib/python3.10/site-packages/guiscrcpy/launcher.py", line 111, in __init__
    self.setupUi(self)
  File "/home/tforsythe/.local/lib/python3.10/site-packages/guiscrcpy/ui/pyside/main.py", line 35, in setupUi
    MainWindow.setSizePolicy(sizePolicy)
TypeError: arguments did not match any overloaded call:
  setSizePolicy(self, QSizePolicy): argument 1 has unexpected type 'PySide6.QtWidgets.QSizePolicy'
  setSizePolicy(self, QSizePolicy.Policy, QSizePolicy.Policy): argument 1 has unexpected type 'PySide6.QtWidgets.QSizePolicy'

Please report this, if its a bug, to [guiscrcpy bug tracker](https://github.com/srevinsaju/guiscrcpy/issues) as it will help to improve the next release.

**Comment by anicetoclucas** [comment]
I found the same problem as @C8forT .
Using Windows, .exe version run perfectly but when I try to run installing by pip occurent that error.

**Comment by yochananmarqos** [comment]
@C8forT: `python-qtpy` is now at 2.0.1. I'm getting the same error.

FYI, `pyside6` and `python-pyqt6` are optional dependencies of `python-qtpy`. Either should work...or at least it did with Qt5 / Pyside2.

**Comment by srevinsaju** [comment]
Currently the UI files are generated using `pyside6-rcc` and `pyside6-uic`. I think if you need to use another Qt python library, the UI files will need to be recompiled using their respective UI and resource compiler.

For `pyside6`, I am currently doing this:
```bash
pyside6-rcc guiscrcpy/ui/rsrc.qrc -o guiscrcpy/ui/pyside/rsrc_rc.py
pyside6-uic guiscrcpy/ui/mainwindow.ui -o guiscrcpy/ui/pyside/main.py --from-imports
pyside6-uic guiscrcpy/ui/downloader.ui -o guiscrcpy/ui/pyside/downloader.py --from-imports
pyside6-uic guiscrcpy/ui/bottompanelui.ui -o guiscrcpy/ui/pyside/panel.py --from-imports
pyside6-uic guiscrcpy/ui/toolkit_ui.ui -o guiscrcpy/ui/pyside/toolkit.py --from-imports
pyside6-uic guiscrcpy/ui/network.ui -o guiscrcpy/ui/pyside/network.py --from-imports
pyside6-uic guiscrcpy/ui/settings.ui -o guiscrcpy/ui/pyside/settings.py --from-imports
```

**Comment by yochananmarqos** [comment]
I have both Pyside6 and PyQt6 installed. Neither Build / Installer nor Poetry looks for either during build or install.

**Comment by srevinsaju** [comment]
@yochananmarqos Can you try setting `QT_API=pyside6` to see if guiscrcpy (qtpy) generates any warning messages? Another env var is `FORCE_QT_API=pyside6` (`pyside6` or `pyqt6`)

**Comment by yochananmarqos** [comment]
> QT_API=pyside6

That works fine. I've updated `guiscrcpy-git` to utilized that.

However PyQt6 does not:

```
❯ QT_API=pyqt6 guiscrcpy
/usr/lib/python3.10/site-packages/qtpy/__init__.py:201: RuntimeWarning: Selected binding "pyqt6" could not be found, using "pyside2"
  warnings.warn('Selected binding "{}" could not be found, '
python: /usr/src/debug/pyside-setup-opensource-src-6.2.4/sources/shiboken6/libshiboken/signature/signature_helper.cpp:103: int add_more_getsets(PyTypeObject*, PyGetSetDef*, PyObject**): Assertion `false' failed.
zsh: IOT instruction (core dumped)  QT_API=pyqt6 guiscrcpy
```

```
❯ FORCE_QT_API=pyqt6 guiscrcpy

guiscrcpy v4.12.1
by @srevinsaju
https://github.com/srevinsaju/guiscrcpy


Failed to load NotoSans-BoldItalic.ttf font.
Failed to load NotoSans-Italic.ttf font.
Failed to load TitilliumWeb-Bold.ttf font.
Failed to load NotoSans-Bold.ttf font.
Failed to load NotoSans-Regular.ttf font.
Failed to load TitilliumWeb-Regular.ttf font.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/guiscrcpy/cli.py", line 153, in cli
    bootstrap(
  File "/usr/lib/python3.10/site-packages/guiscrcpy/launcher.py", line 1283, in bootstrap
    guiscrcpy = InterfaceGuiscrcpy(
  File "/usr/lib/python3.10/site-packages/guiscrcpy/launcher.py", line 111, in __init__
    self.setupUi(self)
  File "/usr/lib/python3.10/site-packages/guiscrcpy/ui/pyside/main.py", line 35, in setupUi
    MainWindow.setSizePolicy(sizePolicy)
TypeError: arguments did not match any overloaded call:
  setSizePolicy(self, QSizePolicy): argument 1 has unexpected type 'PySide6.QtWidgets.QSizePolicy'
  setSizePolicy(self, QSizePolicy.Policy, QSizePolicy.Policy): argument 1 has unexpected type 'PySide6.QtWidgets.QSizePolicy'

QPixmap::scaleHeight: Pixmap is a null pixmap
Aborting!
```

**Comment by srevinsaju** [comment]
Closing this, since PySide6 support has been reverted and v2023.1.1 has a similar hack to fix differences in PySide2 API.
