### ISSUE TITLE
[BUG] "TypeError: arguments did not match any overloaded call:" 

### ISSUE THREAD

**Issue by hayukimori** [srevinsaju/guiscrcpy#304]
**Describe the bug**
I tried to open application and got an exception from PySide6... 
The application created a window containing the following exception:
```
TypeError: arguments did not match any overloaded call:
  setSizePolicy(self, QSizePolicy): argument 1 has unexpected type 'PySide6.QtWidgets.QSizePolicy'
  setSizePolicy(self, QSizePolicy.Policy, QSizePolicy.Policy): argument 1 has unexpected type 'PySide6.QtWidgets.QSizePolicy
```

**To Reproduce**
1. Go to Terminal and launch 'guiscrcpy'

**Expected behavior**
I expected a window that didn't contain an interface error..

**Screenshots**
![image](https://user-images.githubusercontent.com/69482956/159708976-90bb00ff-eed4-4927-acc6-03d9ca7c6e87.png)

**Desktop (please complete the following information):**

* [ ] Linux
hayukimori@pasukon-a-hd 
----------------------- 
OS: Arch Linux x86_64 
Kernel: 5.16.16-arch1-1 
Uptime: 2 hours, 39 mins 
Packages: 1188 (pacman) 
Shell: zsh 5.8.1 
Resolution: 1024x768 
DE: Cinnamon 5.2.7 
WM: Mutter (Muffin) 
WM Theme: Faded-Dream (CBlack) 
Theme: CBlack [GTK2/3] 
Icons: Mint-Y-Blue [GTK2/3] 
Terminal: xfce4-terminal 
Terminal Font: Monospace 10 
CPU: Intel Core 2 Duo E7400 (2) @ 2.793GHz 
GPU: Intel 82G33/G31 Express 
Memory: 2037MiB / 3914MiB 
                                                                 
                                                                 

**Additional context**
I don't have much to report, I just had an interface error, and I don't know how to solve.
PS: I downloaded from pip3

**Comment by demonk** [comment]
same issue

**Comment by faonecze** [comment]
me too
Manjaro...

**Comment by gyurmogyuri** [comment]
I have same!

**Comment by devsnd** [comment]
Try setting the environment variable `QT_API=pyside2`. After that it works for me.

e.g. in the shell, run
```
QT_API=pyside2 guiscrcpy
```

**Comment by srevinsaju** [comment]
I have tried an update meanwhile, on v2023.1.1. #345, let me know if the issue still exists.
