### ISSUE TITLE
[BUG] main guiscrcpy screen mirroring window not showing

### ISSUE THREAD

**Issue by vckai** [srevinsaju/guiscrcpy#305]
[](https://user-images.githubusercontent.com/5569470/108996212-28c0a400-76af-11eb-845f-243828fd7d6c.jpg)[](https://user-images.githubusercontent.com/5569470/108996388-5b6a9c80-76af-11eb-816c-4759560a9529.jpg)Describe the bug and To Reproduce

after launching guiscrcpy-PySide6-x64.exe and clearly see the connected android device
after clicking the start scrcpy the CMD windows will will show "crcpy launched in 0.XX s"
and the bottom panel and swipe panel appears but not the main mirroring screen

if i used the default scrcpy it work as expected

Expected behavior

to see the main mirroring screen and the enabled panels

Screenshots
guiscrcpy scrrenshoot

guiscrcpy

scrcpy screenshoot

scrcpy

Desktop (please complete the following information):

 Windows 10 Pro 20H2
Architecture: 64-bit
Version: OS build: 19042.804 - Windows Feature Experience Pack 120.2212.551.0
Additional context

scrcpy-win64-v1.23
guiscrcpy-PySide6-x64.exe

guiscrcpy.json
```
{
    "adb": "C:\\Users\\Administrator\\scoop\\shims\\adb.EXE",
    "bitrate": 8000,
    "cmx": "",
    "device": {
        "MRD6HEGUOFDEMB7T": {
            "rotation": 0,
            "wifi": false
        }
    },
    "dimension": null,
    "dispRO": false,
    "extra": "",
    "fullscreen": false,
    "mapper": "",
    "panels": {
        "bottom": true,
        "swipe": true,
        "toolkit": false
    },
    "paths": [
        "bin"
    ],
    "scrcpy": "C:\\Users\\Administrator\\scoop\\apps\\scrcpy\\1.23\\scrcpy.EXE",
    "scrcpy-server": "C:\\Users\\Administrator\\scoop\\apps\\scrcpy\\1.23\\scrcpy-server",
    "sha_shift": 5,
    "swtouches": false,
    "theme": "Breeze",
    "version": 1
}
```

the same： https://github.com/srevinsaju/guiscrcpy/issues/222

**Comment by vckai** [comment]
ERROR: Unexpected additional argument: -b 8000K

change 
```
proc = open_process(
            [self.path, args],
            stdout=stdout,
            stderr=stderr,
        )
```
to
```
proc = open_process(
            [self.path] + [i for i in args.split() if i != ""],
            stdout=stdout,
            stderr=stderr,
        )
```

**Comment by srevinsaju** [comment]
Thank you @vckai, I have copied your change over to `main` Didn't notice this error!
