### ISSUE TITLE
Lost icon picture

### ISSUE THREAD

**Issue by felixecited** [srevinsaju/guiscrcpy#313]
guiscrcpy desktop icon lost its picture without having changed anything in the app. Uninstalling and reinstalling does not change the icon.
![guiscrcpy icon](https://user-images.githubusercontent.com/102119632/177118704-dcf512f6-ba08-4f1c-bcf1-38f00bd40354.png)
The .png shows what the icon looks like now. I have linux mint 20.02 fully updated and reinstalled using software manager Build v4.11.2

**Comment by srevinsaju** [comment]
Can you try updating to v2022.7.1?

**Comment by felixecited** [comment]
Upgrading to a newer version fixed this. You can close this issue
