### ISSUE TITLE
Screen mirroring display is too tiny

### ISSUE THREAD

**Issue by Aerodin** [srevinsaju/guiscrcpy#316]
**Describe the bug**
AppImage works - and it starts up.  When pressing Start SCRCPY it fires up just fine.  But the default size of the phone window is a tiny little line that is extremely easy to miss.  I almost though this program was broken until I noticed it!

On a multi monitor setup the controls showed up on one monitor and I completely missed this tiny little line that was on a different monitor for a good ten minutes.  I have relocated the controls to be next to the window for size comparison in the screenshot below.

**To Reproduce**
Steps to reproduce the behavior: (Multi monitor setup)
1. Download either of the latest version available AppImage versions - I took the screenshot with guiscrcpy-v2022.6.1.dev.r.glibc2.31-x86_64.AppImage
3. Run the AppImage, and click Start ScrCpy.
4. Controls show up.
5. Observer Itty bitty phone display window is a tiny little line that is easy to miss.

**Expected behavior**
I expected at least a decently sized phone screen that would be easy to find on the screen.

**Screenshots**
https://imgur.com/a/oylcS3B

**Desktop (please complete the following information):**
* [ ] Ubuntu Budgie
- **Architecture**: 64-bit
- **Version**: 22.04

**Comment by srevinsaju** [comment]
Looks like this depends on the mobile device manufacturer and model of the android device. I cannot reproduce the issue. Maybe this is an issue for https://github.com/Genymobile/scrcpy? Maybe you can check for existing issues on that repository for the same. As a workaround, you can manually set the dimensions.

**Comment by srevinsaju** [comment]
Closing this issue as stale.
