### ISSUE TITLE
Error on Swipe Left

### ISSUE THREAD

**Issue by rjbeswin** [srevinsaju/guiscrcpy#32]
LOG: Passing SWIPE LEFT
Traceback (most recent call last):
  File "C:\Users\FLASHY\guiscrcpy\guiscrcpy\__main__.py", line 1051, in swipleft
ValueError: invalid literal for int() with base 10: '2560\r\nOverride size'

**Comment by srevinsaju** [comment]
hello @rjbeswin can you please send me the output when you execute 
```
adb shell wm size
```

**Comment by rjbeswin** [comment]
Physical size: 1440x2560
Override size: 1080x1920

**Comment by srevinsaju** [comment]
@rjbeswin, this is a new type of display resolution. I haven't implemented swipe for Override Size (I didn't know one existed like that, I thought only Physical Size existed). I will surely implement in the next version!

**Comment by rjbeswin** [comment]
I was actually using extended display in my laptop at work. Does it something to do with that?

**Comment by srevinsaju** [comment]
@rjbeswin, ir hss nothing to do with extended display. seems like your phone resolution was changed manually. can you send me a screenshot of your Android device in full quality (by not resizing), you can do this by

```
$ adb shell screencap -p screen.png
$ adb pull screen.png
```
I would like to know whiv is your original screen resolution, as two of them are given?

**Comment by rjbeswin** [comment]
C:\Users\RBeswin>adb shell screencap -p screen.png
Error opening file: screen.png (Read-only file system)

**Comment by srevinsaju** [comment]
try this
```
$ adb shell screencap -p /sdcard/scr.png
$ adb pull /sdcard/scr.png
```

**Comment by rjbeswin** [comment]
![scr](https://user-images.githubusercontent.com/49226873/69962541-34bfc380-1549-11ea-8d5e-6741659ea25b.png)

**Comment by rjbeswin** [comment]
Hi do we have an update for this?

**Comment by rjbeswin** [comment]
Do we have an update for this?

**Comment by srevinsaju** [comment]
oops forgot about it. thanks for reminding, will reply soon, if I get any clue

**Comment by srevinsaju** [comment]
I am fixing the issue right now 🤔

**Comment by rjbeswin** [comment]
Thats great to hear!

**Comment by srevinsaju** [comment]
@rjbeswin fixed it on Release 3.0

**Comment by rjbeswin** [comment]
I just need to re-download this again right?

[image: image.png]

**Comment by srevinsaju** [comment]
@rjbeswin I forgot this comment, You have to download the latest python package if you prefer pip packages, by pip3 install guiscrcpy==3.0.post2 or the latest version, if you are a Windows user, you may also download the latest release from guiscrcpy/releases to test the new version. thanks
