### ISSUE TITLE
Error: Unhandled exception

### ISSUE THREAD

**Issue by OlimjonSN** [srevinsaju/guiscrcpy#321]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
* [ ] Windows
- **Architecture**: Example: 32-bit / 64-bit
- **Version**: Example: 10, 8.1, 7

* [ ] Linux
 - Please paste your `neofetch` here. (What is a [neofetch](https://github.com/dylanaraps/neofetch))
A `neofetch` is always available in your package repositories. 

- > If you do not want to install neofetch; Please provide the name of your desktop environment, distro and architecture

* [ ] MacOS
 - **Version**: Example Catalina 10.15

**Additional context**

**Comment by Naman278** [comment]
@OlimjonSN can you provide more information

**Comment by srevinsaju** [comment]
Closing this issue as stale.
