### ISSUE TITLE
Android phone won't display

### ISSUE THREAD

**Issue by felixecited** [srevinsaju/guiscrcpy#322]
Samsung s10 just stopped displaying. Guiscrcpy says its connected but nothing displays on monitor Android CT201 still displays correctly with no issues.
Sometimes the phone screen turns black for a second and most of the time it does not. I'm using Linux Mint with cinnamon 20.03 fully updated

 - Please paste your `neofetch` here. 
 -      OS: Linux Mint 20.3 x86_64 
        Host: HP Laptop 17-by0xxx 
        Kernel: 5.4.0-122-generic 
       Uptime: 1 day, 9 hours, 43 mins 
       Packages: 3172 (dpkg), 13 (flatpak), 
       Shell: bash 5.0.17 
       Resolution: 3840x2160 
       DE: Cinnamon 
       WM: Mutter (Muffin) 
       WM Theme: Mint-Y-Dark-Blue (Adapta-N 
       Theme: Mint-Y-Dark-Blue [GTK2/3] 
       Icons: Mint-X-Blue [GTK2/3] 
       Terminal: gnome-terminal 
       CPU: Intel i3-8130U (4) @ 3.400GHz 
       GPU: Intel UHD Graphics 620 
       Memory: 3857MiB / 15888MiB 
            

**Additional context** using Guiscrcpy v4.9.0

**Comment by felixecited** [comment]
![guiscrcpy desktop](https://user-images.githubusercontent.com/102119632/183086058-4eabeecb-22c2-4c16-a9b7-9f355dae9647.png)

**Comment by felixecited** [comment]
desktop picture but no phone display

**Comment by srevinsaju** [comment]
Can you try running from terminal, to see if there are any logs?

**Comment by felixecited** [comment]
i don't know how to extract the info your wanting, suggest how please

**Comment by srevinsaju** [comment]
Open a terminal, and run guiscrcpy.


```bash
/path/to/guiscrcpy.AppImage
```
if you are using the AppImage
or else
```bash
flatpak run in.srev.guiscrcpy
``` 
if you are using the flatpak.

Btw, it seems you are using an older version of guiscrcpy. Kindly update

**Comment by felixecited** [comment]
I updated to 2022.6.1 and now neither tablet or phone screen shows on desktop. guiscrcpy says they are connected

**Comment by srevinsaju** [comment]
I would love to have the logs so that I can debug what is happening. Meanwhile, not sure if the issue you are facing is now resolved by the newest version of guiscrcpy v2023.1.1
