### ISSUE TITLE
Guiscrcpy crashes when it connects to the phone

### ISSUE THREAD

**Issue by shutarg** [srevinsaju/guiscrcpy#326]
Guiscrcpy crashes at 80% when connects to the phone. It started happening after installed pipewire audio on Manjaro Linux. 
![Screenshot](https://user-images.githubusercontent.com/80475751/187769801-e27e9ed7-f3f3-4231-bead-7a5e7ae3ddfc.png)

**Comment by srevinsaju** [comment]
This issue is fixed now #345
