### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Wizards-god** [srevinsaju/guiscrcpy#327]
**Describe the bug**
I opened the using the "guiscrcpy" command from the command line, I pointed out the location of 'scrcpy' and 'scrcpy-server'.
it then gave me the error, I have attached the file for reference.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Windows Terminal
2. Type in "guiscrcpy" and hit enter.
3. See error

**Expected behaviour**
The GUI to open

**Screenshots**

**Desktop (please complete the following information):**
* [x] Windows
- **Architecture**: 64-bit
- **Version**: 11

**Comment by Wizards-god** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/70703332/189125746-e864ebcf-5476-4240-a996-43b7dcfba8b7.png">
Sorry, had forgotten to attach this in the original issue

**Comment by srevinsaju** [comment]
Can I know the version of scrcpy?

**Comment by Wizards-god** [comment]
The Version is "v4.12.0"

**Comment by srevinsaju** [comment]
Can you update to the latest release? v2022.7.1 (releases page)

**Comment by Wizards-god** [comment]
I updated it through the pip interface, do I need to install it in some other way?

**Comment by Wizards-god** [comment]
It works fine after using the .exe file, thank you very much for the help...
Can I remove it from python or should I let it stay?
Should I always open it from the .exe file or is there any other way to open it?

**Comment by srevinsaju** [comment]
>  Should I always open it from the .exe file or is there any other way to open it?

The `.exe` should be fine.
