### ISSUE TITLE
[BUG] Cannot connect on android 11+

### ISSUE THREAD

**Issue by CompileConnected** [srevinsaju/guiscrcpy#344]
**Describe the bug**
this is a bug because it's only support android 10 and below 

scrcpy: 1.21

Gui-scrcpy: 4.9.0

ADB Version:
Android Debug Bridge version 1.0.41
Version 33.0.3-8952118

if you connect with adb manually with pair and connect, scrcpy will works.
But not the gui-scrcpy

**Comment by JustCryen** [comment]
I'm on android 12 and it works great…
But to be fair I'm using `scrcpy 1.24-1` and `guiscrcpy 7.1.1` so you might want to update.

**Comment by srevinsaju** [comment]
Yes, please use the latest version of guiscrcpy, and it should be solved. The latest version is `2023.1.1` , which has a few more bug fixes including the latest version of scrcpy for Linux
