### ISSUE TITLE
[BUG] Error: Unhandled Exception

### ISSUE THREAD

**Issue by rmalampriandanu** [srevinsaju/guiscrcpy#345]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/120299895/206891544-67331384-5896-4d3f-9e1e-908930554ca8.png)

**Desktop (please complete the following information):**
* [ ] Windows
- **Architecture**: 64-bit
- **Version**: Windows 11 22h2

**Comment by srevinsaju** [comment]
I will need the guiscrcpy version you are using, and the configuration you have, in C:/Users/<username>/AppData/Roaming/guiscrcpy/config or C:/Users/<username>/AppData/Local/guiscrcpy/config

**Comment by Kaushik4852** [comment]
![image](https://user-images.githubusercontent.com/79138524/206913021-c5f15b43-53bc-4a06-8753-2e8caf17336e.png)

error: Traceback (most recent call last):
  File "guiscrcpy\launcher.py", line 1195, in start_act
  File "guiscrcpy\lib\bridge\scrcpy.py", line 20, in start
TypeError: can only concatenate list (not "str") to list

when  pressed start scrcpy

**Comment by srevinsaju** [comment]
I think this issue is now fixed on `main` branch, a release coming up soon. Sorry for the super long delay! Please let me know on this issue if this is resolved. I will close this issue for now.
