### ISSUE TITLE
AppImage report this issue

### ISSUE THREAD

**Issue by felixecited** [srevinsaju/guiscrcpy#346]
i downloaded appimage for linux mint 21.trying to run gui or terminal gives these results.
<img width="869" alt="scrpy" src="https://user-images.githubusercontent.com/102119632/207521737-fab3177e-7324-48f0-8575-bdfdde020942.png">
<img width="528" alt="gui" src="https://user-images.githubusercontent.com/102119632/207521755-72bb4014-ed7e-4611-8a37-970d60cbb471.png">
<img width="528" alt="end result" src="https://user-images.githubusercontent.com/102119632/207521774-f9e90432-8387-4ecf-b1e8-3e9b76cbcdc3.png">
<img width="1413" alt="terminal run" src="https://user-images.githubusercontent.com/102119632/207521787-99fa5f87-06b4-48e9-a11a-6a45c7665fd4.png">
<img width="1414" alt="unhandled report" src="https://user-images.githubusercontent.com/102119632/207521806-ef6aeb8d-0682-43d4-9304-95a8d85f958e.png">

am i missing what to do next?

**Comment by felixecited** [comment]
then no device appears at all, says connected but nothing appears on screen

**Comment by felixecited** [comment]
suggestions?

**Comment by srevinsaju** [comment]
Actually, when the `scrcpy` prompt happens, you should choose the binary location for https://github.com/Genymobile/scrcpy instead.

**Comment by srevinsaju** [comment]
I will close this issue for now, feel free to reopen this, or drop comments and I will be back.

**Comment by felixecited** [comment]
Actually, when the scrcpy prompt happens, you should choose the binary location for https://github.com/Genymobile/scrcpy instead. I'm still a beginner, would you please explain this more? there is a  lot of things i don't know about linux and handling files like this is one. Thanks
