### ISSUE TITLE
Just mirroring and wont be able to control

### ISSUE THREAD

**Issue by rm-killer** [srevinsaju/guiscrcpy#364]
The bug is that i can not control the phone. just mirroring works. my phone is Xiaomi 11t and im using the win 11 and android 13

**Comment by rm-killer** [comment]
I found the solution guys. 
I don't now why but im using another apps that use the debugging through usb. so I just revoked all the usb debugging permissions and then when i tried again using this. it asked my permission and it worked

**Comment by srevinsaju** [comment]
closing as done, thanks for the fix!
