### ISSUE TITLE
guiscrcpy 2.0 exe

### ISSUE THREAD

**Issue by vorikx2** [srevinsaju/guiscrcpy#37]
Is there any plan on making a 2.0 exe like with v1.10? Been trying to get 2.0 to run without an exe but for some reason I run into trouble with using python

**Comment by srevinsaju** [comment]
I can create an exe for you, but most people prefer python because it's so fast compared to binary. what is the error you're coming across while running it with python?

**Comment by vorikx2** [comment]
that'd be awesome! I'd have to reinstall python to double check, but I think it was along the lines of it not being able to find something

**Comment by srevinsaju** [comment]
@vorikx2 It might be probably 
`ModuleNotFoundError: pynput not found`
If thats so,
Fix it by:
```
pip3 install pynput --user
```
or (on windows)
```
pip install pynput --user
```

**Comment by vorikx2** [comment]
Any chance you'd still be able to make the exe at all?

**Comment by srevinsaju** [comment]
@vorikx2 to build an exe, I need to have a windows system. My hdd got corrupted, and am waiting this month end to get it working again. Had exams, so couldn't work on it. 
If you would prefer v1.11 versions for Windows available on MEGA

**Comment by srevinsaju** [comment]
@vorikx2 v3.0 with exe is ready. Stay tuned

**Comment by vorikx2** [comment]
@srevinsaju you legend

**Comment by srevinsaju** [comment]
I am writing Release Notes, 5 minutes, and it would be ready :). Hope there would not be any errors :), fixed DPI errors too. Thanks @vorikx2

**Comment by srevinsaju** [comment]
@vorikx2 released. enjoy
