### ISSUE TITLE
version 2.0 Does not work on Windows

### ISSUE THREAD

**Issue by bckps7336** [srevinsaju/guiscrcpy#39]
Hello, 
I installed via the pip method `pip install guiscrcpy`,
and when I want to start it, it gave me an error saying
> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Hello\AppData\Roaming\Python\Python38\site-packages\guiscrcpy\__init__.py", line 8, in <module>
    from guiscrcpy import __main__
  File "C:\Users\Hello\AppData\Roaming\Python\Python38\site-packages\guiscrcpy\__main__.py", line 102, in <module>
    os.chdir(str(os.path.abspath(__file__))[: -len(filename)])
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: ''

In that line, I am able to find out that `filename` contains the full path to the file, so the final result is to chdir to a empty string, thus an error occurred.

A fix to this is to hardcode the offset: `os.chdir(str(os.path.abspath(__file__))[: -11])`
And it worked for me.

**Comment by srevinsaju** [comment]
ok, thanks for reporting the bug, what does [:-11] return from the os.chdir thing. also try importing it into the console, you can do this on your bash / cmd.exe or powershell

```
> python -c 'from guiscrcpy import __main__ as m; m.launch_main()'

```
hope it works! let me know if it does, so I can alter the code

**Comment by bckps7336** [comment]
> what does [:-11] return from the os.chdir thing

11 is the length of `__main__.py`, which after cutting it from the file string, is the path to the file.

The command reported as follows: (I reinstalled to undo my change)

>PS C:\Users\hello> python -c 'from guiscrcpy import __main__ as m; m.launch_main()'
LOG: This is not running from Source. No git sha retrievable
LOG: Extracting version number from pip
LOG: Received flag False
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\hello\AppData\Local\Programs\Python\Python38-32\lib\site-packages\guiscrcpy\__init__.py", line 8, in <module>
    from guiscrcpy import __main__
  File "C:\Users\hello\AppData\Local\Programs\Python\Python38-32\lib\site-packages\guiscrcpy\__main__.py", line 102, in <module>
    os.chdir(str(os.path.abspath(__file__))[: -len(filename)])
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: ''

**Comment by srevinsaju** [comment]
Hmm @bckps7336, thats great info! :100:  Unfortunately, can't implement it in the main branch because, some people run guiscrcpy by the filename `guiscrcpy` as a module and not `__main__.py`, I would be glad to know what the `filename` corresponds to in Windows. For me on linux, `filename` corresponds to `guiscrcpy` and not `__main__.py`, maybe the filename is what I need to fix. Thanks

**Comment by AmonBune** [comment]
I have the same issue. And as an addition to this, some dependencies do not install automatically.

`ModuleNotFoundError: No module named 'pynput'`
and
`ERR: gitpython is not found. It is not a dependency, but you can optionally install it with python3 -m pip install gitpython`

That was what I tried:
![image](https://user-images.githubusercontent.com/15927695/72180356-4ec1b100-33e7-11ea-8e8c-bea27f71d77f.png)

**Comment by srevinsaju** [comment]
thanks @AmonBune for the info regarding dependencies. Fixed on https://github.com/srevinsaju/guiscrcpy/commit/8357362fcc8b28241e0a3cdfd7114bb02bf4ed81

**Comment by srevinsaju** [comment]
@bckps7336 @AmonBune I fixed the Error you have mentioned on the latest commit. Please review. Thanks

**Comment by AmonBune** [comment]
@srevinsaju Thanks! I think we have to wait for the release on pip to be able to review it.

**Comment by srevinsaju** [comment]
will release the security fix, scheduled Monday 2100 GMT+0300

**Comment by srevinsaju** [comment]
@AmonBune @bckps7336 PYPI released it a bit early. 
https://pypi.org/project/guiscrcpy/

**Comment by AmonBune** [comment]
@srevinsaju It installs the dependencies now, thanks!

**Comment by srevinsaju** [comment]
Check if it starts too :)

**Comment by AmonBune** [comment]
@srevinsaju Yes, it starts and everything. Thanks for the credits :)
