### ISSUE TITLE
Panels not movable using Ubuntu 19.04

### ISSUE THREAD

**Issue by logix2** [srevinsaju/guiscrcpy#4]
The two guiscrcpy panels (toolkit UI controller and bottom panel controller) cannot be moved on Ubuntu 19.04 with Qt 5.12.2. I assume one was supposed to be able to move them by dragging the 4 dots icon, but that doesn't work. I can move them by holding the Super key, then dragging them using the left mouse button, but some users might not be aware of that.

I'm using the latest guiscrcpy Linux binary downloaded from the releases page.

**Comment by srevinsaju** [comment]
I tried it on Ubuntu 19.04 with KDE Plasma, it has worked. I tested it on Windows, and works good. Are you using GNOME? It would be very useful if you send your gnome version, so that I can update the README.MD file for adding Super key and drag. I can add a title bar. What is your opinion on the title bar

**Comment by logix2** [comment]
Yes, I'm using Gnome 3.32.2 with Gtk 3.24.8 (the Ubuntu 19.04 default).

**Comment by srevinsaju** [comment]
> what about having a title bar? 

PyQt has some problems with Frameless windows. I shall test it on my GNOME and update you.

**Comment by srevinsaju** [comment]
I have tested moving Panels in Ubuntu LTS 18.04 and 19.04. So far, I have no non-moving issues. Checked from compiled binary and source. Works fine. It seems like a bug in your device. Can you send your `neofetch`

**Comment by logix2** [comment]
It could be an issue on my device, that I don't know. Here's neofetch:

```
$ neofetch
            .-/+oossssoo+/-.               logix@logix-desktop 
        `:+ssssssssssssssssss+:`           ------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 19.04 x86_64 
    .ossssssssssssssssssdMMMNysssso.       Kernel: 5.0.0-25-generic 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Uptime: 5 hours, 53 mins 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Packages: 4646 (dpkg), 80 (flatpak), 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Shell: bash 5.0.3 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Resolution: 2560x1080, 1920x1080 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   DE: GNOME 3.32.2 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: GNOME Shell 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM Theme: Adwaita 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Theme: Yaru [GTK2/3] 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Icons: Yaru [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Terminal: gnome-terminal 
  +sssssssssdmydMMMMMMMMddddyssssssss+     CPU Usage: 87% 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      Disk (/): 175G / 220G (84%) 
    .ossssssssssssssssssdMMMNysssso.       Memory: 6123MiB / 16019MiB 
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`                                   
            .-/+oossssoo+/-.
```

**Comment by srevinsaju** [comment]
Ok, anyways, I shall add using Super, Meta or Alt keys to move panel, in the case of non-functionality, with reference to this issue. So with this, I am closing this issue.
