### ISSUE TITLE
error:clipd2PC&&clipPC2d   windows 10 1909  

### ISSUE THREAD

**Issue by ariagecheney** [srevinsaju/guiscrcpy#44]
windows 10  1909 ， Anaconda Create guiscrcpy's own environment , vscode 1.0.39
I downloaded the source code, debugging  via  vscode.I have executed"pip install -r requirements“ and i unlocked some features such as clipd2PC, clipPC2d

1. but   "__main__.py line 445:  scrcpywindow.foucus(), run error: AttributeError: 'Win32Window' object has no attribute 'focus' ". 
2. "__main__.py line 593:function clippc2d()  , This function can only  copy English characters to the phone, but there is a delay; "Chinese characters " is lost in English and Chinese mixed statements such as " 你好，guiscrcpy" and only  ",guiscrcpy", "你好”lost .

i really find clipPC2d and clipd2PC  so useful.

meanwhile , guiscrcpy  doesn't  support chinese input method.  what a pity!! and it can't transfer files from  phone to his computer expeditiously.

So I sincerely request to be able to package a. Exe file to support clipboard copy transfer to each other

**Comment by srevinsaju** [comment]
Hello @ariagecheney . Copying characters are limited to unicode. This is an issue on Genymobile/scrcpy https://github.com/Genymobile/scrcpy . Clipboard activity uses pygetwindow and pyautogui to work. Without that it won't work. I have not tested Clipboard activity button on Windows, but this might be useful and is working

On the screen mirroring window:
`Ctrl + C` does copy from phone to PC
`Ctrl + Shift + C` does copy from PC to Phone clipboard

**Comment by srevinsaju** [comment]
@ariagecheney This is the same issue you are having, https://github.com/Genymobile/scrcpy/issues/907

**Comment by ariagecheney** [comment]
> Hello @ariagecheney . Copying characters are limited to unicode. This is an issue on Genymobile/scrcpy https://github.com/Genymobile/scrcpy . Clipboard activity uses pygetwindow and pyautogui to work. Without that it won't work. I have not tested Clipboard activity button on Windows, but this might be useful and is working
> 
> On the screen mirroring window:
> `Ctrl + C` does copy from phone to PC
> `Ctrl + Shift + C` does copy from PC to Phone clipboard

Thanks for your reply and help! But I do say:

1. On my computer, when I copied some text (all in English) from the screen mirror window (mobile phone), I did not click the toolbar, moved the mouse directly to the computer, and still could not "paste successfully ".
2. Even though I copied, I clicked "toolbar -- copy device clipboard to PC" and got an error：
 ------------------------------------
  WARNING : Copy device to PC is implemented only in source code due to its development stage
 If you are a developer, uncomment the import statements of PyAutoGui
Traceback (most recent call last):
  File "guiscrcpy\__main__.py", line 446, in clipd2pc
    scrcpywindow.focus()
AttributeError: 'Win32Window' object has no attribute 'focus'
------------------------------------

 I'm sure I've uncommented and imported PyAutoGUI and pygetwindow.

# Uncomment this if you would like to test experimental features
# uncommented .
try:
    import pyautogui as auto
except ModuleNotFoundError:
    print("PyAutoGUI is not installed. Please install it with pip install pyautogui."
          "Read the README.md on github.com/srevinsaju/guiscrcpy. \n You might want to continue without "
          "pyAutoGUI limited functionality")
try:
    from pygetwindow import getWindowsWithTitle
except NotImplementedError:
    print("  some module is not imported")


--------------------

so Ask for your help again sincerely!

**Comment by srevinsaju** [comment]
Hope your issue is solved on https://github.com/Genymobile/scrcpy/issues/1057 . It is always best for its creator to explain how it works. I created only thr GUI wrapper for the command line baseed scrcpy

**Comment by srevinsaju** [comment]
@ariagecheney regarding the button, probably PyAutoGUI have changed their API, i have not updated to latest version on Windows. My testing is focused on Linux (as thats only available option) Hope you installed guiscrcpy 2.0 from PYPI

**Comment by ariagecheney** [comment]
> @ariagecheney Hope your issue is solved on [Genymobile/scrcpy#1057](https://github.com/Genymobile/scrcpy/issues/1057) . It is always best for its creator to explain how it works. I created only thr GUI wrapper for the command line baseed scrcpy

thank you! now it work very correctly  instructed by https://github.com/Genymobile/scrcpy/issues/1057#issuecomment-570789658 steps! 
thank you very much! @srevinsaju
