### ISSUE TITLE
[Windows] GUI renders wrong when using high DPI monitors

### ISSUE THREAD

**Issue by AmonBune** [srevinsaju/guiscrcpy#45]
When using a monitor over 100% DPI (for example a 4K display) the whole GUI and controls render wrong. Here a Screenshot of the issue:
![image](https://user-images.githubusercontent.com/15927695/72111332-bff75a80-333a-11ea-98df-6b95de9cef40.png)

**Comment by srevinsaju** [comment]
oh Lord 😂.

this was one of the issues pointed out by one of my clients using guiscrcpy. there are few steps to fix this:

* download and install guiscrcpy 2.0
* resize the window to make guiscrcpy visible

thanks for letting me know. I would add the screen size to the configuration file so that you won't have to resize over an over

**Comment by AmonBune** [comment]
@srevinsaju Oh Lord, yes. 😂
The main window is actually not very much of a problem. Surely it is annoying and looks horrible when everything is scrambles like that, but the greater issue is the floating action bars. They cannot be resized per design and it's hard to guess what each button does or even click the correct one because they overlap each other in some cases.

Anyway, it would be great to have a nice GUI with high DPI screens without fiddling with the window sizes on every startup 💃

**Comment by srevinsaju** [comment]
Ok @AmonBune thanks for the review, It seems like the toolbar icons are oversized comaparative to the window. Did you install 2.0 and check?

**Comment by AmonBune** [comment]
@srevinsaju Version 2.0 looks like this:

![image](https://user-images.githubusercontent.com/15927695/72181532-de685f00-33e9-11ea-843c-3e2ba04a72a8.png)

As you can see, the buttons are pretty small. It would be nice if they could be made a little larger (according to the dpi percent). Also the two buttons on the bottom left edge of both button panels look a little weird to me. The main window is the same as in Version 1.x

**Comment by srevinsaju** [comment]
@AmonBune Hope this will be fixed  in v3.0, releasing in few minutes

**Comment by srevinsaju** [comment]
@AmonBune please see V3.0

**Comment by AmonBune** [comment]
@srevinsaju I'm not able to install version 3.0 correctly. Something seems to be wrong.

![image](https://user-images.githubusercontent.com/15927695/74180376-adc15280-4c3f-11ea-9c25-26c6a69ede3b.png)

pip --version
pip 20.0.2 from c:\python38\lib\site-packages\pip (python 3.8)

Also I managed to install some weird "-uiscrcpy" package. Don't ask me how I did that. I cannot uninstall it because of the dash in the name...
![image](https://user-images.githubusercontent.com/15927695/74180640-2de7b800-4c40-11ea-85c5-755201ee1ba8.png)
![image](https://user-images.githubusercontent.com/15927695/74180752-54a5ee80-4c40-11ea-8286-8622ea4dfb16.png)

**Comment by srevinsaju** [comment]
@AmonBune seems like your pip packages are messed up completely.
try this
```
pip uninstall '-uiscrcpy'
```
the way to run guiscrcpy is 
```
python -m guiscrcpy
```
you can do the above in any directory, it's not necessary to go to that folder.

PS: I don't know why exactly you are not able to run `guiscrcpy` only and make it run.
alternatively, if you prefer the exe compiled files, you can get it from the releases.

**Comment by AmonBune** [comment]
![image](https://user-images.githubusercontent.com/15927695/74182085-ac455980-4c42-11ea-923a-3c4b07860624.png)
Nothing seems to work... I also never got a desktop or a start menu shortcut. Also not with version 1.x or 2.x. I'll try to uninstall python, pip and all packages and see if it behaves the same again or if it is fixed then.

**Comment by srevinsaju** [comment]
@AmonBune, there is no need to uninstall pip, you can manually delete the folders

Go that directory where you went before, C:/users/.../../site-packages/ in your explorer, remove all the guiscrcpy and uiscrcpy files and then go for a clean install of guiscrcpy
https://pypi.org/project/guiscrcpy/
guiscrcpy · PyPI

Copy paste the code specified in the website, and then it should work.

**Comment by srevinsaju** [comment]
Alternatively, try the exe also ;)

**Comment by AmonBune** [comment]
@srevinsaju I can try the plain windows exe later.

#### Regarding pip:
I deleted all folders regarding guiscrcpy and the uiscrcpy stuff. I reinstalled and got the error:
`No module named guiscrcpy.__main__; 'guiscrcpy' is a package and cannot be directly executed`
![image](https://user-images.githubusercontent.com/15927695/74192924-c2f5ab80-4c56-11ea-8f9b-4b49e5a00b57.png)

And there is actually no `__main__.py` in the folder.
![image](https://user-images.githubusercontent.com/15927695/74192939-cb4de680-4c56-11ea-9719-3a67221be8e4.png)

And I randomly opened the `__init__.py` whose content confuses me. Version 2? It said it installed Version 3 when executing the pip install.
![image](https://user-images.githubusercontent.com/15927695/74193319-78c0fa00-4c57-11ea-9f89-7169ba81ec80.png)

I thought it is a problem with using an administrator shell, but I have tried the same thing with a user shell and I have the same results.

**Comment by srevinsaju** [comment]
@AmonBune my mistake, I tested it again after removing all my installation on Windows, and it shows the same error 
Fixed on https://github.com/srevinsaju/guiscrcpy/commit/11b5b2693c619f8dc847dce937dad9db35dc06a0

Thanks for finding that bug, it was a potential security fix on many devices including MacOS

**Comment by srevinsaju** [comment]
@AmonBune I have made a package for you, you may test it, so I can push it to v3.1

[guiscrcpy-3.0.post17.dev0.tar.gz](https://github.com/srevinsaju/guiscrcpy/files/4198286/guiscrcpy-3.0.post17.dev0.tar.gz)

**Comment by AmonBune** [comment]
I cannot install the tar.gz package on my machine. I uninstalled the existing guiscrcpy with pip uninstall guiscrcpy.

![image](https://user-images.githubusercontent.com/15927695/74474585-1c9fe500-4ea6-11ea-93bb-195176217d4a.png)

**Comment by srevinsaju** [comment]
@AmonBune no need to extract the tar.gz, 
do
```
pip install guiscrcrpy-3.0.post17.dev0.tar
gz
```

**Comment by AmonBune** [comment]
@srevinsaju In the window with the red error I tried just that. I just wanted to show that both methods don't work.

**Comment by srevinsaju** [comment]
@AmonBune does 
pip3 install https://github.com/srevinsaju/guiscrcpy/archive/master.zip work?

**Comment by AmonBune** [comment]
@srevinsaju 
![image](https://user-images.githubusercontent.com/15927695/74555467-0e140500-4f5c-11ea-8476-67869cc5c3e5.png)

**Comment by srevinsaju** [comment]
I guess the last option is :
```
git clone https://github.com/srevinsaju/guiscrcpy
cd guiscrcpy
pip install .
```

**Comment by AmonBune** [comment]
Install works, but I get the same error as before :( 
![image](https://user-images.githubusercontent.com/15927695/74557556-ac09ce80-4f60-11ea-89d5-f529671a4495.png)

**Comment by srevinsaju** [comment]
@AmonBune try only `guiscrcpy`
if that fails too, please let me know,
for the sake of this issue, try
```
python -c 'from guiscrcpy.launcher import bootstrap; bootstrap ()'
```

**Comment by AmonBune** [comment]
@srevinsaju It works, but adb.exe and scrcpy.exe don't get shipped with the pip install.
![image](https://user-images.githubusercontent.com/15927695/74561841-b4b2d280-4f69-11ea-8d3e-96f63f9f4432.png)

**Comment by srevinsaju** [comment]
yea, we have to manually download scrcpy release from https://github.com/Genymobile/scrcpy/releases , actually I am not supposed to add scrcpy.exe to the package as it's copyrighted.

does running `guiscrcpy` work now or did you use python -c .... that one?

**Comment by AmonBune** [comment]
**guiscrcpy worked**. python -c ... did not work and threw some error

**Comment by srevinsaju** [comment]
ok thanks for that, is the DPI error fixed too?

**Comment by AmonBune** [comment]
@srevinsaju When I start up the application, everything is good:
![image](https://user-images.githubusercontent.com/15927695/74567242-9b178800-4f75-11ea-8a95-0a45538e3ea2.png)

But I can resize it a little bit too much. Just increase the min height a little bit here:
![image](https://user-images.githubusercontent.com/15927695/74567270-b4203900-4f75-11ea-88ca-2317ad9940b6.png)

I have to test the other windows later, I have no phone here at the moment

**Comment by AmonBune** [comment]
@srevinsaju The sizing of the icons look good to me:
![image](https://user-images.githubusercontent.com/15927695/74610474-d17b1180-50f3-11ea-8315-2145f1c512e1.png)

**Comment by srevinsaju** [comment]
Thanks for testing @AmonBune, I will close the issue with my open PR for version 3.2 
Keep looking for more features, 
wifi + automatic scrcpy installer (as suggested in your previous issue) + update checker
