### ISSUE TITLE
Uninstall script please.

### ISSUE THREAD

**Issue by deragon** [srevinsaju/guiscrcpy#50]
I am always wary software that only provide an install script, but no uninstall one.  I am concerned to waste time trying to figure out what files was installed where.  Please provide an uninstall script so a proper cleanup can be performed if a user decide to remove the software.

Take for instance my own FOSS project which provides easy means to uninstall the software: [Autopoweroff - Uninstallation](https://github.com/deragon/autopoweroff#Uninstallation)

**Comment by srevinsaju** [comment]
@deragon please use `pip3 uninstall guiscrcpy` to uninstall guiscrcpy. it is automatically done by python's package manager.
if you are a Arch Linux user, and used the AUR, then use `pacman -R' guiscrcrpy`
the manual install script is deprecated, I am trying to remove all instances of manual installation script in the documentation. if you are a user of the previous releases, you should remove 
```
/usr/share/guiscrcrpy
/usr/share/application/guiscrcrpy*
~/.local/bin/guiscrcpy*
~/.local/share/application/guiscrcpy*
```

the manual

**Comment by est61** [comment]
Hi
Does `pip3 uninstall guiscrcpy` still apply if you install as per these commands?
```
git clone https://github.com/srevinsaju/guiscrcpy.git --depth=1
cd guiscrcpy
python3 setup.py install --user
```

I tried it, and it only asked me to remove one file..
```
Found existing installation: guiscrcpy 4.7.3
Uninstalling guiscrcpy-4.7.3:
  Would remove:
    /home/test/.local/lib/python3.6/site-packages/guiscrcpy-4.7.3-py3.6.egg
Proceed (y/n)? y
  Successfully uninstalled guiscrcpy-4.7.3
```

Is that it ?

**Comment by srevinsaju** [comment]
Yes
