### ISSUE TITLE
Icons missing from toolbars with QDarkStyle 2.8

### ISSUE THREAD

**Issue by yochananmarqos** [srevinsaju/guiscrcpy#51]
No issues with QDarkStyle 2.7.

Manjaro GNOME
Vimix-dark-beryl GTK / Kvantum theme
Papirus-Dark-Maia icon theme

![Screenshot from 2020-01-28 08-52-09](https://user-images.githubusercontent.com/5437803/73280400-b2035f80-41ab-11ea-97c9-d0fea09b7156.png)

**Comment by srevinsaju** [comment]
@yochananmarqos areyou using higher DPI settings now, or is this the same testing device as you have used before. 
I have a fix for High DPI systems remaining pending, so I would like to know if this happened due to my recent changes. Thanks for the review

**Comment by yochananmarqos** [comment]
No, I haven't changed my DPI settings. This is the same device I always use. I'm not sure if your recent changes made any difference or not since it looks fine with QDarkStyle 2.7.

**Comment by srevinsaju** [comment]
@yochananmarqos I have pushed the commit https://github.com/srevinsaju/guiscrcpy/commit/39f06a71578c664e3677c8218c5c8f05fc00d9f6, I am not sure if it would work, If you do have any tracebacks, that would help me too, I apologize, I am constrained to do a blind commit, it works only on my PC probably.

**Comment by yochananmarqos** [comment]
It fails when running now:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/guiscrcpy/__main__.py", line 1933, in <module>
    launch_main0()
  File "/usr/lib/python3.8/site-packages/guiscrcpy/__main__.py", line 1868, in launch_main0
    QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True) #enable highdpi scaling
NameError: name 'QApplication' is not defined
```

**Comment by srevinsaju** [comment]
@yochananmarqos I have added another commit. Extremely sorry about that, my brain gets foggy now. I have a lot of changes to commit, so I forgot to stage that hunk.Thanks

**Comment by yochananmarqos** [comment]
No difference, same output.

**Comment by srevinsaju** [comment]
I apologize :cry:, I sent another commit

**Comment by yochananmarqos** [comment]
```
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
QPixmap: Must construct a QGuiApplication before a QPixmap
/usr/sbin/guiscrcpy: line 2: 20351 Aborted                 (core dumped) python /usr/lib/python3.8/site-packages/guiscrcpy/__main__.py
```

**Comment by srevinsaju** [comment]
@yochananmarqos this error looks weird, is it ok if I send all the commits within 10 minutes, because proabably I might have some more unstaged changes, which might be causing this error. :man_facepalming:

**Comment by yochananmarqos** [comment]
Take your time, no worries.

**Comment by srevinsaju** [comment]
@yochananmarqos I  have pushed a huge commit. It should possibly work now. Sorry for the delay

**Comment by yochananmarqos** [comment]
The main window looks the same, but the button bars don't open at all now. No errors this time.

**Comment by srevinsaju** [comment]
Yes, I changed the code to launch the bars when the Start Scrcpy i pressed, hope it now works for you

**Comment by srevinsaju** [comment]
I will be releasing v2.1 in a while, need to completely refactor the code, after a brief stay away from guiscrcpy, I came back and realized how messy it was. I regret writing the code :)

**Comment by yochananmarqos** [comment]
Oh, duh. Yes, the bars launch when starting scrcpy, but they look the same as my above screenshot.

**Comment by srevinsaju** [comment]
Oh, my bad, Idk what do i do, Is there any errors in the stdout?

**Comment by yochananmarqos** [comment]
Nope, no errors this time.

**Comment by srevinsaju** [comment]
Sorry for some more quiestions
-  is your screen size above 1920x1080
- seems like your'e using KDE, may I know what font size you have put, so that I can recreate it on my system and create a possible fix
Thanks

**Comment by srevinsaju** [comment]
@yochananmarqos I have pushed a huge commit again,  I guess its a PyQt5.14 Port regression, the last commit strictly needs PyQt5.14.1, otherwise it might render incorrectly again. Thanks

**Comment by yochananmarqos** [comment]
I tried to move the horizontal bar over dragging from the right and it crashed:

```

**Comment by srevinsaju** [comment]
@yochananmarqos I wasn't able to reproduce the error on KDE, seems like an error which appears only on GNOME, I am getting a Ubuntu 20.04 for testing and fixing it on the VM. Thanks for the guidance you provided for the same

**Comment by srevinsaju** [comment]
@yochananmarqos does commenting
```
    app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())
```
help?

**Comment by yochananmarqos** [comment]
Yes, that does the trick indeed.

**Comment by srevinsaju** [comment]
Ok, the error was with QDarkStyle, idk why, The checkboxes might look a little bad now without QDarkStyle

**Comment by srevinsaju** [comment]
@yochananmarqos if you change the previous code to 
```
app.setStyleSheet(qdarkstyle.load_stylesheet(qt_api='pyqt5'))
```
does it still look offset?

**Comment by yochananmarqos** [comment]
No, they look fine. Same as in my screenshots. 

As I told you to begin with, the issue only occured after updating QDarkStyle from 2.7 > 2.8.

**Comment by srevinsaju** [comment]
Ok, mine might have been outdated, but does this work 
```
app.setStyleSheet(qdarkstyle.load_stylesheet(qt_api='pyqt5'))
```?
Thanks

**Comment by srevinsaju** [comment]
Lol, I reproduced your error with updating qdarkstule to 2.8. :man_facepalming: I'm dumb

**Comment by yochananmarqos** [comment]
Changing to the above made no difference.

**Comment by srevinsaju** [comment]
Ok, then I will be remove qdarkstyle as my dependency. thanks for helping me find my bug
