### ISSUE TITLE
Version 3.0 on Ubuntu: "AttributeError: type object 'QPalette' has no attribute 'PlaceholderText'"

### ISSUE THREAD

**Issue by logix2** [srevinsaju/guiscrcpy#54]
Using the latest guiscrcpy 3.0 installed via pypi (pip3) on Ubuntu 19.10, I get this error when trying to launch it:

```
guiscrcpy
by srevinsaju
3.0
Licensed under GNU GPL v3 (c) 2020  
                                  
MSG: Please ensure you have enabled USB Debugging on your device. See README.md for more details

Traceback (most recent call last):
  File "/home/logix/.local/bin/guiscrcpy", line 12, in <module>
    bootstrap()
  File "/home/logix/.local/lib/python3.7/site-packages/guiscrcpy/launcher.py", line 490, in bootstrap
    bootstrap0()
  File "/home/logix/.local/lib/python3.7/site-packages/guiscrcpy/launcher.py", line 454, in bootstrap0
    prog = InterfaceGuiscrcpy(window)
  File "/home/logix/.local/lib/python3.7/site-packages/guiscrcpy/launcher.py", line 149, in __init__
    self.setupUi(Ui_MainWindow)
  File "/home/logix/.local/lib/python3.7/site-packages/guiscrcpy/ui/main.py", line 649, in setupUi
    QtGui.QPalette.PlaceholderText, brush)
AttributeError: type object 'QPalette' has no attribute 'PlaceholderText'
```

**Comment by srevinsaju** [comment]
@logix2 can you confirm guiscrcpy PyQt5==5.14?

**Comment by srevinsaju** [comment]
```
$pip3 list | grep PyQt5       
PyQt5              5.14.1 
PyQt5-sip          12.7.0
```

**Comment by logix2** [comment]
It looks like it didn't install that version:

```
$ pip3 list | grep PyQt5 
PyQt5                        5.10.1
```

How can I force it to use 5.14?

**Comment by srevinsaju** [comment]
sudo pip3 install PyQt5==5.14 
Seems like your Ubuntu had a debian package already installed in `/usr/lib/python3.*` and it loads that PyQt5 instead of the one in your `~/.local/`.

**Comment by logix2** [comment]
I won't use sudo with pip3, that can completely mess up the system. Every package that uses PyQt5 could be broken after that (I've had this happen in the past with other packages installed with pip). You'll find a lot of information about not using pip with sudo on the web...

Any other solution?

**Comment by logix2** [comment]
Well, actually installing it for my user only (npip3 install --user PyQt5==5.14 ) got it to work. So I guess guiscrcpy didn't pull it the correct PyQt5 version by itself.

**Comment by srevinsaju** [comment]
Hmm, maybe, I will specify it in the documentation. Hope you like v3.0

**Comment by logix2** [comment]
Thanks for your help. The app works nicely now.

**Comment by srevinsaju** [comment]
Great to know!

**Comment by logix2** [comment]
One more thing. This fails to install

```
pip3 install pyqt5
```

This works properly:

```
pip3 install PyQt5==5.14
```

Actually, some Linux systems don't have pip3, and for them pip (which is for Python 2 on Ubuntu) defaults to pip3 (for Python 3). The alternative that works on any Linux distribution (via Google) is to use "python -m pip install", that works on any Linux distribution and uses Python3 correctly. So then the proper installation instructions that work on any Linux distribution would be:

```
python3 -m pip install --user PyQt5==5.14
python3 -m pip install --upgrade --user guiscrcpy
```

This also takes care of upgrading to the latest version of guiscrcpy in case the user installed a previous version.

**Comment by srevinsaju** [comment]
yup, I faced a lot of these issues, when i was on Ubuntu, I used to mention this in the documentation during that time, the guiscrcpy documentation is soo.. outdated right now, will have to include a lot of stuff, release 3.0.post2 at PYPI, now fixing the PyQt5==5.14 bug,

**Comment by srevinsaju** [comment]
https://pypi.org/project/guiscrcpy/
