### ISSUE TITLE
ImportError: Failed to initialize: Bad git executable.

### ISSUE THREAD

**Issue by snbryrlh** [srevinsaju/guiscrcpy#57]
[Windows 8] Just using Scrcpy about few weeks ago. And then just try yours yesterday and try the 1.11.0 ones and its works well. Can you tell me step by step installing the v3.0 one. I think I have several problems on it.

**Comment by srevinsaju** [comment]
@snbryrlh thanks for using guiscrcpy, I will let you know everything when I release 3.2. Currently the method to install this on WIndows is a bit cumbersome. An new user might not know exactly how to fix it .

If you are interested in short:
* Download scrcpy
* download adb
* Add adb to PATH
* Add scrcpy to PATH
* Install guiscrcpy
* Run guicrcpy
* Enjoy

The first four steps should be automatically be done in #58, so keep watching for it. These were automatically done previously, but now, it had been stopped due to UAC practice,.

**Comment by srevinsaju** [comment]
@snbryrlh any help needed?

**Comment by WahyuKuncoro** [comment]
@srevinsaju i got problem when trying to run 3.0. i have all requirement. adding `scrcpy` to path, using 'pip3 install guiscrcpy==3.0 --user' to install, and running the executable, but i got this error

`C:\Users\Wahyu>guiscrcpy
Traceback (most recent call last):
  File "site-packages\git\__init__.py", line 83, in <module>
  File "site-packages\git\__init__.py", line 73, in refresh
  File "site-packages\git\cmd.py", line 287, in refresh
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "guiscrcpy", line 3, in <module>
  File "C:\Users\SS\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "guiscrcpy\launcher.py", line 51, in <module>
  File "C:\Users\SS\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "guiscrcpy\lib\ver.py", line 24, in <module>
  File "C:\Users\SS\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "site-packages\git\__init__.py", line 85, in <module>
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
`
trying to manually remove config as you said, but i have no idea which directory to go..
also `C:\Users\SS\AppData\Local\...`, user SS doesn't even exist on my pc

**Comment by srevinsaju** [comment]
@WahyuKuncoro 
What does
```
pip3 install https://github.com/srevinsaju/guiscrcpy/archive/master.zip
```
do?

**Comment by WahyuKuncoro** [comment]
@srevinsaju here's after `pip3 install https://github.com/srevinsaju/guiscrcpy/archive/master.zip`

> C:\Users\Wahyu>pip3 install https://github.com/srevinsaju/guiscrcpy/archive/master.zip
Collecting https://github.com/srevinsaju/guiscrcpy/archive/master.zip
  Downloading https://github.com/srevinsaju/guiscrcpy/archive/master.zip
     / 3.1 MB 63 kB/s
Requirement already satisfied: PyQt5==5.14.1 in c:\users\wahyu\appdata\local\programs\python\python37\lib\site-packages (from guiscrcpy===3.x.src.dev) (5.14.1)
Requirement already satisfied: psutil in c:\users\wahyu\appdata\local\programs\python\python37\lib\site-packages (from guiscrcpy===3.x.src.dev) (5.7.0)
Requirement already satisfied: pynput in c:\users\wahyu\appdata\local\programs\python\python37\lib\site-packages (from guiscrcpy===3.x.src.dev) (1.6.7)
Requirement already satisfied: gitpython in c:\users\wahyu\appdata\local\programs\python\python37\lib\site-packages (from guiscrcpy===3.x.src.dev) (3.1.0)
Requirement already satisfied: PyQt5-sip<13,>=12.7 in c:\users\wahyu\appdata\local\programs\python\python37\lib\site-packages (from PyQt5==5.14.1->guiscrcpy===3.x.src.dev) (12.7.1)
Requirement already satisfied: six in c:\users\wahyu\appdata\local\programs\python\python37\lib\site-packages (from pynput->guiscrcpy===3.x.src.dev) (1.14.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\wahyu\appdata\local\programs\python\python37\lib\site-packages (from gitpython->guiscrcpy===3.x.src.dev) (4.0.2)
Requirement already satisfied: smmap<4,>=3.0.1 in c:\users\wahyu\appdata\local\programs\python\python37\lib\site-packages (from gitdb<5,>=4.0.1->gitpython->guiscrcpy===3.x.src.dev) (3.0.1)
Installing collected packages: guiscrcpy
  Attempting uninstall: guiscrcpy
    Found existing installation: guiscrcpy 3.0
    Uninstalling guiscrcpy-3.0:
      Successfully uninstalled guiscrcpy-3.0
    Running setup.py install for guiscrcpy ... done
Successfully installed guiscrcpy-3.x.src.dev
trying to run `guiscrcpy` here's what i got
> C:\Users\Wahyu>guiscrcpy
Traceback (most recent call last):
  File "c:\users\wahyu\appdata\local\programs\python\python37\lib\site-packages\git\__init__.py", line 83, in <module>
    refresh()
  File "c:\users\wahyu\appdata\local\programs\python\python37\lib\site-packages\git\__init__.py", line 73, in refresh
    if not Git.refresh(path=path):
  File "c:\users\wahyu\appdata\local\programs\python\python37\lib\site-packages\git\cmd.py", line 278, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()
All git commands will error until this is rectified.
This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception
Example:
    export GIT_PYTHON_REFRESH=quiet
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\Wahyu\AppData\Local\Programs\Python\Python37\Scripts\guiscrcpy-script.py", line 11, in <module>
    load_entry_point('guiscrcpy===3.x.src.dev', 'console_scripts', 'guiscrcpy')()
  File "c:\users\wahyu\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\wahyu\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "c:\users\wahyu\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2324, in load
    return self.resolve()
  File "c:\users\wahyu\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\wahyu\appdata\local\programs\python\python37\lib\site-packages\guiscrcpy\launcher.py", line 51, in <module>
    from guiscrcpy.lib.ver import version
  File "c:\users\wahyu\appdata\local\programs\python\python37\lib\site-packages\guiscrcpy\lib\ver.py", line 24, in <module>
    import git
  File "c:\users\wahyu\appdata\local\programs\python\python37\lib\site-packages\git\__init__.py", line 85, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc))
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()
All git commands will error until this is rectified.
This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception
Example:
    export GIT_PYTHON_REFRESH=quiet

**Comment by srevinsaju** [comment]
@WahyuKuncoro 
try
```bash
set GIT_PYTHON_GIT_EXECUTABLE=C:\Program Files\Git\cmd\git.exe
```

**Comment by WahyuKuncoro** [comment]
@srevinsaju thanks man, i now its working

**Comment by srevinsaju** [comment]
Ok @WahyuKuncoro , the error was mentioned here https://github.com/gitpython-developers/GitPython/issues/816 for your reference
Hope you like guiscrcpy
