### ISSUE TITLE
[Feature request] Portable edition (windows)

### ISSUE THREAD

**Issue by seiya-git** [srevinsaju/guiscrcpy#6]
Hello. Can you make portable installer? I don't want store configuration in my system

**Comment by srevinsaju** [comment]
Yes, sure, the next release may include a portable installer. In the sense of portable, it will be a zipped folder of all the necessary DLLs and EXE file. Hope it will be fine. Will mark this as a feature request.

**Comment by srevinsaju** [comment]
Fixed, see Releases v1.10.1

You may close the issue, or issue will be closed in 48hrs
