### ISSUE TITLE
Trebuchet fonts should be installed

### ISSUE THREAD

**Issue by tukusejssirs** [srevinsaju/guiscrcpy#63]
Tasks
- [ ] Add a note on how to install the fonts in the docs;
- [ ] Make the ‘moving handle’ output the way it should (see screenshot below)

---

I tried to install the fonts using the following commands, but it does not work.

```bash
sudo cp -r "${XDG_GIT_DIR}/others/guiscrcpy/guiscrcpy/ui/fonts" /usr/share/fonts/trebuchet
sudo fc-cache -f
```

![Screenshot from 2020-02-19 19-42-48](https://user-images.githubusercontent.com/5111894/74866015-008ac080-534a-11ea-8708-5942bf0747a1.png)

**Comment by srevinsaju** [comment]
Fixed on #69
