### ISSUE TITLE
Add an option to select which device should be connected to

### ISSUE THREAD

**Issue by tukusejssirs** [srevinsaju/guiscrcpy#64]
When multiple devices are connected to the computer, the user should be able to select a specific device. One might want to connect to multiple devices at the same time, therefore it might be a good idea to manage this situation too (e.g. `guiscrcpy` should be able to create multiple `adb` servers).

**Comment by JimWu1987** [comment]
Hi,
I need to control mutiple cellphones with my laptop at the same time. So I too wish there is an option to select which device should be connected to.

**Comment by srevinsaju** [comment]
Thanks for showing your interest in guiscrcpy 

@JimWu1987, will surely consider this when version 3.5 is released

**Comment by JimWu1987** [comment]
Hi,
I'm so happy to hear that!
Thanks!
Jim


Jim806646984@outlook.com
 
From: Srevin Saju
Date: 2020-03-17 01:13
To: srevinsaju/guiscrcpy
CC: Jim Wu; Mention
Subject: Re: [srevinsaju/guiscrcpy] Add an option to select which device should be connected to (#64)
Thanks for showing your interest in guiscrcpy
@JimWu1987, will surely consider this when version 3.5 is released

**Comment by srevinsaju** [comment]
Closed by [3.7](https://github.com/srevinsaju/guiscrcpy/releases/3.7
