### ISSUE TITLE
Add an option to select the connection type (wired or wireless)

### ISSUE THREAD

**Issue by tukusejssirs** [srevinsaju/guiscrcpy#65]
One might want to connect to the phone by USB cable, others might want to connect wirelessly. Let the users choose the connection type. Please keep in mind that if the users can connect to multiple devices (see #64), you should let the users choose the connection type per device.

**Comment by srevinsaju** [comment]
Closed by [3.7](https://github.com/srevinsaju/guiscrcpy/releases/3.7)
