### ISSUE TITLE
scrcpy window not launching with 3.2

### ISSUE THREAD

**Issue by yochananmarqos** [srevinsaju/guiscrcpy#67]
With the previous commit it worked, now it does not after updating to 3.2. There are no errors and the `scrcpy` process is running.

**Comment by srevinsaju** [comment]
@yochananmarqos Could you share me your logs (in terminal) and those in `~/.config/guiscrcpy`

**Comment by yochananmarqos** [comment]
The only logs I have there are from January 28th & 29th. Again, there are no errors in the terminal. Running `scrcpy` on it's own works fine.

**Comment by srevinsaju** [comment]
Can you send me your configuration file?

**Comment by yochananmarqos** [comment]
I tried deleting it and let it regenerate with no difference.

```
{
    "adb": "/usr/bin/adb",
    "bitrate": 8000,
    "cmx": [],
    "dimension": null,
    "dispRO": true,
    "extra": "",
    "fullscreen": false,
    "paths": [
        "bin",
        "/usr/bin",
        "~/.local/bin",
        "~/bin",
        "/usr/local/bin"
    ],
    "scrcpy": "/usr/bin/scrcpy",
    "swtouches": false
}
```

**Comment by srevinsaju** [comment]
@yochananmarqos try changing `"cmx"` to `""`

**Comment by yochananmarqos** [comment]
That worked, thanks!

**Comment by srevinsaju** [comment]
@yochananmarqos I have createda commit https://github.com/srevinsaju/guiscrcpy/commit/576ce7d3dbd2de157bd78e305a45f267b79f2960 but I would prefer not releasing it to the AUR, rather, `guiscrcpy-beta` or `guiscrcpy-dev` would be a better or rather not releasing it

The current plan of my release would be
`3.1` (stable)
`3.2` (unstable)
`3.3` (stable)
`3.4` (unstable)
`3.5` (stable)
`3.6` (unstable)
`3.7`(unstable)
`3.8` (stable)
`3.9` (unstable)
:  
: 
Following the Fibonacci sequence (exception is 3.2)

**Comment by yochananmarqos** [comment]
Alright. Just mark the unstable releases as pre-releases on GitHub like you have been.

**Comment by srevinsaju** [comment]
Sure,
PS: will you be creating `-beta` on the AUR?

**Comment by yochananmarqos** [comment]
No, there's already `guiscrcpy-git` so there wouldn't really be much point.

**Comment by srevinsaju** [comment]
Ok, thanks
