### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources.py2_warn'

### ISSUE THREAD

**Issue by m4heshd** [srevinsaju/guiscrcpy#72]
Following error occurs whenever i try to run the downloaded exe build.

![image](https://user-images.githubusercontent.com/6711514/76146972-f5f85700-60bd-11ea-99f3-bdf20d506bf7.png)

Is there something I'm missing? Been using `scrcpy` for a long time and it works fine.

**Comment by srevinsaju** [comment]
May I know which version is this? To my knowledge, I have fixed it in v3.4 (pre) and forward versions.

**Comment by srevinsaju** [comment]
v3.3. Fixed exe here: https://github.com/srevinsaju/guiscrcpy/suites/540351218/artifacts/3255283

**Comment by srevinsaju** [comment]
@m4heshd  i have released [3.3.1](https://github.com/srevinsaju/guiscrcpy/releases/3.3.1) with the same link. Thanks for pointing it out again

**Comment by srevinsaju** [comment]
Closed by [3.5](https://github.com/srevinsaju/guiscrcpy/releases/tag/3.5)
