### ISSUE TITLE
Windows EXE fail on install_fonts script

### ISSUE THREAD

**Issue by scrakcho** [srevinsaju/guiscrcpy#73]
![Sin título](https://user-images.githubusercontent.com/6636661/76311077-6b3b7600-62d0-11ea-9ebd-b2e4f8e950bc.png)

**Comment by srevinsaju** [comment]
Thanks, is this 3.3 or 3.4?

**Comment by scrakcho** [comment]
Is the last 3.4 (pre) EXE available for download, i have tried to download a preview version but the artifacts same to be removed so...
scrcpy -> 1.12.1
guiscrcpy -> 3.4

**Comment by srevinsaju** [comment]
Thanks for the information. Does the exe work after manually installing Titillium Web Font from Google Fonts

 https://fonts.google.com/specimen/Titillium+Web
Titillium Web - Google Fonts

**Comment by srevinsaju** [comment]
Does the guiscrcpy.exe work from version 3.3, (3.5 is still a work in progress and may go buggy, and 3.4 is a development release. 3.3 is the stable tested version)

**Comment by scrakcho** [comment]
Hi @srevinsaju ,

Sorry about my news but the 3.3 dont work and installing the Google Fonts (Titillium Web) not helped (I have tryed to install the fonts with the right mouse button and option install... but what logic have this fonts with the temp and random folder that the instaler search?)

**Comment by srevinsaju** [comment]
@scrakcho I cannot understand the language in your log. Which is your native language. 
PS: Does the PYPI (pip) package work for you

**Comment by scrakcho** [comment]
Spanish, basically the log say that the path cant be found C:\.......\Temp\_MEIxxxxxx\guiscrcp\ui\fonts

**Comment by srevinsaju** [comment]
@scrakcho the logs look like you are not using version 3.3.
If you are using version 3.3, you are probably likely to get another Traceback,
If you know Python, here is 3.3's code:
https://github.com/srevinsaju/guiscrcpy/blob/6e4bdc8d6aa60254177c138121b39c670a540733/guiscrcpy/platform/windows.py#L20-L54

As you can see, there is no `install_font` here in version 3.4 and 3.5
https://github.com/srevinsaju/guiscrcpy/pull/71/files#diff-a49c174a87b10a60b3fc78112e7259d9R58-R81

If you had sent me the logs of 3.3 exe failure, it would be helpful for fixing future errors too
Thanks

**Comment by scrakcho** [comment]
![Sin título](https://user-images.githubusercontent.com/6636661/76871446-5b410a80-686b-11ea-9de9-2bcb2f95015a.png)

**Comment by scrakcho** [comment]
Hello @srevinsaju , any news about that?

**Comment by srevinsaju** [comment]
@scrakcho I have pushed the commit https://github.com/srevinsaju/guiscrcpy/commit/7db8ed04f0d01d8d857b357d3df2500e8266691f

**Comment by srevinsaju** [comment]
@scrakcho try this out and let me know https://github.com/srevinsaju/guiscrcpy/suites/540351218/artifacts/3255283

**Comment by scrakcho** [comment]
Now with the last .EXE work! 
Thanks! ;)
