### ISSUE TITLE
FileNotFoundError v3.4

### ISSUE THREAD

**Issue by ricjonsu098** [srevinsaju/guiscrcpy#75]
Hi, I encountered this error when running the 3.4 pre version. I already added scrcpy to the env variables

![image](https://user-images.githubusercontent.com/35645526/77641900-c25f6d00-6f97-11ea-81e7-7a92bc067960.png)

**Comment by srevinsaju** [comment]
@ricjonsu098  Thanks, this is a known issue with v3.4. Please use stable 3.3 and let me know if it works

**Comment by ricjonsu098** [comment]
> @ricjonsu098 Thanks, this is a known issue with v3.4. Please use stable 3.3 and let me know if it works

with stable 3.3 I get the issue #72

**Comment by srevinsaju** [comment]
@ricjonsu098 Is it fixed by this exe ?https://github.com/srevinsaju/guiscrcpy/suites/540351218/artifacts/3255283

**Comment by srevinsaju** [comment]
@ricjonsu098 i have released [3.3.1](https://github.com/srevinsaju/guiscrcpy/releases/3.3.1) with the same link. Thanks for pointing it out again

**Comment by ricjonsu098** [comment]
Works great now. Thanks for the great support!
