### ISSUE TITLE
Windows 10 64Bit - Issue

### ISSUE THREAD

**Issue by Gallie2k** [srevinsaju/guiscrcpy#78]
Hi,
Downloaded guiscrcpy yesterday 3.5v Beta Windows.exe and also manually downloaded scrcpy-win64-v1.21.1, I put the guiscrcpy inside the same folder and added it to my Enviroment Variables (User Path), i have tried running it as administrator and also through CMG this is the error it is saying.
//////////////////////////Start\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
D:\Desktop\Scrcpy>guiscrcpy.exe
No conda env active, defaulting to base
Traceback (most recent call last):
  File "site-packages\git\__init__.py", line 83, in <module>
  File "site-packages\git\__init__.py", line 73, in refresh
  File "site-packages\git\cmd.py", line 278, in refresh
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts\guiscrcpy", line 3, in <module>
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "guiscrcpy\launcher.py", line 51, in <module>
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "guiscrcpy\lib\ver.py", line 24, in <module>
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "site-packages\git\__init__.py", line 85, in <module>
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

[11508] Failed to execute script guiscrcpy
//////////////////////////Stop\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

I assume i have done something wrong but i have followed the guide.

**Comment by srevinsaju** [comment]
Thanks, this is an issue with GitPython, 
Here is another user who had this problem and the solution to solve this https://github.com/srevinsaju/guiscrcpy/issues/57#issuecomment-591899120

**Comment by Gallie2k** [comment]
Hi,

Thanks for the update on the other link.....but that still didnt work once i found Git online and installed it aswell as setting the directory it now works fine (it does not mention anywhere that i had to install Git for this to work so might be worth updating the windows guide

**Comment by srevinsaju** [comment]
thanks, I will update the wiki. I apologize for that error, I guess its causing a lot of problems for other windows users too. I will fix that in 3.6

**Comment by Gallie2k** [comment]
Great thanks for your very quick help and this program is great! so thanks again for the work you are all doing to develop the software

**Comment by DesignerdriP** [comment]
Did you make sure to include python in path during the installation ?
