### ISSUE TITLE
Crash on startup if ~/.local/share/applications/ does not exist

### ISSUE THREAD

**Issue by cameel** [srevinsaju/guiscrcpy#80]
Hello, I encountered a small issue while trying out the application on Linux. Fortunately it seems pretty easy to solve. Details below.

When I launch the application, it crashes immediately:
``` python
Traceback (most recent call last):
File "/usr/bin/guiscrcpy", line 11, in <module>
load_entry_point('guiscrcpy==3.5', 'console_scripts', 'guiscrcpy')()
File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
return ep.load()
File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2450, in load
return self.resolve()
File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2456, in resolve
module = __import__(self.module_name, fromlist=['__name__'], level=0)
File "/usr/lib/python3.8/site-packages/guiscrcpy/launcher.py", line 72, in <module>
cfgmgr = InterfaceConfig()
File "/usr/lib/python3.8/site-packages/guiscrcpy/lib/config.py", line 48, in __init__
self.check_file()
File "/usr/lib/python3.8/site-packages/guiscrcpy/lib/config.py", line 97, in check_file
self.os.create_desktop()
File "/usr/lib/python3.8/site-packages/guiscrcpy/platform/linux.py", line 89, in create_desktop
with open(os.path.join(os.path.expanduser('~/.local/share/applications/'), 'guiscrcpy.desktop'), 'w') as w:
FileNotFoundError: [Errno 2] No such file or directory: '/home/cameel/.local/share/applications/guiscrcpy.desktop'
```

Apparently, it tries to open `~/.local/share/applications/guiscrcpy.desktop` for writing while the directory it's supposed to be in does not exist. Assuming that any particular directory in user's home exists is probably not a good idea. I think that the program should create it if it does not exist.

Also, creating this file at startup seems completely unnecessary to me so my suggestion is to simply remove the offending line. It's the job of the package manager (or installer). For example the [Arch Linux PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=guiscrcpy) already installs the `.desktop` file in `/usr/share/applications/` as it should so I end up with two copies of the file. I would expect packages for other systems to do something similar.

**Comment by srevinsaju** [comment]
@cameel, thanks for the information.
I would like to know some information:
* which Linux distribution are you using (Arch Linux?)


regarding installing the file to ~/.local/share/applications, many people complained to me, that, they need a desktop launcher. assuming you are using Arch Linux, you might not know that, there is not no one interested in packaging `guiscrcpy` for other Linux distribution. I have more that 5k downloads on PYPI per month. and popularity on the AUR is extremely less, (2-3 votes). as majority of my Linux users are dependent on the PYPI wheels, I would have to keep the desktop file. guiscrcpy was created as a hope of removing all command line applications of scrcpy. It was meant to help people who do not know how to use the command line.

Regarding the AUR, it is upto @yochananmarqos to keep it or remove it. I have no take / right to remove that one. The only official package for `guiscrcpy` is the PYPI wheel and the binary downloads at the Releases page. The author does not take any legal rights / ownership over other packages. 


Now how to solve this problem:
thanks for looking into this and providing insights, I have got some new clues on how to fix it better.
assuming, I fixed all the path creating procedures,
how is it to ask a dialog to the user, asking "Do you want to create a desktop shortcut?". I guess, that would be a non-biased decision to make. I am looking for your opinion too @cameel .


by the way, thanks for bringing your interest to guiscrcpy. I am always here to make it better, and keep learning

**Comment by yochananmarqos** [comment]
I agree with asking the user if they want a desktop file created on first run. There are quite a few other applications that do that as well.

**Comment by cameel** [comment]
Yes, I'm on Arch Linux.

Oh, so your primary method of distribution is a python wheel? Sorry, I thought you're relying on packages or installers. In that case I think you can handle the shortcuts in `setup.py`.

As to whether to ask the user - I definitely would not ask about the menu shortcut (the file that goes into `share/applications`) - because, at least on Linux, I think it's expected that you'll find the app in the menu when you install a package and users are not typically asked about it. On Windows they are but that's because the installation process is more interactive there.

A desktop shortcut on the other hand may warrant asking but I personally would suggest not doing it. User can easily delete the shortcut from the desktop and it's the same effort as clicking "no" in a dialog.

But anyway, I did not mean to distract you from the main issue. Having a duplicate `.desktop` file is really a **very** minor thing and I suggested fixing it mostly because it would at the same time fix this crash. But well, this made me check how to handle it in `setup.py` and it looks like there's a very easy and elegant solution so I'll post it as a new issue.

**Comment by cameel** [comment]
@srevinsaju @yochananmarqos Here's the issue that explains my proposed solution for shortcuts in more detail #82.

But like I said there - it's not such a big deal. The crash is more important :)

**Comment by yochananmarqos** [comment]
@cameel By the way, you never did say how you installed `guiscrcpy`. One of the AUR packages or with Pip?

**Comment by cameel** [comment]
I used your PKBGUILD from AUR: https://aur.archlinux.org/packages/guiscrcpy/

**Comment by yochananmarqos** [comment]
@cameel I just removed `python-pyshortcuts` as a dependency, I forgot it was unneeded. Please update `guiscrcpy`, remove `python-pyshortcuts` and see if it still happens.

**Comment by cameel** [comment]
Updated. It does not crash.

But I wonder why. The line is still there and there wasn't anything related to `python-shortcuts` in the traceback.

But yeah, looks like your change fixed it for me, so I can get rid of my local patch. Thanks!

**Comment by srevinsaju** [comment]
Merged to `master` by https://github.com/srevinsaju/guiscrcpy/commit/2bf2ce887cfd53a10a001dae09a0d47889492d3a
