### ISSUE TITLE
Wrong screen orientation on devices where landscape is the default

### ISSUE THREAD

**Issue by cameel** [srevinsaju/guiscrcpy#81]
I tried using guiscrcpy on [Gemini PDA](https://en.wikipedia.org/wiki/Gemini_(PDA)) but I'm running into a problem where the content of the screen is displayed sideways, in portrait orientation while the device itself is displaying it in landscape (which is its normal orientation).

![guiscrcpy-on-gemini-pda-landscape-displayed-in-portrait](https://user-images.githubusercontent.com/137030/79053376-3149f080-7c3d-11ea-9ef3-83b0e098002b.png)

Moreover, clicking it with a mouse triggers a touch event in the wrong spot - it works as if the screen was actually oriented correctly so the thing you actually touch is not the thing you see in that spot.

The weird thing is that it works like this only for the first `scrcpy` window. If i click "START SCRCPY" button multiple times, subsequent instances have the correct orientation and touch locations match screen content. It's only the first one launched that has the wrong orientation.

**Comment by srevinsaju** [comment]
Thanks. Interesting. I would check it out with @rom1v and let you know. its quite late on my timezone 💤😴, I will let you know tomorrow

**Comment by cameel** [comment]
Sure, it isn't really urgent. I'm not expecting you to lose sleep over it :) Thanks for developing the app and releasing it as open source to begin with. It would be nice to have this issue fixed but I can work around it by launching multiple instances and closing the first one so please take your time.

**Comment by srevinsaju** [comment]
@cameel I will fix this issue in v3.8

**Comment by srevinsaju** [comment]
@cameel A default rotation setting has been added to `master` if that helps; let me know if it does

**Comment by cameel** [comment]
@srevinsaju Thanks for the fix. Sorry for a late answer but I did not have time to test it during the week. I did play with it during the weekend though and, while the orientation can now be changed, it has some quirks:
1) I launch `guiscrcpy`, change `Default Rotation` to `Landscape` and click `START SCRCPY`. It does show the screen in the right orientation but with huge top and bottom margins. It's as if the window size was still set for the landscape orientation:

    ![gemini-pda-guiscrcpy-landscape](https://user-images.githubusercontent.com/137030/82157733-92d82d00-9883-11ea-8f1c-5e50dd3fc22f.png)

    When I resize the window vertically to hide the margin, the screen size decreases as well, adding margins on the left and right:

    ![gemini-pda-guiscrcpy-landscape-resized-vertically](https://user-images.githubusercontent.com/137030/82157828-0f6b0b80-9884-11ea-9b40-917b9b6c4323.png)
2) If I start another `scrcpy` instance (by clicking `START SCRCPY` button again while the previous one is still running), the `Default Orientation` setting is ignored for that new instance and the orientation is wrong again:
    ![gemini-pda-guiscrcpy-landscape-second-instance](https://user-images.githubusercontent.com/137030/82157919-b18af380-9884-11ea-8f9e-88b3fdb57822.png)
3. If I start one instance at `Default Orientation` and then (without closing it) change orientation to `Portrait` and launch another instance, the second instance shows up horizontal and without margins - which is what should be happening for `Landscape` instead:
    ![gemini-pda-guiscrcpy-portrait-second-instance](https://user-images.githubusercontent.com/137030/82158024-5c9bad00-9885-11ea-9690-3d5147b15f2a.png)
4. Not sure if it's related, but the free-floating bars with shortcuts show up in top-left corner of the desktop while the window showing phone screen is centered on the screen and not aligned with them. They also do not move together with the screen window, though I don't know if they're supposed to (would be convenient though).

**Comment by srevinsaju** [comment]
@cameel It is all related to the GPU specification which are specific on your device, i.e Gemini PDA. It is possible that the Tablet has a a orientation problem, `scrcpy` server decodes the GPU device specification and can vary from device to device. For your reference, this might help you in finding your device specific error:
https://github.com/Genymobile/scrcpy/issues/972

@rom1v had created the solution, to allow manual rotation, although, to support for some device GPUs which do not follow the standrd guidelines in GPU decoding.

Alternatively, use `Ctrl`+`R` to raotate device while its running

> Not sure if it's related, but the free-floating bars with shortcuts show up in top-left corner of the desktop while the window showing phone screen is centered on the screen and not aligned with them. They also do not move together with the screen window, though I don't know if they're supposed to (would be convenient though).

I have been trying to find a solution for the same. Currently, the toolbars are completely independant from `scrcpy`. Maybe this info might help

* `scrcpy` is a command line utility that helps to display your screen. You might need to remmber the commands to display your device etc.
* `guiscrcpy` is a ui + config + scrcpy interface which are independant of each other. `guiscrcpy` tells `scrcpy` what to do. `scrcpy` is built on SDL and therefore its super fast. However, to connect the toolbar to the device screen, we need to use a slower User interface Library, or example `Qt`.
To get a toolbar + screen snapped interface, you might like to use [QtScrcpy](https://github.com/barry-ran/QtScrcpy) by @barry-ran

**Comment by cameel** [comment]
I just tried `scrcpy` and it behaves just like `guiscrcpy` with `Default Rotation`. So this means that the issue must actually be in `scrcpy`.

> It is possible that the Tablet has a a orientation problem

Yeah, it's very possible that the device is reporting something weird (BTW, thanks for the link to the issue, I'll check it out when I have some time to play with it again). But I think there's still something going wrong on `scrcpy` (or `guiscrcpy`) side because:
- The orientation is correct for the second instance.
- The touch events do not match mouse position.

If it was just orientation reported wrong, I think it would always display it rotated and touch screen would also be rotated, right?

> I have been trying to find a solution for the same. Currently, the toolbars are completely independant from scrcpy.

OK. I did try QtScrcpy earlier and I remembered that it had sticky bars so I just thought I'd report it here. But if it's a technical limitation, well, can't be helped :)

**Comment by srevinsaju** [comment]
@cameel Yes, what I meant is that the GPU might not be decoding the screen over the current display. The mechanism of display (GPU) and input (CPU) works independantly. 
* GPU sends the screen to the PC
* PC CPU sends `(x, y)` coordinates relative the the device top left corner. The CPU might send positions differently. For example, if you tap on the left most part of the screen on your PC (scrcpy), in reality, it might tap on the top of your device (your Gemini PDA); If you have time, you might check the master brain of @rom1v in creating scrcpy so that it remains the fastest android screen mirroring system in the world
